BATCH4 = [
    {"id": "devil-ray", "name": "Devil Ray", "emoji": "🐟", "type": "Fish", "habitat": "Ocean",
     "livesIn": "Warm oceans worldwide — open water near coasts", "diet": "Plankton and small fish filtered or caught",
     "size": "Wings wider than a dining table", "funFact": "Devil rays leap completely out of the water and belly-flop back down!",
     "extraFact": "Horn-like head fins gave them the name devil ray.",
     "funFacts": ["Devil rays leap completely out of the water and belly-flop back down!", "They filter-feed like mantas with wide mouths.", "Long whip-like tail has no stinger unlike stingrays."],
     "didYouKnowFacts": ["They travel in large schools near the surface.", "Pregnancy lasts about a year for one pup.", "Satellite tags show they cross entire ocean basins."],
     "livesInFacts": ["Warm oceans worldwide — open water near coasts", "Upwellings bring plankton they follow.", "Cleaning stations on reefs remove parasites."],
     "dietFacts": ["Plankton and small fish filtered or caught", "Gill rakers trap tiny drifting animals.", "They also scoop small schooling fish."],
     "sizeFacts": ["Wings wider than a dining table", "Diamond-shaped body is built for gliding.", "White shoulder patches mark some species."]},
    {"id": "japanese-spider-crab", "name": "Japanese Spider Crab", "emoji": "🦀", "type": "Crustacean", "habitat": "Ocean",
     "livesIn": "Pacific Ocean floor near Japan — rocky and sandy depths", "diet": "Dead animals, algae, and shellfish",
     "size": "Leg span wider than a car in the largest individuals", "funFact": "Japanese spider crabs have the longest legs of any crab!",
     "extraFact": "They decorate their shell with sponges and anemones for camouflage.",
     "funFacts": ["Japanese spider crabs have the longest legs of any crab!", "A knobby, long-legged body looks like a spider.", "They walk slowly on the deep seafloor."],
     "didYouKnowFacts": ["They can live up to 100 years.", "Depths below 600 feet keep them hidden.", "Fishing once threatened populations near Japan."],
     "livesInFacts": ["Pacific Ocean floor near Japan — rocky and sandy depths", "Cold deep water slows their growth.", "Molting happens in sheltered rocky crevices."],
     "dietFacts": ["Dead animals, algae, and shellfish", "Long legs reach food other crabs cannot.", "They scavenge more than chase live prey."],
     "sizeFacts": ["Leg span wider than a car in the largest individuals", "Carapace body is only about a foot wide.", "Spiny, bumpy shell collects camouflage creatures."]},
    {"id": "bearded-dragon", "name": "Bearded Dragon", "emoji": "🦎", "type": "Reptile", "habitat": "Desert",
     "livesIn": "Australian deserts and dry woodlands", "diet": "Insects, flowers, and leafy greens",
     "size": "About as long as your forearm", "funFact": "Bearded dragons puff a spiky throat pouch and darken their beard when upset!",
     "extraFact": "They wave one front leg slowly to show submission.",
     "funFacts": ["Bearded dragons puff a spiky throat pouch and darken their beard when upset!", "They bask on rocks each morning to warm up.", "A third eye on top detects shadows from birds."],
     "didYouKnowFacts": ["They are popular pet lizards worldwide.", "Males bob their heads quickly to claim territory.", "They can run on hind legs for short bursts."],
     "livesInFacts": ["Australian deserts and dry woodlands", "Sandy soil is easy to dig for sleeping burrows.", "They climb low bushes to escape ground heat."],
     "dietFacts": ["Insects, flowers, and leafy greens", "Young dragons eat mostly insects for growth.", "Adults add more plants as they age."],
     "sizeFacts": ["About as long as your forearm", "Spiky scales around the throat look like a beard.", "Flat body helps them squeeze under rocks."]},
    {"id": "emerald-tree-boa", "name": "Emerald Tree Boa", "emoji": "🐍", "type": "Reptile", "habitat": "Jungle",
     "livesIn": "Amazon rainforest — low branches over water", "diet": "Small mammals, birds, and lizards",
     "size": "About as long as a baseball bat", "funFact": "Emerald tree boas loop coils over branches and strike from above!",
     "extraFact": "Juveniles are red or orange before turning bright green.",
     "funFacts": ["Emerald tree boas loop coils over branches and strike from above!", "Heat-sensing pits along the lips find warm prey.", "White zigzag markings break up their outline."],
     "didYouKnowFacts": ["They are not venomous — they squeeze small prey.", "They give birth to live young in some populations.", "Their grip is strong enough to hang from one tail loop."],
     "livesInFacts": ["Amazon rainforest — low branches over water", "Humid air keeps their skin healthy.", "Night hunting matches when rodents are active."],
     "dietFacts": ["Small mammals, birds, and lizards", "Long front teeth hook prey before wrapping coils.", "They swallow head-first while hanging."],
     "sizeFacts": ["About as long as a baseball bat", "Bright green scales mimic sunlit leaves.", "Large head and jaw fit bigger prey than thin body suggests."]},
    {"id": "dall-sheep", "name": "Dall Sheep", "emoji": "🐏", "type": "Mammal", "habitat": "Arctic",
     "livesIn": "Alaska and northwest Canada — alpine ridges", "diet": "Grasses, sedges, and alpine plants",
     "size": "About as heavy as a large dog — rams much bigger", "funFact": "Male Dall sheep clash horns with crashes heard far away!",
     "extraFact": "Their horns grow rings like tree trunks showing age.",
     "funFacts": ["Male Dall sheep clash horns with crashes heard far away!", "Pure white coat matches snowy peaks.", "They stand on knife-edge ridges to escape wolves."],
     "didYouKnowFacts": ["Horns can weigh 30 pounds on old rams.", "Ewes and lambs stay in separate groups much of the year.", "Golden eagles threaten lambs on cliffs."],
     "livesInFacts": ["Alaska and northwest Canada — alpine ridges", "Wind-swept slopes grow the grasses they need.", "They use the same trails for generations."],
     "dietFacts": ["Grasses, sedges, and alpine plants", "Summer fat must last through harsh winters.", "Mineral licks draw them to special rocky spots."],
     "sizeFacts": ["About as heavy as a large dog — rams much bigger", "Curved horns stay with males for life.", "Compact hooves grip steep rock like climbing shoes."]},
    {"id": "hamerkop", "name": "Hamerkop", "emoji": "🦩", "type": "Bird", "habitat": "Ocean",
     "livesIn": "Africa and Madagascar — wetlands and rivers", "diet": "Fish, frogs, insects, and small reptiles",
     "size": "About as tall as a school backpack", "funFact": "Hamerkops build huge stick nests that can weigh over 100 pounds!",
     "extraFact": "Their hammer-shaped head and crest give them their name.",
     "funFacts": ["Hamerkops build huge stick nests that can weigh over 100 pounds!", "Several birds sometimes add to one nest.", "They stamp their feet in mud to stir up prey."],
     "didYouKnowFacts": ["Nests may include random objects like bones or litter.", "They bow and flap wings in courtship displays.", "Other birds and snakes sometimes steal the giant nests."],
     "livesInFacts": ["Africa and Madagascar — wetlands and rivers", "Shallow water and mudflats are hunting grounds.", "They perch on hippos and logs to fish."],
     "dietFacts": ["Fish, frogs, insects, and small reptiles", "Long bill grabs prey with a quick stab.", "They hunt more at dusk and dawn."],
     "sizeFacts": ["About as tall as a school backpack", "Brown plumage blends with muddy shores.", "Unique head shape is unlike any heron or stork."]},
    {"id": "glow-worm", "name": "Glow Worm", "emoji": "✨", "type": "Insect", "habitat": "Forest",
     "livesIn": "Caves and damp forests — New Zealand, Australia, and elsewhere", "diet": "Adults eat little or nothing; larvae trap flying insects",
     "size": "Larva about as long as a matchstick", "funFact": "Glow-worm larvae hang sticky silk strands that shine blue-green to trap insects!",
     "extraFact": "The light comes from a chemical reaction in their body.",
     "funFacts": ["Glow-worm larvae hang sticky silk strands that shine blue-green to trap insects!", "Flying insects fly toward the glow and get stuck.", "Adult beetles often live only a few days."],
     "didYouKnowFacts": ["New Zealand cave tours famous for thousands of glow worms.", "Only females and larvae glow brightly in some species.", "They are beetles, not worms, despite the name."],
     "livesInFacts": ["Caves and damp forests — New Zealand, Australia, and elsewhere", "Dark wet places protect the light display.", "Ceiling strands dangle over streams in caves."],
     "dietFacts": ["Adults eat little or nothing; larvae trap flying insects", "Mucus beads on silk snare midges and mosquitoes.", "Larvae suck the liquid inside caught insects."],
     "sizeFacts": ["Larva about as long as a matchstick", "Bioluminescent tail spot is brightest.", "Soft body lives on cave ceilings or log crevices."]},
    {"id": "clown-knifefish", "name": "Clown Knifefish", "emoji": "🐟", "type": "Fish", "habitat": "Jungle",
     "livesIn": "Southeast Asia — slow rivers and flooded forests", "diet": "Small fish, insects, and crustaceans",
     "size": "About as long as a baseball bat", "funFact": "Knifefish swim forward and backward using one long fin underneath!",
     "extraFact": "They sense prey with weak electric fields around their body.",
     "funFacts": ["Knifefish swim forward and backward using one long fin underneath!", "Round spots on young fish fade into a stripe as adults.", "They are popular in large aquarium tanks."],
     "didYouKnowFacts": ["They are mostly active at night.", "Electric organs help them navigate murky water.", "They can gulp air if oxygen is low."],
     "livesInFacts": ["Southeast Asia — slow rivers and flooded forests", "Vegetation tangles hide their thin body.", "Monsoon floods spread them into seasonal pools."],
     "dietFacts": ["Small fish, insects, and crustaceans", "A large mouth sucks prey in quickly.", "They hunt near the surface at night."],
     "sizeFacts": ["About as long as a baseball bat", "Knife-thin body slips between plant stems.", "Silvery scales flash when they turn."]},
    {"id": "flying-gurnard", "name": "Flying Gurnard", "emoji": "🐟", "type": "Fish", "habitat": "Ocean",
     "livesIn": "Warm sandy shores — Atlantic and Indo-Pacific", "diet": "Small crustaceans, worms, and fish on the bottom",
     "size": "About as long as a dinner plate", "funFact": "Flying gurnards spread huge wing-like fins that flash bright blue spots!",
     "extraFact": "They do not truly fly — the fins startle predators and show off.",
     "funFacts": ["Flying gurnards spread huge wing-like fins that flash bright blue spots!", "They crawl on finger-like fins across sand.", "Armored heads and cheeks crunch hard prey."],
     "didYouKnowFacts": ["They grunt or croak when caught.", "Pectoral fins reach past the tail when opened.", "Camouflage matches sand until they flare up."],
     "livesInFacts": ["Warm sandy shores — Atlantic and Indo-Pacific", "Shallow bays are perfect for walking on the bottom.", "They rest half-buried in sand."],
     "dietFacts": ["Small crustaceans, worms, and fish on the bottom", "Mouth is small but jaws are strong.", "They fan sand to uncover hidden prey."],
     "sizeFacts": ["About as long as a dinner plate", "Head spines look like armor plates.", "Dotted fins look like butterfly wings underwater."]},
    {"id": "viperfish", "name": "Viperfish", "emoji": "🐟", "type": "Fish", "habitat": "Ocean",
     "livesIn": "Deep oceans worldwide — twilight and midnight zones", "diet": "Small fish and crustaceans",
     "size": "About as long as a ruler", "funFact": "Viperfish have fangs so long they fold outside the mouth!",
     "extraFact": "A glowing lure on a spine attracts prey in the dark.",
     "funFacts": ["Viperfish have fangs so long they fold outside the mouth!", "They rise toward the surface at night to feed.", "Dark silver skin is nearly invisible in deep water."],
     "didYouKnowFacts": ["They swallow prey whole despite huge teeth.", "Photophores along the belly hide their shadow from below.", "Deep nets often bring up crushed specimens."],
     "livesInFacts": ["Deep oceans worldwide — twilight and midnight zones", "Vertical migration follows prey each day.", "Pressure at depth would crush surface fish."],
     "dietFacts": ["Small fish and crustaceans", "Lure light draws victims close before a snap.", "They eat little because meals are rare."],
     "sizeFacts": ["About as long as a ruler", "Hinged skull opens extra wide for big bites.", "Slender body saves energy in food-poor depths."]},
    {"id": "hoatzin", "name": "Hoatzin", "emoji": "🐦", "type": "Bird", "habitat": "Jungle",
     "livesIn": "Amazon and Orinoco river forests — swampy edges", "diet": "Leaves and buds — mostly tough marsh plants",
     "size": "About as long as a house cat", "funFact": "Hoatzin chicks have claws on their wings to climb trees after falling in the water!",
     "extraFact": "They digest leaves using bacteria like a cow in their crop.",
     "funFacts": ["Hoatzin chicks have claws on their wings to climb trees after falling in the water!", "A spiky crest and blue face make them look prehistoric.", "They sunbathe with wings spread to warm up."],
     "didYouKnowFacts": ["Their smell earned the nickname stinkbird.", "They are poor fliers and often crash through branches.", "Fossil relatives may date back millions of years."],
     "livesInFacts": ["Amazon and Orinoco river forests — swampy edges", "River islands with reeds are favorite spots.", "They nest over water so chicks can swim away from predators."],
     "dietFacts": ["Leaves and buds — mostly tough marsh plants", "Fermenting leaves in the crop takes hours to digest.", "Adults spend many hours each day just eating leaves."],
     "sizeFacts": ["About as long as a house cat", "Rusty-brown feathers and long tail look awkward in flight.", "Clawed wings appear only in young birds."]},
    {"id": "resplendent-quetzal", "name": "Resplendent Quetzal", "emoji": "🐦", "type": "Bird", "habitat": "Jungle",
     "livesIn": "Central American cloud forests — misty mountain trees", "diet": "Wild avocados and other fruit, plus insects",
     "size": "Body robin-sized — male tail feathers can be three feet long", "funFact": "Male quetzals have shimmering green tail plumes longer than their body!",
     "extraFact": "Ancient Maya and Aztec royalty wore quetzal feathers.",
     "funFacts": ["Male quetzals have shimmering green tail plumes longer than their body!", "They swallow fruit whole and regurgitate the pits.", "A red belly and green crest shine in cloudy light."],
     "didYouKnowFacts": ["They nest in rotting tree holes they barely fit into.", "The tail streamers were once collected for ceremonies.", "Cloud forest loss threatens their mountain home."],
     "livesInFacts": ["Central American cloud forests — misty mountain trees", "Cool wet air grows the fruit trees they need.", "They stay high in the canopy most of the day."],
     "dietFacts": ["Wild avocados and other fruit, plus insects", "They time breeding when avocados ripen.", "Insects feed growing chicks extra protein."],
     "sizeFacts": ["Body robin-sized — male tail feathers can be three feet long", "Females lack the extreme tail length.", "Metallic green feathers come from structure, not pigment."]},
]
