BATCH2 = [
    {"id": "southern-stingray", "name": "Southern Stingray", "emoji": "🐟", "type": "Fish", "habitat": "Ocean",
     "livesIn": "Atlantic and Caribbean — sandy bays and coral reefs", "diet": "Crabs, worms, and shellfish on the seafloor",
     "size": "Wings wider than a card table", "funFact": "Stingrays flap their wings like birds to swim over sand!",
     "extraFact": "A venomous spine near the tail is used only for defense.",
     "funFacts": ["Stingrays flap their wings like birds to swim over sand!", "Eyes sit on top while mouth and gills are underneath.", "They bury in sand with only eyes showing."],
     "didYouKnowFacts": ["Shuffling feet in shallow water warns stingrays to swim away.", "Babies hatch inside the mother before birth.", "Their skeleton is made of cartilage, not bone."],
     "livesInFacts": ["Atlantic and Caribbean — sandy bays and coral reefs", "Warm shallow water is perfect for hiding.", "Tide pools and lagoons are common hangouts."],
     "dietFacts": ["Crabs, worms, and shellfish on the seafloor", "Strong jaws crush shells from below.", "Smell and touch find food in murky sand."],
     "sizeFacts": ["Wings wider than a card table", "Diamond-shaped body is flat for gliding.", "Tail spine can be longer than a pencil."]},
    {"id": "great-hammerhead", "name": "Great Hammerhead", "emoji": "🦈", "type": "Fish", "habitat": "Ocean",
     "livesIn": "Warm oceans worldwide — coasts and reefs", "diet": "Stingrays, fish, squid, and crustaceans",
     "size": "Longer than a small car", "funFact": "Hammerheads spread sensors along their wide head to find prey!",
     "extraFact": "They sometimes swim on their side to reduce drag.",
     "funFacts": ["Hammerheads spread sensors along their wide head to find prey!", "Eyes at the ends of the 'hammer' see a huge area.", "Schools of dozens gather in some regions."],
     "didYouKnowFacts": ["They pin stingrays to the seafloor with their head.", "Great hammerheads are the largest hammerhead species.", "Pups are born live, not from eggs."],
     "livesInFacts": ["Warm oceans worldwide — coasts and reefs", "They migrate long distances along coastlines.", "Night hunting brings them into shallower water."],
     "dietFacts": ["Stingrays, fish, squid, and crustaceans", "Serrated teeth slice through tough ray bodies.", "They also eat groupers and octopus."],
     "sizeFacts": ["Longer than a small car", "Head width can be a third of their body length.", "Tall dorsal fin is sickle-shaped."]},
    {"id": "goblin-shark", "name": "Goblin Shark", "emoji": "🦈", "type": "Fish", "habitat": "Ocean",
     "livesIn": "Deep oceans — rarely seen near the surface", "diet": "Fish, squid, and deep-sea crustaceans",
     "size": "About as long as a small car", "funFact": "A goblin shark shoots its jaw forward like a spring trap!",
     "extraFact": "Pink skin comes from blood vessels near the surface.",
     "funFacts": ["A goblin shark shoots its jaw forward like a spring trap!", "Long snout is covered with sensors for electric fields.", "Flabby body suits slow life in the deep."],
     "didYouKnowFacts": ["They are living fossils little changed for millions of years.", "Knife-like teeth snag slippery squid.", "Most sightings are from fishing nets, not divers."],
     "livesInFacts": ["Deep oceans — rarely seen near the surface", "Continental slopes are their main zone.", "Cold dark water keeps them hidden."],
     "dietFacts": ["Fish, squid, and deep-sea crustaceans", "Slingshot jaws grab prey before it escapes.", "They ambush more than chase."],
     "sizeFacts": ["About as long as a small car", "Snout can stick out farther than a football.", "Soft pink skin looks unlike other sharks."]},
    {"id": "basking-shark", "name": "Basking Shark", "emoji": "🦈", "type": "Fish", "habitat": "Ocean",
     "livesIn": "Cool oceans — surfaces in coastal bays in summer", "diet": "Tiny plankton filtered from the water",
     "size": "Longer than a school bus — second-largest fish", "funFact": "Basking sharks swim with their huge mouth wide open to filter plankton!",
     "extraFact": "Their liver can be a quarter of their body weight.",
     "funFacts": ["Basking sharks swim with their huge mouth wide open to filter plankton!", "Gill rakers trap food like a giant sieve.", "They look scary but eat creatures smaller than ants."],
     "didYouKnowFacts": ["They sometimes breach and leap completely out of the water.", "Hundreds may gather where plankton blooms.", "Their fins were once hunted for soup."],
     "livesInFacts": ["Cool oceans — surfaces in coastal bays in summer", "Sun-warmed surface layers hold plankton swarms.", "They cross oceans between feeding seasons."],
     "dietFacts": ["Tiny plankton filtered from the water", "Thousands of gallons pass through the mouth each hour.", "They close their mouth to swallow after filtering."],
     "sizeFacts": ["Longer than a school bus — second-largest fish", "Gaping mouth can be three feet wide.", "Rough gray skin has a sandpaper feel."]},
    {"id": "sea-lamprey", "name": "Sea Lamprey", "emoji": "🐟", "type": "Fish", "habitat": "Ocean",
     "livesIn": "Atlantic Ocean and rivers — migrates to spawn in streams", "diet": "Blood and fluids of other fish as adults; no food after spawning",
     "size": "About as long as your arm", "funFact": "Lampreys use a round sucker mouth ringed with sharp teeth!",
     "extraFact": "They are ancient fish older than dinosaurs.",
     "funFacts": ["Lampreys use a round sucker mouth ringed with sharp teeth!", "They attach to fish and rasp through scales.", "Larval lampreys filter-feed in mud for years."],
     "didYouKnowFacts": ["Invasive lampreys once hurt Great Lakes fish populations.", "They die after spawning in rivers like salmon.", "No jaws — just a sucking disc mouth."],
     "livesInFacts": ["Atlantic Ocean and rivers — migrates to spawn in streams", "Rocky river beds hold their nests.", "Parasitic adults roam the open sea."],
     "dietFacts": ["Blood and fluids of other fish as adults; no food after spawning", "Saliva keeps wounds from clotting on hosts.", "Spawning adults use stored fat only."],
     "sizeFacts": ["About as long as your arm", "Eel-like body has no paired fins.", "Seven gill holes show on each side behind the head."]},
    {"id": "hagfish", "name": "Hagfish", "emoji": "🐟", "type": "Fish", "habitat": "Ocean",
     "livesIn": "Deep muddy seafloors worldwide", "diet": "Dead or dying fish and worms — scavengers",
     "size": "About as long as a scarf", "funFact": "Hagfish ooze thick slime that clogs predators' mouths!",
     "extraFact": "They tie themselves in knots to scrape off their own slime.",
     "funFacts": ["Hagfish ooze thick slime that clogs predators' mouths!", "They burrow into carcasses tail-first.", "Tooth-like plates rasp flesh, not true teeth."],
     "didYouKnowFacts": ["One hagfish can fill a bucket with slime in minutes.", "They have four hearts and can survive low oxygen.", "Leather goods sometimes use hagfish skin."],
     "livesInFacts": ["Deep muddy seafloors worldwide", "Soft sediment lets them hide quickly.", "Whale falls are feasts for hagfish crowds."],
     "dietFacts": ["Dead or dying fish and worms — scavengers", "They enter through gills or wounds of large fish.", "Knot-twisting helps them tear off meat chunks."],
     "sizeFacts": ["About as long as a scarf", "Eel-shaped body is soft and jawless.", "Whiskery barbels sense food in the dark."]},
    {"id": "coelacanth", "name": "Coelacanth", "emoji": "🐟", "type": "Fish", "habitat": "Ocean",
     "livesIn": "Deep rocky caves off eastern Africa and Indonesia", "diet": "Fish, squid, and deep-sea prey",
     "size": "About as long as a tall person", "funFact": "Coelacanths were thought extinct until one was caught in 1938!",
     "extraFact": "Lobe-fins move like four legs inside the body.",
     "funFacts": ["Coelacanths were thought extinct until one was caught in 1938!", "They drift in caves by day and hunt at night.", "Baby fish grow inside the mother for years."],
     "didYouKnowFacts": ["Their blue scales shine with special reflective cells.", "They are closer to lungfish ancestors than to most fish.", "Slow metabolism means they live many decades."],
     "livesInFacts": ["Deep rocky caves off eastern Africa and Indonesia", "Caves near volcanic islands are strongholds.", "Cold deep water below 300 feet is home."],
     "dietFacts": ["Fish, squid, and deep-sea prey", "They suck prey with a quick mouth gulp.", "Hunting happens after drifting from caves."],
     "sizeFacts": ["About as long as a tall person", "Fat lobed fins look almost like limbs.", "Rough scales feel like sandpaper."]},
    {"id": "giant-oarfish", "name": "Giant Oarfish", "emoji": "🐟", "type": "Fish", "habitat": "Ocean",
     "livesIn": "Deep open ocean — rarely washes onto beaches", "diet": "Tiny krill, shrimp, and squid",
     "size": "Longer than a school bus — world's longest bony fish", "funFact": "Giant oarfish swim upright with a red crest like a sea ribbon!",
     "extraFact": "Beach strandings may have inspired sea serpent legends.",
     "funFacts": ["Giant oarfish swim upright with a red crest like a sea ribbon!", "Silver body gleams like a ribbon in the deep.", "They lack a full tail fin — tail tapers to a point."],
     "didYouKnowFacts": ["Most photos come from sick or dying fish near shore.", "They may signal earthquakes in old folk tales.", "Very little is known about their daily life."],
     "livesInFacts": ["Deep open ocean — rarely washes onto beaches", "Mesopelagic twilight zone is their main depth.", "Currents may push them up when they are weak."],
     "dietFacts": ["Tiny krill, shrimp, and squid", "Small mouth suits filter feeding.", "They likely open wide to trap drifting plankton."],
     "sizeFacts": ["Longer than a school bus — world's longest bony fish", "Red dorsal fin runs the whole back.", "Paper-thin body is almost all length."]},
    {"id": "barreleye", "name": "Barreleye", "emoji": "🐟", "type": "Fish", "habitat": "Ocean",
     "livesIn": "Deep Pacific Ocean — dark midwater zone", "diet": "Tiny jellyfish and drifting prey",
     "size": "About as long as a cucumber", "funFact": "A barreleye has a transparent dome head and green tubular eyes!",
     "extraFact": "Eyes point up to spot prey silhouettes above.",
     "funFacts": ["A barreleye has a transparent dome head and green tubular eyes!", "Eyes can rotate forward to watch food while eating.", "They hold still and steal food caught by siphonophores."],
     "didYouKnowFacts": ["Scientists only recently filmed them alive in deep water.", "Green lenses may filter out blue deep-sea light.", "Their mouth is tiny compared to their head."],
     "livesInFacts": ["Deep Pacific Ocean — dark midwater zone", "Almost no sunlight reaches their depth.", "They drift below jellyfish curtains."],
     "dietFacts": ["Tiny jellyfish and drifting prey", "Stolen tentacles are nibbled from traps.", "They eat gelatinous animals hard for others to catch."],
     "sizeFacts": ["About as long as a cucumber", "Fluid-filled dome protects the upward eyes.", "Silver flanks hide them from predators below."]},
    {"id": "fangtooth", "name": "Fangtooth", "emoji": "🐟", "type": "Fish", "habitat": "Ocean",
     "livesIn": "Deep oceans worldwide — migrates up at night", "diet": "Small fish and squid",
     "size": "About as long as your hand", "funFact": "Fangtooth fish have the largest teeth for body size of any ocean fish!",
     "extraFact": "They look fierce but are only a few inches long.",
     "funFacts": ["Fangtooth fish have the largest teeth for body size of any ocean fish!", "Teeth slide into slots in the skull when the mouth closes.", "Huge jaw muscles power a deep-sea snap."],
     "didYouKnowFacts": ["They rise hundreds of feet at night to feed.", "Sensitive lateral line feels vibrations in the dark.", "Young fangtooths look very different from adults."],
     "livesInFacts": ["Deep oceans worldwide — migrates up at night", "Twilight zone migration follows prey.", "Cold water keeps metabolism slow."],
     "dietFacts": ["Small fish and squid", "Anything that fits is grabbed in one bite.", "They are aggressive hunters for their size."],
     "sizeFacts": ["About as long as your hand", "Scaleless dark body is muscular.", "Grooved lines on flanks may sense water movement."]},
    {"id": "red-king-crab", "name": "Red King Crab", "emoji": "🦀", "type": "Crustacean", "habitat": "Ocean",
     "livesIn": "Cold northern Pacific — rocky seafloor", "diet": "Clams, worms, sea stars, and dead animals",
     "size": "Leg span wider than a bicycle wheel", "funFact": "King crabs walk on long spiny legs across the cold seafloor!",
     "extraFact": "Millions migrate in huge herds in some Alaskan bays.",
     "funFacts": ["King crabs walk on long spiny legs across the cold seafloor!", "One claw is often larger for crushing shells.", "They shed their hard shell to grow bigger."],
     "didYouKnowFacts": ["Introduced populations live in the Barents Sea too.", "Females carry thousands of eggs under the abdomen.", "Fishing fleets catch them for seafood worldwide."],
     "livesInFacts": ["Cold northern Pacific — rocky seafloor", "Depth changes with season and age.", "They pile on sandy patches during migrations."],
     "dietFacts": ["Clams, worms, sea stars, and dead animals", "Strong claws open clams and tear prey.", "They scavenge fish left by fishing boats."],
     "sizeFacts": ["Leg span wider than a bicycle wheel", "Carapace alone can be as wide as a dinner plate.", "Spines on shell discourage predators."]},
    {"id": "giant-isopod", "name": "Giant Isopod", "emoji": "🦐", "type": "Crustacean", "habitat": "Ocean",
     "livesIn": "Deep Atlantic and Pacific seafloor", "diet": "Whale carcasses, fish, and slow deep-sea prey",
     "size": "About as long as a house cat", "funFact": "Giant isopods look like huge pill bugs from the deep sea!",
     "extraFact": "They can go years without eating after one big meal.",
     "funFacts": ["Giant isopods look like huge pill bugs from the deep sea!", "Seven pairs of legs walk along muddy bottoms.", "They curl into a ball when threatened."],
     "didYouKnowFacts": ["They are related to roly-polies in your garden.", "Aquariums sometimes display them as deep-sea oddities.", "Compound eyes are huge for spotting rare food."],
     "livesInFacts": ["Deep Atlantic and Pacific seafloor", "Pressure at depth would crush surface animals.", "They gather fast at whale falls."],
     "dietFacts": ["Whale carcasses, fish, and slow deep-sea prey", "Strong jaws slice through tough blubber.", "Scavenging is safer than chasing fast prey."],
     "sizeFacts": ["About as long as a house cat", "Rigid segments form an armored cylinder.", "Pale lavender or brown color is common."]},
    {"id": "purple-sea-urchin", "name": "Purple Sea Urchin", "emoji": "🦔", "type": "Invertebrate", "habitat": "Ocean",
     "livesIn": "Pacific rocky shores — tide pools to deep reefs", "diet": "Algae and kelp",
     "size": "About as wide as a softball", "funFact": "Sea urchins move on hundreds of tiny tube feet!",
     "extraFact": "Their mouth on the bottom is called Aristotle's lantern.",
     "funFacts": ["Sea urchins move on hundreds of tiny tube feet!", "Spines wave to warn fish away.", "They scrape rocks clean of kelp forests when too many gather."],
     "didYouKnowFacts": ["Otters smash urchins on their chest to eat them.", "Purple spines fade to green in some individuals.", "Larval urchins drift in plankton before settling."],
     "livesInFacts": ["Pacific rocky shores — tide pools to deep reefs", "Crevices protect them from crashing waves.", "Kelp forests are their grocery store."],
     "dietFacts": ["Algae and kelp", "Five teeth grind kelp holdfasts.", "Urchin barrens are rocks stripped bare of algae."],
     "sizeFacts": ["About as wide as a softball", "Spines can regrow if broken off.", "Hard shell called a test remains after death."]},
    {"id": "sand-dollar", "name": "Sand Dollar", "emoji": "🪙", "type": "Invertebrate", "habitat": "Ocean",
     "livesIn": "Sandy seafloors — shallow bays and beaches", "diet": "Tiny plankton and organic bits in sand",
     "size": "About as wide as a cookie", "funFact": "Live sand dollars are covered in fuzzy purple spines!",
     "extraFact": "Bleached white shells on beaches are skeletons after the animal dies.",
     "funFacts": ["Live sand dollars are covered in fuzzy purple spines!", "They burrow slightly and stand on edge in sand.", "Tube feet move food grooves toward the mouth."],
     "didYouKnowFacts": ["A five-petal pattern on the shell is from their body design.", "They travel in groups called beds.", "Tiny jaws chew food inside the disk body."],
     "livesInFacts": ["Sandy seafloors — shallow bays and beaches", "Calm water keeps fine sand from burying them.", "Breaking waves sometimes toss them ashore."],
     "dietFacts": ["Tiny plankton and organic bits in sand", "Mucus-coated spines trap particles.", "They eat lying flat or standing upright."],
     "sizeFacts": ["About as wide as a cookie", "Flattened body is made for sand not rock.", "Dead tests show a flower-like pattern of holes."]},
    {"id": "aye-aye", "name": "Aye-Aye", "emoji": "🐒", "type": "Mammal", "habitat": "Jungle",
     "livesIn": "Madagascar — rainforest trees", "diet": "Insect larvae inside wood, fruit, and nuts",
     "size": "About as long as a house cat", "funFact": "The aye-aye taps trees with a bony finger, then gnaws a hole to fish out grubs!",
     "extraFact": "Huge ears swivel like satellite dishes toward sounds.",
     "funFacts": ["The aye-aye taps trees with a bony finger, then gnaws a hole to fish out grubs!", "Bushy tail is longer than its body.", "Big orange eyes glow in night vision."],
     "didYouKnowFacts": ["Some locals once thought aye-ayes brought bad luck.", "They are the world's largest nocturnal primate.", "Rodent-like teeth keep growing for gnawing wood."],
     "livesInFacts": ["Madagascar — rainforest trees", "Only found on this island in the wild.", "Canopy travel avoids ground predators."],
     "dietFacts": ["Insect larvae inside wood, fruit, and nuts", "Thin middle finger scoops larvae after tapping.", "Coconut-like ramy nuts are cracked with teeth."],
     "sizeFacts": ["About as long as a house cat", "Shaggy dark fur blends into shadows.", "Claws help cling while hanging under branches."]},
    {"id": "indri", "name": "Indri", "emoji": "🐒", "type": "Mammal", "habitat": "Jungle",
     "livesIn": "Madagascar — eastern rainforest treetops", "diet": "Leaves, flowers, fruit, and seeds",
     "size": "About as tall as a kindergartener when upright", "funFact": "Indris sing loud howls that carry for miles through the forest!",
     "extraFact": "They are the largest living lemur.",
     "funFacts": ["Indris sing loud howls that carry for miles through the forest!", "They cannot hang by their tail — it is short.", "Powerful legs leap vertically between tree trunks."],
     "didYouKnowFacts": ["Pairs sing duets to mark territory.", "They rarely come down to the ground.", "Habitat loss makes them critically endangered."],
     "livesInFacts": ["Madagascar — eastern rainforest treetops", "Tall trees in wet forests are required.", "Family groups defend a patch of forest."],
     "dietFacts": ["Leaves, flowers, fruit, and seeds", "Toxic leaves are avoided by careful tasting.", "They eat for hours each morning."],
     "sizeFacts": ["About as tall as a kindergartener when upright", "Black and white fur looks like a teddy bear.", "Arms are short compared to other lemurs."]},
    {"id": "coquerels-sifaka", "name": "Coquerel's Sifaka", "emoji": "🐒", "type": "Mammal", "habitat": "Jungle",
     "livesIn": "Madagascar — dry northwestern forests", "diet": "Leaves, flowers, fruit, and bark",
     "size": "About as long as a large cat", "funFact": "Sifakas dance sideways on two legs when crossing open ground!",
     "extraFact": "They are named for their 'shi-fak' alarm call.",
     "funFacts": ["Sifakas dance sideways on two legs when crossing open ground!", "They leap up to 30 feet between tree trunks.", "White fur and brown arms stand out in trees."],
     "didYouKnowFacts": ["They sunbathe belly-up on branches in the morning.", "Babies cling to mom's belly, then ride on her back.", "Only a few thousand remain in the wild."],
     "livesInFacts": ["Madagascar — dry northwestern forests", "Spiny trees and deciduous woods are home.", "They avoid crossing wide open spaces except by dancing."],
     "dietFacts": ["Leaves, flowers, fruit, and bark", "Seasonal diet shifts with what trees offer.", "Some plants are toxic to other animals but not sifakas."],
     "sizeFacts": ["About as long as a large cat", "Long hind legs power tree leaps.", "Thick fur handles cool dry-season nights."]},
    {"id": "galapagos-tortoise", "name": "Galapagos Tortoise", "emoji": "🐢", "type": "Reptile", "habitat": "Grassland",
     "livesIn": "Galapagos Islands — volcanic highlands and dry lowlands", "diet": "Grass, cactus pads, leaves, and fruit",
     "size": "Heavier than ten kids combined — shell longer than a table", "funFact": "Galapagos tortoises can live more than 100 years!",
     "extraFact": "Different islands have tortoises with different shell shapes.",
     "funFacts": ["Galapagos tortoises can live more than 100 years!", "They store water and fat inside their shell for dry seasons.", "Slow walks cover miles between food and mud wallows."],
     "didYouKnowFacts": ["Sailors once took thousands aboard ships for food.", "Charles Darwin noticed island differences on his voyage.", "Breeding centers help endangered types recover."],
     "livesInFacts": ["Galapagos Islands — volcanic highlands and dry lowlands", "Misty highlands grow lush grass in cool season.", "They sleep in mud or water to cool off."],
     "dietFacts": ["Grass, cactus pads, leaves, and fruit", "Prickly pear cactus is a favorite on dry islands.", "They can go months with little food or water."],
     "sizeFacts": ["Heavier than ten kids combined — shell longer than a table", "Domed shells suit highland grazers.", "Saddleback shells let necks reach high cactus on dry islands."]},
    {"id": "tuatara", "name": "Tuatara", "emoji": "🦎", "type": "Reptile", "habitat": "Ocean",
     "livesIn": "New Zealand islands — coastal burrows and forest", "diet": "Insects, spiders, worms, and sometimes seabird eggs",
     "size": "About as long as a football", "funFact": "Tuatara are living fossils — the only survivors of an ancient reptile group!",
     "extraFact": "They have a third 'eye' on top of the head sensitive to light.",
     "funFacts": ["Tuatara are living fossils — the only survivors of an ancient reptile group!", "They prefer cool weather and are active at low temperatures.", "Spiny crest runs down the back in males."],
     "didYouKnowFacts": ["They can live over 100 years.", "Eggs take more than a year to hatch.", "Rats on islands are a major threat to eggs."],
     "livesInFacts": ["New Zealand islands — coastal burrows and forest", "Predator-free islands are safest refuges.", "They share burrows with seabirds sometimes."],
     "dietFacts": ["Insects, spiders, worms, and sometimes seabird eggs", "Jaws slice prey with sharp teeth.", "They hunt at night near burrow entrances."],
     "sizeFacts": ["About as long as a football", "Olive-green skin has knobby scales.", "They are not lizards — they are a separate lineage."]},
    {"id": "common-basilisk", "name": "Common Basilisk", "emoji": "🦎", "type": "Reptile", "habitat": "Jungle",
     "livesIn": "Central America — rainforest streams and rivers", "diet": "Insects, small fish, flowers, and fruit",
     "size": "About as long as your forearm including tail", "funFact": "Basilisk lizards run on water on their hind feet — earning the name Jesus lizard!",
     "extraFact": "Long toes and fringes slap the surface before they sink.",
     "funFacts": ["Basilisk lizards run on water on their hind feet — earning the name Jesus lizard!", "A crest on the head and back marks males.", "They dive underwater to escape predators."],
     "didYouKnowFacts": ["Young basilisks can run farther on water than heavy adults.", "They sleep in bushes overhanging water.", "Tail whips help balance during sprints."],
     "livesInFacts": ["Central America — rainforest streams and rivers", "Overhanging branches are escape routes.", "Warm humid air keeps them active all day."],
     "dietFacts": ["Insects, small fish, flowers, and fruit", "Fast jaws snap up crickets and butterflies.", "They hunt at the water edge and in trees."],
     "sizeFacts": ["About as long as your forearm including tail", "Green and brown patterns hide them in leaves.", "Back legs are much longer than front legs for running."]},
    {"id": "blue-tongue-skink", "name": "Blue-Tongue Skink", "emoji": "🦎", "type": "Reptile", "habitat": "Forest",
     "livesIn": "Australia — woodlands, gardens, and scrub", "diet": "Snails, insects, berries, and flowers",
     "size": "About as long as a skateboard", "funFact": "When scared, blue-tongue skinks stick out a bright blue tongue!",
     "extraFact": "They give live birth instead of laying eggs.",
     "funFacts": ["When scared, blue-tongue skinks stick out a bright blue tongue!", "Short legs and a fat body look almost like a snake with a head.", "They hiss and flatten their body to look bigger."],
     "didYouKnowFacts": ["They are gentle enough to be popular pets.", "Powerful jaws crush snail shells.", "They sunbathe in the morning to warm up."],
     "livesInFacts": ["Australia — woodlands, gardens, and scrub", "Leaf litter hides them from hawks.", "Suburban yards often have resident skinks."],
     "dietFacts": ["Snails, insects, berries, and flowers", "Tongue color may warn predators they taste bad.", "They forage slowly with a flicking tongue."],
     "sizeFacts": ["About as long as a skateboard", "Smooth overlapping scales shine.", "Brown bands cross a pale belly."]},
    {"id": "black-mamba", "name": "Black Mamba", "emoji": "🐍", "type": "Reptile", "habitat": "Grassland",
     "livesIn": "Sub-Saharan Africa — savannas and rocky hills", "diet": "Small mammals, birds, and nestlings",
     "size": "Longer than a car — one of the longest snakes in Africa", "funFact": "Black mambas are fast runners and actually gray-brown — the name refers to the black mouth inside!",
     "extraFact": "They raise the front of the body high when threatened.",
     "funFacts": ["Black mambas are fast runners and actually gray-brown — the name refers to the black mouth inside!", "They are shy and usually flee from people.", "Smooth scales give a satin look in sunlight."],
     "didYouKnowFacts": ["Their venom is very potent but bites to humans are rare.", "They hunt by day using keen eyesight.", "Tree hollows and termite mounds are nest sites."],
     "livesInFacts": ["Sub-Saharan Africa — savannas and rocky hills", "Open ground lets them sprint at high speed.", "They also climb trees for birds and eggs."],
     "dietFacts": ["Small mammals, birds, and nestlings", "Quick strikes inject venom into prey.", "They swallow food whole after it stops moving."],
     "sizeFacts": ["Longer than a car — one of the longest snakes in Africa", "Inside of mouth is inky black when opened wide.", "Slim body is built for speed, not crushing."]},
    {"id": "gray-tree-frog", "name": "Gray Tree Frog", "emoji": "🐸", "type": "Amphibian", "habitat": "Forest",
     "livesIn": "Eastern North America — woods near ponds", "diet": "Insects, spiders, and snails",
     "size": "About as long as a golf ball", "funFact": "Gray tree frogs can change color from gray to bright green!",
     "extraFact": "Sticky toe pads let them climb windows and trees.",
     "funFacts": ["Gray tree frogs can change color from gray to bright green!", "They hide in tree holes by day.", "Loud trilling calls fill summer nights near ponds."],
     "didYouKnowFacts": ["They freeze partly solid in winter and thaw in spring.", "Skin secretions may irritate eyes if touched.", "Eggs float in jelly clumps on pond surfaces."],
     "livesInFacts": ["Eastern North America — woods near ponds", "Breeding pools can be temporary puddles.", "They range far from water after the breeding season."],
     "dietFacts": ["Insects, spiders, and snails", "Tongue flicks catch moths at porch lights.", "They hunt at night when predators are fewer."],
     "sizeFacts": ["About as long as a golf ball", "Yellow-orange inner thighs flash when they leap.", "Warty skin camouflages them on bark."]},
    {"id": "blue-poison-dart-frog", "name": "Blue Poison Dart Frog", "emoji": "🐸", "type": "Amphibian", "habitat": "Jungle",
     "livesIn": "Suriname rainforest — forest floor near streams", "diet": "Ants, termites, and tiny insects",
     "size": "Smaller than a paperclip — about two inches long", "funFact": "Bright blue skin warns predators that this frog is poisonous!",
     "extraFact": "Captive frogs lose toxicity without the right wild diet.",
     "funFacts": ["Bright blue skin warns predators that this frog is poisonous!", "They are active by day unlike many frogs.", "Males carry tadpoles to water in bromeliad cups."],
     "didYouKnowFacts": ["Indigenous people once used frog toxins on blow darts.", "Each frog has a unique spot pattern.", "They are endangered from pet trade collection."],
     "livesInFacts": ["Suriname rainforest — forest floor near streams", "Humid leaf litter keeps skin moist.", "Bromeliad plants hold tiny pools for tadpoles."],
     "dietFacts": ["Ants, termites, and tiny insects", "Alkaloids from ants may build up poison in skin.", "A long sticky tongue catches fast prey."],
     "sizeFacts": ["Smaller than a paperclip — about two inches long", "Smooth skin shines sapphire blue.", "Legs are strong for hopping through moss."]},
    {"id": "lionfish", "name": "Lionfish", "emoji": "🐟", "type": "Fish", "habitat": "Ocean",
     "livesIn": "Indo-Pacific reefs — also invasive in Atlantic", "diet": "Small fish and shrimp",
     "size": "About as long as a football", "funFact": "Lionfish fan out venomous spines like a underwater lion's mane!",
     "extraFact": "They corner prey with their wide pectoral fins.",
     "funFacts": ["Lionfish fan out venomous spines like a underwater lion's mane!", "Striped red and white pattern warns predators.", "They swallow prey whole in one gulp."],
     "didYouKnowFacts": ["Atlantic invasions hurt native reef fish.", "One female can release millions of eggs a year.", "Hunters use spears to control populations in some places."],
     "livesInFacts": ["Indo-Pacific reefs — also invasive in Atlantic", "Coral ledges are daytime hiding spots.", "They hunt more at dawn and dusk."],
     "dietFacts": ["Small fish and shrimp", "Fast strikes vacuum prey with suction.", "They sometimes cooperate to herd fish."],
     "sizeFacts": ["About as long as a football", "Long dorsal spines deliver painful stings.", "Feathery fins slow their swim but aid ambush."]},
    {"id": "blue-marlin", "name": "Blue Marlin", "emoji": "🐟", "type": "Fish", "habitat": "Ocean",
     "livesIn": "Tropical and temperate open oceans worldwide", "diet": "Tuna, mackerel, squid, and flying fish",
     "size": "Longer than a car — bill alone can exceed a person's height", "funFact": "Blue marlin spears schools of fish with their long spear-like bill!",
     "extraFact": "They heat their eyes and brain for sharper deep hunting.",
     "funFacts": ["Blue marlin spears schools of fish with their long spear-like bill!", "They leap high when hooked by fishing lines.", "Dark blue backs fade to silver bellies."],
     "didYouKnowFacts": ["Females grow much larger than males.", "They migrate thousands of miles following warm currents.", "Sport fishers often tag and release them."],
     "livesInFacts": ["Tropical and temperate open oceans worldwide", "They rarely come near shore except young fish.", "Gulf Stream edges concentrate prey."],
     "dietFacts": ["Tuna, mackerel, squid, and flying fish", "Slashing bill stuns prey before swallowing.", "They dive hundreds of feet for squid."],
     "sizeFacts": ["Longer than a car — bill alone can exceed a person's height", "Rigid pectoral fins do not fold flat.", "Powerful tail drives bursts over 50 mph."]},
    {"id": "atlantic-sailfish", "name": "Atlantic Sailfish", "emoji": "🐟", "type": "Fish", "habitat": "Ocean",
     "livesIn": "Warm Atlantic Ocean — surface waters near coasts", "diet": "Sardines, anchovies, and squid",
     "size": "Bill to tail longer than a tall person", "funFact": "Sailfish raise a giant dorsal fin like a sail to look bigger and herd prey!",
     "extraFact": "They are among the fastest fish in the sea.",
     "funFacts": ["Sailfish raise a giant dorsal fin like a sail to look bigger and herd prey!", "Colors flash blue and bronze when excited.", "They work in groups to trap fish schools."],
     "didYouKnowFacts": ["Their bill is rounder than a marlin's.", "They can swim 60 mph in short bursts.", "Sport anglers prize them for acrobatic jumps."],
     "livesInFacts": ["Warm Atlantic Ocean — surface waters near coasts", "Gulf and Caribbean waters are hotspots.", "They follow baitfish near the surface."],
     "dietFacts": ["Sardines, anchovies, and squid", "Slashing bills injure fish in tight schools.", "They eat stunned fish as they sink."],
     "sizeFacts": ["Bill to tail longer than a tall person", "Tall sail fin can be taller than their body depth.", "Slender body is built for speed not bulk."]},
    {"id": "anchovy", "name": "Anchovy", "emoji": "🐟", "type": "Fish", "habitat": "Ocean",
     "livesIn": "Temperate oceans worldwide — huge surface schools", "diet": "Tiny plankton and larval fish",
     "size": "About as long as your finger", "funFact": "Anchovies swim in giant shimmering schools that confuse predators!",
     "extraFact": "They have a silver stripe along the side.",
     "funFacts": ["Anchovies swim in giant shimmering schools that confuse predators!", "They filter-feed with gill rakers like baleen whales in miniature.", "Millions move as one swirling cloud."],
     "didYouKnowFacts": ["People salt and preserve anchovies for pizza flavor.", "Whales, seabirds, and tuna all depend on anchovy schools.", "Overfishing can collapse entire food webs."],
     "livesInFacts": ["Temperate oceans worldwide — huge surface schools", "Upwelling coasts bring cold nutrient-rich water.", "They stay near the surface at night more than day."],
     "dietFacts": ["Tiny plankton and larval fish", "Gaping mouth catches drifting plankton.", "They must eat often to fuel fast swimming."],
     "sizeFacts": ["About as long as your finger", "Small size lets huge schools form.", "Forked tail powers quick escapes."]},
    {"id": "sardine", "name": "Sardine", "emoji": "🐟", "type": "Fish", "habitat": "Ocean",
     "livesIn": "Coastal oceans worldwide — especially upwelling regions", "diet": "Plankton and tiny crustaceans",
     "size": "About as long as your hand", "funFact": "Sardine runs pack so many fish that the sea seems to boil!",
     "extraFact": "They are named after the island of Sardinia.",
     "funFacts": ["Sardine runs pack so many fish that the sea seems to boil!", "Predators attack from above and below at once.", "Each fish has a spot behind the gill cover."],
     "didYouKnowFacts": ["Dolphins blow bubble rings to herd sardines.", "Canned sardines include calcium-rich edible bones.", "Southern Africa's sardine run is famous worldwide."],
     "livesInFacts": ["Coastal oceans worldwide — especially upwelling regions", "Cool water holds more oxygen and food.", "They migrate vertically each day following plankton."],
     "dietFacts": ["Plankton and tiny crustaceans", "Filter feeding happens with mouth wide open.", "Seasonal blooms decide how fat they grow."],
     "sizeFacts": ["About as long as your hand", "Silvery scales flash when the school turns.", "Slightly larger than anchovies on average."]},
    {"id": "betta", "name": "Betta", "emoji": "🐟", "type": "Fish", "habitat": "Jungle",
     "livesIn": "Southeast Asia — shallow rice paddies and slow streams", "diet": "Insects, larvae, and small crustaceans",
     "size": "About as long as your thumb", "funFact": "Male bettas flare gills and fins to challenge rivals!",
     "extraFact": "They breathe air with a special labyrinth organ.",
     "funFacts": ["Male bettas flare gills and fins to chase rivals!", "Bubble nests hold eggs at the water surface.", "Wild types are duller brown than pet shop colors."],
     "didYouKnowFacts": ["They can survive in low-oxygen puddles briefly.", "Females are less aggressive and less flashy.", "Over 70 color forms exist in aquarium trade."],
     "livesInFacts": ["Southeast Asia — shallow rice paddies and slow streams", "Warm shallow water suits air breathing.", "Plants and roots hide bubble nests."],
     "dietFacts": ["Insects, larvae, and small crustaceans", "Upward mouth catches prey at the surface.", "Males guard eggs until they hatch."],
     "sizeFacts": ["About as long as your thumb", "Long flowing fins are bred in pet fish.", "Bright colors warn other males in territory fights."]},
    {"id": "guppy", "name": "Guppy", "emoji": "🐟", "type": "Fish", "habitat": "Jungle",
     "livesIn": "South America and worldwide — warm streams and ponds", "diet": "Algae, small insects, and detritus",
     "size": "About as long as a paperclip", "funFact": "Male guppies wear bright spots to impress females!",
     "extraFact": "Females give birth to live tiny fish, not eggs.",
     "funFacts": ["Male guppies wear bright spots to impress females!", "They are popular aquarium fish for beginners.", "Predators learn to target the flashiest males."],
     "didYouKnowFacts": ["Guppies eat mosquito larvae and help control pests.", "They were once called millionfish for fast breeding.", "Tail shapes vary from fan to sword in pets."],
     "livesInFacts": ["South America and worldwide — warm streams and ponds", "Introduced guppies live on every continent except Antarctica.", "Shallow sunny water grows algae they graze."],
     "dietFacts": ["Algae, small insects, and detritus", "Mouth points up to skim surface food.", "Newborns hide in plants right away."],
     "sizeFacts": ["About as long as a paperclip", "Females are larger and plainer than males.", "Transparent fry grow color patterns later."]},
]
