BATCH3 = [
    {"id": "mountain-goat", "name": "Mountain Goat", "emoji": "🐐", "type": "Mammal", "habitat": "Arctic",
     "livesIn": "North American alpine peaks — rocky cliffs above the trees", "diet": "Grasses, lichens, and alpine plants",
     "size": "About as heavy as a large dog", "funFact": "Mountain goats climb near-vertical cliffs with rubbery hooves!",
     "extraFact": "They are more closely related to antelopes than to farm goats.",
     "funFacts": ["Mountain goats climb near-vertical cliffs with rubbery hooves!", "Thick white coats shed in summer.", "Both males and females have sharp curved horns."],
     "didYouKnowFacts": ["Kids can climb within hours of birth.", "Salt licks draw them to human trails sometimes.", "A fall from cliffs is a leading cause of death."],
     "livesInFacts": ["North American alpine peaks — rocky cliffs above the trees", "Steep terrain keeps away most predators.", "They migrate down slightly in harsh winter storms."],
     "dietFacts": ["Grasses, lichens, and alpine plants", "They paw snow to reach plants underneath.", "Mineral licks provide needed salt."],
     "sizeFacts": ["About as heavy as a large dog", "Beards and stocky shoulders suit cold wind.", "Hoof edges grip rock like climbing shoes."]},
    {"id": "alpine-ibex", "name": "Alpine Ibex", "emoji": "🐐", "type": "Mammal", "habitat": "Arctic",
     "livesIn": "European Alps — steep rocky mountains", "diet": "Grass, herbs, leaves, and lichens",
     "size": "About as heavy as a big dog", "funFact": "Male ibex clash horns so hard you can hear the crack across the valley!",
     "extraFact": "Their horns curve backward in huge arcs.",
     "funFacts": ["Male ibex clash horns so hard you can hear the crack across the valley!", "They stand on tiny ledges to lick salt from rocks.", "Kids leap and play on slopes that look impossible."],
     "didYouKnowFacts": ["Hunting once wiped them out in Switzerland until reintroduction.", "Horns can weigh 30 pounds on old males.", "They descend to forests in winter for food."],
     "livesInFacts": ["European Alps — steep rocky mountains", "Cliff faces above the snow line are daytime hangouts.", "Caves and overhangs shelter them from storms."],
     "dietFacts": ["Grass, herbs, leaves, and lichens", "Morning and evening grazing fits their schedule.", "Hard hooves dig through snow for buried plants."],
     "sizeFacts": ["About as heavy as a big dog", "Males have a dark beard and heavier horns.", "Compact body and low center help on cliffs."]},
    {"id": "springbok", "name": "Springbok", "emoji": "🦌", "type": "Mammal", "habitat": "Grassland",
     "livesIn": "Southern Africa — dry savannas and deserts", "diet": "Grass, leaves, and succulents",
     "size": "About as tall as a desk", "funFact": "Springboks pronk — bouncing straight up with stiff legs to show off!",
     "extraFact": "A dark stripe runs along each side when they are excited.",
     "funFacts": ["Springboks pronk — bouncing straight up with stiff legs to show off!", "They once migrated in herds millions strong.", "White face and belly flash when they flee."],
     "didYouKnowFacts": ["Springbok is the national animal of South Africa.", "They can survive with little drinking water.", "Cheetahs and wild dogs chase them on open plains."],
     "livesInFacts": ["Southern Africa — dry savannas and deserts", "Open grass lets them spot predators early.", "They gather at waterholes in dry seasons."],
     "dietFacts": ["Grass, leaves, and succulents", "Moist plants provide most of their water.", "They graze at dawn and dusk to avoid heat."],
     "sizeFacts": ["About as tall as a desk", "Lyre-shaped horns curve on males.", "Slender legs are built for speed and leaps."]},
    {"id": "greater-kudu", "name": "Greater Kudu", "emoji": "🦌", "type": "Mammal", "habitat": "Forest",
     "livesIn": "Eastern and southern Africa — bush and woodland", "diet": "Leaves, shoots, fruit, and vines",
     "size": "Shoulder height near a tall kid — horns spiral high above", "funFact": "Male kudu horns twist in huge corkscrews up to six feet around!",
     "extraFact": "Vertical white stripes help them vanish in bush shadows.",
     "funFacts": ["Male kudu horns twist in huge corkscrews up to six feet around!", "They freeze instead of running when they sense danger.", "Big ears swivel toward the faintest sound."],
     "didYouKnowFacts": ["Lions are their main predator.", "Males usually live alone; females form family groups.", "Horns are not shed — they grow for life."],
     "livesInFacts": ["Eastern and southern Africa — bush and woodland", "Thickets provide cover from open savanna hunters.", "They visit water every few days in dry heat."],
     "dietFacts": ["Leaves, shoots, fruit, and vines", "They stand on hind legs to reach high branches.", "Browsing fits thick forest edges better than pure grass."],
     "sizeFacts": ["Shoulder height near a tall kid — horns spiral high above", "Gray-brown coat matches tree trunks.", "A mane runs along the neck and back."]},
    {"id": "giant-centipede", "name": "Giant Centipede", "emoji": "🐛", "type": "Invertebrate", "habitat": "Jungle",
     "livesIn": "Tropics worldwide — leaf litter, logs, and caves", "diet": "Insects, spiders, mice, and small reptiles",
     "size": "About as long as a dinner plate in largest species", "funFact": "Centipedes have one pair of legs per body segment — and the first pair are venom fangs!",
     "extraFact": "They move fast in an S-shaped ripple.",
     "funFacts": ["Centipedes have one pair of legs per body segment — and the first pair are venom fangs!", "They are hunters, not plant-eating millipedes.", "Antennae probe ahead in the dark."],
     "didYouKnowFacts": ["Amazon giant centipedes can catch bats on cave ceilings.", "They breathe through holes along their sides.", "Mothers guard eggs until they hatch."],
     "livesInFacts": ["Tropics worldwide — leaf litter, logs, and caves", "Moist ground keeps their body from drying out.", "They hide under rocks by day."],
     "dietFacts": ["Insects, spiders, mice, and small reptiles", "Venom paralyzes prey quickly.", "They chew with strong jaw-like mouthparts."],
     "sizeFacts": ["About as long as a dinner plate in largest species", "Orange or red bands warn predators.", "Flattened body slips into narrow cracks."]},
    {"id": "cone-snail", "name": "Cone Snail", "emoji": "🐚", "type": "Mollusk", "habitat": "Ocean",
     "livesIn": "Tropical reefs and sandy shallows worldwide", "diet": "Fish, worms, and other snails",
     "size": "Shell about as long as your thumb to hand", "funFact": "Cone snails harpoon prey with a venomous tooth on a stretchy tube!",
     "extraFact": "Pretty patterned shells attract collectors — but live snails can sting.",
     "funFacts": ["Cone snails harpoon prey with a venomous tooth on a stretchy tube!", "Some hunt fish faster than the eye can follow.", "They extend a tube called a proboscis to strike."],
     "didYouKnowFacts": ["Their venom inspired pain-relief medicine research.", "Each species has its own shell pattern.", "They move slowly but strike in milliseconds."],
     "livesInFacts": ["Tropical reefs and sandy shallows worldwide", "They bury in sand with a siphon sticking out.", "Coral rubble hides the most colorful species."],
     "dietFacts": ["Fish, worms, and other snails", "Fish-eating cones are the most dangerous to humans.", "Worm-eaters use a different venom mix."],
     "sizeFacts": ["Shell about as long as your thumb to hand", "Spiral shells are geometrically neat.", "Soft body can stretch far outside the shell."]},
    {"id": "chinchilla", "name": "Chinchilla", "emoji": "🐭", "type": "Mammal", "habitat": "Desert",
     "livesIn": "Andes mountains — rocky dry slopes of Chile and Peru", "diet": "Grass, leaves, bark, and seeds",
     "size": "About as long as a squirrel", "funFact": "Chinchilla fur is so dense that fleas suffocate — up to 80 hairs from one follicle!",
     "extraFact": "They bathe in volcanic dust instead of water.",
     "funFacts": ["Chinchilla fur is so dense that fleas suffocate — up to 80 hairs from one follicle!", "They jump six feet straight up.", "Big ears release heat in cool mountain air."],
     "didYouKnowFacts": ["Wild chinchillas are endangered from fur hunting.", "They eat by holding food in front paws.", "Dust baths keep their fur fluffy and dry."],
     "livesInFacts": ["Andes mountains — rocky dry slopes of Chile and Peru", "Crevices in cliffs are daytime shelters.", "Cold dry air suits their thick coat."],
     "dietFacts": ["Grass, leaves, bark, and seeds", "They chew at dawn and dusk.", "Digestion needs high-fiber plants."],
     "sizeFacts": ["About as long as a squirrel", "Bushy tail balances during leaps.", "Soft gray fur was once called the softest in the world."]},
    {"id": "long-nosed-bandicoot", "name": "Long-Nosed Bandicoot", "emoji": "🐭", "type": "Mammal", "habitat": "Forest",
     "livesIn": "Eastern Australia — gardens, forests, and parks", "diet": "Insects, worms, roots, and berries",
     "size": "About as long as a rabbit", "funFact": "Bandicoots dig cone-shaped holes with their long snout to find grubs!",
     "extraFact": "They have a backward-facing pouch so dirt does not fill it while digging.",
     "funFacts": ["Bandicoots dig cone-shaped holes with their long snout to find grubs!", "They hop quickly when startled.", "Striped hindquarters are easy to spot."],
     "didYouKnowFacts": ["They are marsupials related to bilbies, not rats.", "A litter can have up to five tiny babies.", "They are active mostly at night."],
     "livesInFacts": ["Eastern Australia — gardens, forests, and parks", "Suburban lawns are full of worms to eat.", "Leaf litter hides daytime nests."],
     "dietFacts": ["Insects, worms, roots, and berries", "Sensitive nose smells underground prey.", "They eat in short bursts then rest."],
     "sizeFacts": ["About as long as a rabbit", "Pointed snout is longer than a rabbit's.", "Coarse fur is gray-brown with speckles."]},
    {"id": "southern-cuscus", "name": "Southern Cuscus", "emoji": "🐨", "type": "Mammal", "habitat": "Jungle",
     "livesIn": "New Guinea and northern Australia — rainforest canopy", "diet": "Leaves, fruit, and flowers",
     "size": "About as long as a house cat", "funFact": "Cuscuses have a grasping tail and move slowly like sloths in the trees!",
     "extraFact": "Thick fur can be spotted or plain depending on the population.",
     "funFacts": ["Cuscuses have a grasping tail and move slowly like sloths in the trees!", "They are marsupials, not monkeys.", "Big eyes help them feed at night."],
     "didYouKnowFacts": ["Males have a scent gland that stains fur yellow on the chest.", "They curl into a ball when sleeping.", "Hunting and logging shrink their forest home."],
     "livesInFacts": ["New Guinea and northern Australia — rainforest canopy", "They rarely come down to the ground.", "Vines connect trees in their slow routes."],
     "dietFacts": ["Leaves, fruit, and flowers", "Low-energy diet matches their slow lifestyle.", "They pick fruit with careful paws."],
     "sizeFacts": ["About as long as a house cat", "Prehensile tail wraps around branches.", "Rounded ears and snout look bear-like."]},
    {"id": "pistol-shrimp", "name": "Pistol Shrimp", "emoji": "🦐", "type": "Crustacean", "habitat": "Ocean",
     "livesIn": "Tropical reefs — burrows in sand and coral", "diet": "Small fish, worms, and scraps",
     "size": "About as long as your finger", "funFact": "Pistol shrimp snap their claw so fast it makes a bubble that stuns prey!",
     "extraFact": "The snap is one of the loudest sounds in the ocean for its size.",
     "funFacts": ["Pistol shrimp snap their claw so fast it makes a bubble that stuns prey!", "One claw is huge; the other is small.", "Some share burrows with goby fish lookouts."],
     "didYouKnowFacts": ["The collapsing bubble briefly reaches hot temperatures.", "Colonies of snapping shrimp create ocean crackle.", "Gobies warn shrimp when predators approach."],
     "livesInFacts": ["Tropical reefs — burrows in sand and coral", "Paired burrows have chimneys of pebbles.", "They rarely wander far from home."],
     "dietFacts": ["Small fish, worms, and scraps", "Stunned prey is dragged into the burrow.", "The snap also scares away rivals."],
     "sizeFacts": ["About as long as your finger", "Oversized claw can be half the body length.", "Red bands on some species mark the snapper."]},
    {"id": "eastern-quoll", "name": "Eastern Quoll", "emoji": "🐾", "type": "Mammal", "habitat": "Forest",
     "livesIn": "Tasmania — grasslands and forests (extinct on mainland)", "diet": "Insects, mice, fruit, and carrion",
     "size": "About as long as a cat", "funFact": "Eastern quolls have white spots on dark fur like a mini leopard!",
     "extraFact": "They are marsupials with a pouch facing backward.",
     "funFacts": ["Eastern quolls have white spots on dark fur like a mini leopard!", "They hunt at night and rest in dens by day.", "Pink nose and ears stand out on their face."],
     "didYouKnowFacts": ["Foxes and cats hurt mainland populations long ago.", "They perform a stiff-legged hop when excited.", "Six babies often fit in the mother's pouch."],
     "livesInFacts": ["Tasmania — grasslands and forests (extinct on mainland)", "Log piles and rock crevices are dens.", "Farmland edges offer mice to hunt."],
     "dietFacts": ["Insects, mice, fruit, and carrion", "They help control farm pests.", "Seasonal fruit adds variety in autumn."],
     "sizeFacts": ["About as long as a cat", "Two color phases exist: fawn and black.", "Slender body suits chasing fast prey."]},
    {"id": "sawfish", "name": "Sawfish", "emoji": "🐟", "type": "Fish", "habitat": "Ocean",
     "livesIn": "Warm coastal rivers and estuaries worldwide", "diet": "Small fish stunned and sliced by the rostrum",
     "size": "Rostrum to tail can exceed a small car", "funFact": "A sawfish's snout is lined with teeth-like scales called a rostrum!",
     "extraFact": "They are rays, not sharks, with gills underneath.",
     "funFacts": ["A sawfish's snout is lined with teeth-like scales called a rostrum!", "They slash sideways to herd fish.", "Sensors on the rostrum detect prey heartbeats in sand."],
     "didYouKnowFacts": ["All sawfish species are critically endangered.", "Rostrum can be one-third of total length.", "They sometimes mistaken ly attack fishing nets."],
     "livesInFacts": ["Warm coastal rivers and estuaries worldwide", "Muddy bottoms hide them from above.", "Young grow up in freshwater before moving to sea."],
     "dietFacts": ["Small fish stunned and sliced by the rostrum", "Crustaceans on the bottom are raked up.", "They swallow food whole after disabling it."],
     "sizeFacts": ["Rostrum to tail can exceed a small car", "Flat body is shark-like on top, ray-like below.", "Eyes sit on the sides of a broad head."]},
    {"id": "nurse-shark", "name": "Nurse Shark", "emoji": "🦈", "type": "Fish", "habitat": "Ocean",
     "livesIn": "Warm Atlantic and Pacific — reefs and mangroves", "diet": "Fish, squid, crustaceans, and mollusks sucked from sand",
     "size": "About as long as a kayak", "funFact": "Nurse sharks pile in groups under ledges to rest by day!",
     "extraFact": "They suck prey like a vacuum with strong throat muscles.",
     "funFacts": ["Nurse sharks pile in groups under ledges to rest by day!", "Barbels by the mouth feel for hidden prey.", "Their skin feels like rough sandpaper."],
     "didYouKnowFacts": ["They are gentle to divers compared to reef sharks.", "Tail can deliver a defensive bite if grabbed.", "Name may come from a sucking sound like a nursing baby."],
     "livesInFacts": ["Warm Atlantic and Pacific — reefs and mangroves", "Caves and ledges are daytime sleeping spots.", "Shallow lagoons suit their lazy lifestyle."],
     "dietFacts": ["Fish, squid, crustaceans, and mollusks sucked from sand", "Crushing teeth handle shells.", "They hunt more at night."],
     "sizeFacts": ["About as long as a kayak", "Spotted young darken to brown-gray adults.", "Broad head and small mouth fit bottom feeding."]},
    {"id": "mahi-mahi", "name": "Mahi-Mahi", "emoji": "🐟", "type": "Fish", "habitat": "Ocean",
     "livesIn": "Tropical open ocean — near floating debris and weed lines", "diet": "Flying fish, squid, and smaller fish",
     "size": "About as long as a tall person — bulls much bigger", "funFact": "Mahi-mahi flash brilliant green and gold, then fade gray when they die!",
     "extraFact": "Also called dolphinfish but they are not related to dolphins.",
     "funFacts": ["Mahi-mahi flash brilliant green and gold, then fade gray when they die!", "Males have a square forehead; females have a rounded head.", "They grow incredibly fast in warm seas."],
     "didYouKnowFacts": ["Sport anglers love their acrobatic leaps.", "They follow ocean currents and floating logs.", "A single female releases millions of eggs."],
     "livesInFacts": ["Tropical open ocean — near floating debris and weed lines", "Sargassum weed mats attract prey and mahi.", "They rarely touch the seafloor as adults."],
     "dietFacts": ["Flying fish, squid, and smaller fish", "Fast swimmers chase prey near the surface.", "They eat constantly to fuel rapid growth."],
     "sizeFacts": ["About as long as a tall person — bulls much bigger", "Crested forehead on large males looks hammer-shaped.", "Bright blue spots speckle the sides when alive."]},
    {"id": "leafy-sea-dragon", "name": "Leafy Sea Dragon", "emoji": "🐉", "type": "Fish", "habitat": "Ocean",
     "livesIn": "Southern Australia — kelp and seagrass beds", "diet": "Tiny mysid shrimp sucked through a long snout",
     "size": "About as long as a forearm", "funFact": "Leafy sea dragons look like drifting kelp — camouflage with leaf-shaped fins!",
     "extraFact": "Males carry bright pink eggs on their tail, not in a pouch.",
     "funFacts": ["Leafy sea dragons look like drifting kelp — camouflage with leaf-shaped fins!", "They barely swim — they bob like seaweed.", "Independent eyes can watch prey and predators at once."],
     "didYouKnowFacts": ["They are relatives of seahorses and pipefish.", "Collecting them is illegal in Australia.", "Gentle currents help them wander for food."],
     "livesInFacts": ["Southern Australia — kelp and seagrass beds", "Cool water full of hiding fronds is essential.", "They stay in a home range of one bay."],
     "dietFacts": ["Tiny mysid shrimp sucked through a long snout", "Suction feeding needs no teeth.", "They eat constantly because prey is small."],
     "sizeFacts": ["About as long as a forearm", "Leafy appendages are skin flaps, not for swimming.", "Yellow-green and brown tones match local plants."]},
    {"id": "nudibranch", "name": "Nudibranch", "emoji": "🐌", "type": "Mollusk", "habitat": "Ocean",
     "livesIn": "Reefs and tide pools worldwide — especially warm seas", "diet": "Sponges, anemones, hydroids, or other nudibranchs",
     "size": "From a grain of rice to a hot dog in largest species", "funFact": "Nudibranchs wear wild colors to warn predators they stole stinging cells from prey!",
     "extraFact": "They are sea slugs with exposed gills on their back.",
     "funFacts": ["Nudibranchs wear wild colors to warn predators they stole stinging cells from prey!", "They have no shell as adults.", "Two horn-like rhinophores smell and taste the water."],
     "didYouKnowFacts": ["Some can photosynthesize after eating algae.", "Over 3,000 species exist in many shapes.", "They leave a slime trail like land slugs."],
     "livesInFacts": ["Reefs and tide pools worldwide — especially warm seas", "Coral rubble and algae hold their food.", "They crawl slowly on a muscular foot."],
     "dietFacts": ["Sponges, anemones, hydroids, or other nudibranchs", "Stolen nematocysts line their back for defense.", "Bright colors often match toxic food sources."],
     "sizeFacts": ["From a grain of rice to a hot dog in largest species", "Frilly cerata on the back can be gills or weapons.", "Soft bodies are delicate out of water."]},
    {"id": "sea-pen", "name": "Sea Pen", "emoji": "🪸", "type": "Invertebrate", "habitat": "Ocean",
     "livesIn": "Soft sandy seafloors worldwide — shallow to deep", "diet": "Plankton caught by polyps on the branches",
     "size": "Some stand taller than a baseball bat", "funFact": "Sea pens look like old quill pens buried in sand — and glow green in the deep!",
     "extraFact": "They are colonies of tiny animals working as one.",
     "funFacts": ["Sea pens look like old quill pens buried in sand — and glow green in the deep!", "They anchor in sand with a bulbous root.", "When touched, many species deflate into the sediment."],
     "didYouKnowFacts": ["Each polyp has a special job in the colony.", "They sway in currents like underwater plants.", "Fish sometimes hide among the branches."],
     "livesInFacts": ["Soft sandy seafloors worldwide — shallow to deep", "Calm bottoms let them stay upright.", "Colonies grow slowly over many years."],
     "dietFacts": ["Plankton caught by polyps on the branches", "Tentacles on each polyp trap drifting food.", "Night feeding matches plankton rises."],
     "sizeFacts": ["Some stand taller than a baseball bat", "Feathery shape maximizes food-catching area.", "Red, purple, and orange colors are common."]},
    {"id": "ribbon-worm", "name": "Ribbon Worm", "emoji": "🪱", "type": "Invertebrate", "habitat": "Ocean",
     "livesIn": "Ocean shores and shallow seas — under rocks and sand", "diet": "Worms, clams, and small animals — some hunt, some scavenge",
     "size": "From an inch to over 100 feet in the longest species", "funFact": "Ribbon worms shoot a sticky proboscis like a lasso to grab prey!",
     "extraFact": "Bright colors warn that some species are toxic.",
     "funFacts": ["Ribbon worms shoot a sticky proboscis like a lasso to grab prey!", "Their bodies stretch incredibly thin.", "Some proboscises branch into two tips."],
     "didYouKnowFacts": ["Bootlace worms may be the world's longest animals.", "They regenerate lost body parts.", "Most live hidden where kids rarely see them."],
     "livesInFacts": ["Ocean shores and shallow seas — under rocks and sand", "Tide pools hide them under algae.", "They need moisture to survive out of water briefly."],
     "dietFacts": ["Worms, clams, and small animals — some hunt, some scavenge", "Proboscis glue traps prey outside the mouth.", "They digest meals inside a stretchy gut."],
     "sizeFacts": ["From an inch to over 100 feet in the longest species", "Flat ribbon shape slides through cracks.", "Smooth or wrinkled skin varies by species."]},
    {"id": "cotton-top-tamarin", "name": "Cotton-Top Tamarin", "emoji": "🐒", "type": "Mammal", "habitat": "Jungle",
     "livesIn": "Colombia — northwest rainforest", "diet": "Fruit, insects, sap, and gum",
     "size": "About as long as a squirrel", "funFact": "Cotton-top tamarins have a white mohawk that looks like cotton candy!",
     "extraFact": "They pee on their feet to leave scent trails on branches.",
     "funFacts": ["Cotton-top tamarins have a white mohawk that looks like cotton candy!", "Whole family groups help raise babies.", "They whistle and chirp in complex calls."],
     "didYouKnowFacts": ["Only about 2,000 remain in the wild.", "Twins are normal at every birth.", "Illegal pet trade threatens them severely."],
     "livesInFacts": ["Colombia — northwest rainforest", "Deforestation shrinks their tiny range.", "They need tall trees to leap safely."],
     "dietFacts": ["Fruit, insects, sap, and gum", "Long claws dig into bark for gum.", "Insects give protein for active monkeys."],
     "sizeFacts": ["About as long as a squirrel", "White crest stands out against black face and back.", "Reddish tail is not prehensile like some monkeys."]},
    {"id": "sloth-bear", "name": "Sloth Bear", "emoji": "🐻", "type": "Mammal", "habitat": "Jungle",
     "livesIn": "India and Sri Lanka — forests and grasslands", "diet": "Termites, ants, fruit, and honey",
     "size": "About as tall as a big dog at the shoulder", "funFact": "Sloth bears suck up termites like a vacuum with their floppy lips!",
     "extraFact": "Cubs ride on mother's back for months.",
     "funFacts": ["Sloth bears suck up termites like a vacuum with their floppy lips!", "Long curved claws rip open termite mounds.", "They stand on hind legs and whoof when threatened."],
     "didYouKnowFacts": ["They are the bears that inspired the character Baloo.", "Males do not help raise cubs.", "Their shaggy black coat lacks shoulder hump of brown bears."],
     "livesInFacts": ["India and Sri Lanka — forests and grasslands", "They avoid deep jungle without termite hills.", "Dry forest and wet forest both work for them."],
     "dietFacts": ["Termites, ants, fruit, and honey", "Missing upper incisors leave a gap for sucking insects.", "They knock down honeycombs with claws."],
     "sizeFacts": ["About as tall as a big dog at the shoulder", "White chest V or U mark is unique.", "Long lips and nostrils close while sucking insects."]},
    {"id": "sable", "name": "Sable", "emoji": "🦡", "type": "Mammal", "habitat": "Forest",
     "livesIn": "Russian and Mongolian taiga — snowy conifer forests", "diet": "Small mammals, birds, berries, and nuts",
     "size": "About as long as a house cat", "funFact": "Sables leap through deep snow to catch mice and voles!",
     "extraFact": "Their dark brown fur was once royal luxury in Russia.",
     "funFacts": ["Sables leap through deep snow to catch mice and voles!", "They climb trees to raid bird nests.", "Flexible ankles help them run down trees headfirst."],
     "didYouKnowFacts": ["They are relatives of martens and fishers.", "Territories are marked with scent from anal glands.", "Logging threatens old-growth forest homes."],
     "livesInFacts": ["Russian and Mongolian taiga — snowy conifer forests", "Deep snow is no problem for their big paws.", "Hollow trees are favorite dens."],
     "dietFacts": ["Small mammals, birds, berries, and nuts", "Summer adds blueberries and pine nuts.", "Winter hunting targets rodents under snow."],
     "sizeFacts": ["About as long as a house cat", "Yellow throat patch appears on some forms.", "Thick winter fur can be almost black."]},
    {"id": "least-weasel", "name": "Least Weasel", "emoji": "🦡", "type": "Mammal", "habitat": "Grassland",
     "livesIn": "Northern hemisphere — fields, meadows, and barns", "diet": "Mice, voles, and small birds",
     "size": "Smaller than a hamster — world's tiniest carnivore", "funFact": "Least weasels can slip through holes the size of a broomstick!",
     "extraFact": "They turn pure white in winter in cold regions.",
     "funFacts": ["Least weasels can slip through holes the size of a broomstick!", "They stash extra prey in hidden pantries.", "Fast metabolism needs several meals a day."],
     "didYouKnowFacts": ["They attack prey much bigger than themselves.", "Brown summer coat swaps to white except the tail tip.", "Farmers welcome them for rodent control."],
     "livesInFacts": ["Northern hemisphere — fields, meadows, and barns", "Stone walls and hay bales hide nests.", "They follow mouse tunnels in snow."],
     "dietFacts": ["Mice, voles, and small birds", "A bite to the skull kills prey instantly.", "They drink blood and eat muscle first."],
     "sizeFacts": ["Smaller than a hamster — world's tiniest carnivore", "Short legs and long body fit burrows.", "Tiny weight lets them run across snow crust."]},
]
