#!/usr/bin/env python3
"""Build animals_99.jsonl with curated kid-friendly facts."""

import json
from pathlib import Path

OUT = Path(__file__).parent / "animals_99.jsonl"

# id, name, emoji, type, habitat, funFact, extraFact, livesIn, diet, size,
# fun2, fun3, dyk2, dyk3, live2, live3, diet2, diet3, size2, size3
SPECS = [
    ("cardinal", "Cardinal", "🐦", "Bird", "Forest", "Male cardinals are bright red with a pointy crest!", "Cardinals do not migrate — many stay put all winter.", "Gardens and woods in eastern North America", "Seeds, berries, and insects", "About as long as your hand", "Females are soft brown with red on the wings and tail.", "They often visit backyard feeders for sunflower seeds.", "Both parents feed their chicks.", "A cardinal pair may raise two broods in one summer.", "They like bushes and small trees for nesting.", "Parents bring insects to chicks even when eating mostly seeds.", "Roughly sparrow-sized but with a longer tail."),
    ("great-blue-heron", "Great Blue Heron", "🐦", "Bird", "Ocean", "Great blue herons stand still like statues to catch fish!", "They can hunt day or night thanks to excellent vision.", "Marshes, rivers, and coasts across North America", "Fish, frogs, and small animals near water", "About as tall as a child with neck stretched up", "They fly with slow, deep wingbeats and neck tucked in.", "Long legs let them wade in shallow water without swimming.", "They nest in groups called rookeries in tall trees.", "Special neck vertebrae let them strike prey in a flash.", "Shallow wetlands give them room to stalk and spear fish.", "They swallow fish headfirst so fins do not catch.", "Wingspan can reach about six feet across."),
    ("stork", "Stork", "🐦", "Bird", "Grassland", "White storks are famous for nesting on rooftops in Europe!", "Parents clatter their bills to greet each other.", "Wet meadows and farmland from Europe to Africa", "Frogs, fish, insects, and small mammals", "About as tall as a grown-up's waist", "They migrate long distances between breeding and winter grounds.", "Huge stick nests are reused and grow bigger each year.", "Stork parents take turns warming eggs on the nest.", "Young storks snap their bills to ask for food.", "Open fields near water give them space to walk and hunt.", "They stab prey with a sharp bill, then swallow it whole.", "Long legs and neck help them see over tall grass."),
    ("sandhill-crane", "Sandhill Crane", "🐦", "Bird", "Grassland", "Sandhill cranes dance with jumps, bows, and wing flaps!", "Their loud trumpeting calls carry for miles.", "Prairies, marshes, and fields in North America", "Seeds, grains, insects, and small animals", "About as tall as a grown-up's chest", "They form huge flocks during migration.", "Gray feathers turn rusty brown when they stain feathers with mud.", "Pairs may stay together for many years.", "Chicks can walk and swim within a day of hatching.", "Wet prairies give them food and safe roosting water.", "They probe soil with bills to find roots and insects.", "Wingspan is wider than many children are tall."),
    ("hoopoe", "Hoopoe", "🐦", "Bird", "Grassland", "Hoopoes have a fan-shaped crest they can raise!", "Their name comes from the sound of their call: hoop-hoop-hoop.", "Open country, parks, and farms in Europe, Asia, and Africa", "Insects, worms, and small reptiles from the ground", "About as long as a city pigeon", "They nest in tree holes or wall cavities.", "Stiff tail feathers help them perch and balance.", "Hoopoe chicks can spray smelly liquid if threatened.", "Parents feed chicks insects gathered from lawns.", "Short grass makes it easy to probe soil for bugs.", "Strong bills pry larvae out of bark and dirt.", "Crest feathers are tipped with black and white bands."),
    ("magpie", "Magpie", "🐦", "Bird", "Forest", "Magpies are clever birds that can recognize themselves in a mirror!", "They collect shiny objects, but mostly eat natural food.", "Woodlands, farms, and towns across Europe and Asia", "Insects, fruit, seeds, and small animals", "About as long as a crow", "Black-and-white feathers shine green and blue in sunlight.", "They build domed nests in trees with a side entrance.", "Magpies belong to the crow family and are great problem solvers.", "They sometimes store food to eat later.", "Forest edges and fields give them both trees and open ground.", "Omnivore diets change with seasons and what is ripe.", "Long tail feathers make up half their length."),
    ("raven", "Raven", "🐦", "Bird", "Forest", "Ravens are among the smartest birds on Earth!", "They can mimic sounds, including human words in captivity.", "Mountains, forests, and coasts in the Northern Hemisphere", "Carrion, small animals, eggs, and human food scraps", "About as long as a hawk", "Shaggy throat feathers and wedge-shaped tails help tell them from crows.", "They soar on thermals and do amazing aerial rolls.", "Raven pairs work together to raise young.", "Young ravens play games, like sliding down snowbanks.", "Wild forests and cliffs give nesting ledges and food.", "They eat almost anything and remember good food spots.", "Wingspan can be nearly four feet wide."),
    ("jackdaw", "Jackdaw", "🐦", "Bird", "Farm", "Jackdaws have pale gray eyes and love chimneys and towers!", "They nest in colonies and chatter constantly.", "Towns, cliffs, and farms in Europe and western Asia", "Insects, seeds, and scraps found on the ground", "About as small as a crow", "They are the smallest crows in their range.", "Tight-knit flocks roost together at night.", "Jackdaws use sticks, wool, and mud in their nests.", "They sometimes follow plows to catch worms.", "Farm fields and villages give food and nest holes.", "Parents feed chicks insects and soft food at first.", "Compact bodies help them slip into narrow cavities."),
    ("storm-petrel", "Storm Petrel", "🐦", "Bird", "Ocean", "Storm petrels are tiny seabirds that patter on the water!", "Sailors once called them Mother Carey's chickens.", "Open oceans worldwide, returning to islands to nest", "Plankton, small fish, and oil from the sea surface", "About as small as a sparrow", "They have a great sense of smell for finding food at sea.", "Webbed feet help them dance on waves.", "Many nest in burrows on remote islands.", "They visit chicks only at night to avoid predators.", "Open sea is their home between breeding seasons.", "They dip bills to grab food from the surface.", "Light bodies and long wings suit life on the wind."),
    ("cormorant", "Cormorant", "🐦", "Bird", "Ocean", "Cormorants dive underwater and chase fish with their feet!", "After diving, they stand with wings spread to dry.", "Coasts, lakes, and rivers worldwide", "Fish caught while swimming underwater", "About as long as a goose", "Their feathers soak up water, which helps them dive deeper.", "They nest in colonies on cliffs or in trees.", "Some fishermen once trained cormorants to catch fish.", "A pouch under the tongue holds fish for chicks.", "Rocky shores and pilings give perches near prey.", "Sharp bills grip slippery fish underwater.", "Neck is long and snakelike when swimming."),
    ("grebe", "Grebe", "🐦", "Bird", "Ocean", "Grebes are expert divers with lobed toes, not webbed feet!", "Chicks ride on a parent's back to stay warm and safe.", "Freshwater lakes and ponds in many regions", "Small fish, insects, and water plants underwater", "About as long as a duck", "They run on water to take off because their legs sit far back.", "Seasonal feathers change from plain to bold patterns.", "Grebe nests float like rafts anchored to plants.", "Young grebes can swim soon after hatching.", "Quiet ponds give cover from waves and predators.", "They swallow feathers to help digest fish bones.", "Compact bodies are built for diving, not walking on land."),
    ("white-ibis", "White Ibis", "🐦", "Bird", "Grassland", "White ibises have curved red bills perfect for probing mud!", "Bright red legs match their bill in breeding season.", "Wetlands and coastal marshes in the southeastern United States", "Crabs, insects, and small fish in shallow water", "About as long as a chicken", "Juveniles are brown and slowly turn white.", "They fly in lines or V-shaped flocks.", "Ibises feed in groups, stirring prey with their feet.", "Parents regurgitate food for chicks in the nest.", "Marshes and mudflats are full of hidden snacks.", "Sensitive bill tips feel prey underwater in mud.", "Long neck lets them reach the ground while walking."),
    ("roseate-spoonbill", "Roseate Spoonbill", "🦩", "Bird", "Grassland", "Roseate spoonbills filter food with a bill shaped like a spoon!", "Their pink color comes from crustaceans in their diet.", "Coastal marshes and lagoons in the Americas", "Small fish, shrimp, and insects swept up in water", "About as tall as a goose", "When feeding, they swing their heads side to side in water.", "Bright pink feathers stand out in green mangroves.", "They nest in trees on islands away from predators.", "Spoonbills often feed in mixed flocks with herons.", "Shallow salty or fresh wetlands hold their prey.", "Bill works like a sieve to catch tiny animals.", "Wings show bold pink and red when they fly."),
    ("groundhog", "Groundhog", "🐿️", "Mammal", "Farm", "Groundhogs are famous for Groundhog Day weather predictions!", "They are also called woodchucks.", "Fields, meadows, and edges of forests in North America", "Grasses, clover, garden plants, and bark", "About as long as a house cat", "They dig burrows with separate rooms for sleeping and bathroom waste.", "Groundhogs whistle when alarmed.", "True hibernators: heart rate slows way down in winter.", "They can climb trees to escape danger or reach fruit.", "Farmland and grassy banks give food and digging space.", "Strong teeth grow all life and must stay worn down.", "Stocky bodies store fat before winter sleep."),
    ("yellow-bellied-marmot", "Yellow-bellied Marmot", "🐿️", "Mammal", "Grassland", "Yellow-bellied marmots whistle loudly from rocky slopes!", "They sunbathe on boulders on cool mornings.", "Alpine meadows and rock piles in western North America", "Grasses, flowers, and herbs", "About as big as a large house cat", "They hibernate about eight months of the year.", "Colonies share lookout duties while others feed.", "Burrows can be six feet deep under rocks.", "Pups learn alarm calls from adults quickly.", "Mountain meadows give soft plants and sun-warmed rocks.", "They clip grass with front teeth like tiny lawnmowers.", "Plump bodies help them survive long hibernation."),
    ("american-pika", "American Pika", "🐰", "Mammal", "Arctic", "Pikas gather hay piles of dried plants for winter!", "They look like mice but are related to rabbits.", "Talus slopes high in western North America mountains", "Grass, wildflowers, and leaves they store", "About as small as a tennis ball", "Pikas do not hibernate — they eat stored hay under snow.", "Their loud eeep calls warn neighbors of danger.", "Thick fur keeps them warm on cold rock slides.", "Pikas are sensitive to hot weather and need cool slopes.", "Rock piles near meadows give food and hiding cracks.", "They harvest plants quickly before winter snow arrives.", "Round ears and no tail help save heat in the cold."),
    ("black-tailed-prairie-dog", "Black-tailed Prairie Dog", "🐿️", "Mammal", "Grassland", "Prairie dogs live in huge underground towns!", "They kiss by touching teeth to recognize friends.", "Short-grass prairies in central North America", "Grass, seeds, and leafy plants", "About as long as a rabbit", "Colonies can cover hundreds of acres.", "Sentinel dogs bark different alarms for hawks versus snakes.", "Burrows have listening posts and escape tunnels.", "Prairie dog towns support many other animals.", "Short grass lets them see predators while feeding.", "They clip plants near burrows to watch for danger.", "Compact legs are built for running to hole entrances."),
    ("common-shrew", "Common Shrew", "🐭", "Mammal", "Forest", "Shrews must eat almost constantly because they burn energy fast!", "They have a venomous bite to subdue prey.", "Woodlands, gardens, and grasslands in Europe and Asia", "Insects, worms, and spiders", "About as long as your thumb", "A shrew's heart beats hundreds of times per minute.", "They use whiskers and smell more than eyesight.", "Some shrews are active day and night in short bursts.", "Females can have many litters in one summer.", "Leaf litter in forests hides worms and beetles.", "Pointy teeth grab prey too big to swallow whole at once.", "Tiny bodies lose heat quickly, so they eat often."),
    ("muskrat", "Muskrat", "🐀", "Mammal", "Ocean", "Muskrats build dome lodges from plants in wetlands!", "They are good swimmers but are rodents, not rats.", "Marshes, ponds, and slow rivers in North America", "Cattails, roots, and aquatic plants", "About as long as a small cat", "Their tails are flat sideways like a paddle rudder.", "They can stay underwater several minutes.", "Muskrat houses have underwater entrances.", "Fur traps air for warmth while swimming.", "Wetlands provide both food plants and shelter.", "Strong gnawing teeth cut stems underwater.", "Webbed back feet push them through water."),
    ("saiga", "Saiga", "🦌", "Mammal", "Grassland", "Saiga antelopes have bulbous noses that filter dusty air!", "Huge herds once roamed Asian steppes.", "Dry grasslands in Kazakhstan and nearby countries", "Grasses and desert plants", "About as tall as a pony", "Males carry odd-looking horns used in shoving matches.", "Saiga can run about 50 miles per hour.", "Their noses warm cold winter air before it reaches lungs.", "Calves can run within hours of birth.", "Open steppe gives long views for spotting wolves.", "Migrating herds follow rains to fresh grass.", "Stocky bodies handle cold winds on open plains."),
    ("takin", "Takin", "🐐", "Mammal", "Forest", "Takins are goat-antelopes of the Himalayan mountains!", "Golden fur and a big nose help them in cold mist.", "Steep bamboo forests in China and the Himalayas", "Leaves, bark, and bamboo shoots", "About as tall as a pony", "They climb cliffs with hooves that grip rock.", "Takins sometimes gather in herds in winter.", "Thick coats shed in warmer months.", "Calves hide on ledges while mothers feed nearby.", "Mountain forests give tough plants other animals skip.", "Powerful shoulders help push through bamboo thickets.", "Heavy bodies suit cold, windy ridges."),
    ("babirusa", "Babirusa", "🐗", "Mammal", "Jungle", "Male babirusas have tusks that curve up and can pierce their own skull!", "They are wild pigs of Indonesian rainforests.", "Swamps and forests on Indonesian islands", "Fruit, leaves, and small animals they find", "About as long as a sheep", "Tusks are actually long upper canine teeth.", "They wallow in mud to cool off.", "Babirusas are good swimmers crossing rivers.", "Pigs root with noses to uncover food.", "Rainforest floor offers fruit and roots year-round.", "Omnivore teeth crush nuts and tear plants.", "Barrel-shaped bodies crash through thick brush."),
    ("pygmy-marmoset", "Pygmy Marmoset", "🐒", "Mammal", "Jungle", "Pygmy marmosets are the smallest monkeys in the world!", "They cling to tree trunks and gouge holes to drink sap.", "Amazon rainforest treetops in South America", "Tree sap, gum, insects, and fruit", "About as long as your hand", "They weigh less than a stick of butter.", "Tails are longer than their bodies for balance.", "Family groups help care for tiny twins.", "Sharp claws grip bark like climbing hooks.", "Tall rainforest trees give sap and insect hiding spots.", "Long tongues lick sap from holes they make.", "Light bodies let them run on thin branches."),
    ("gray-langur", "Gray Langur", "🐒", "Mammal", "Jungle", "Gray langurs are sacred monkeys in many parts of India!", "They leap between branches with long tails for balance.", "Forests, temples, and towns in South and Southeast Asia", "Leaves, fruit, flowers, and seeds", "About as long as a medium dog", "Silver-gray fur and black faces are easy to spot.", "Troops have many females and fewer males.", "Langurs bark alarms when leopards approach.", "Babies cling to mothers' bellies, then backs.", "Forest trees supply leaves they eat most of the day.", "Strong stomachs digest tough leafy food.", "Long tails act like a balancing pole when jumping."),
    ("fossa", "Fossa", "🐆", "Mammal", "Jungle", "The fossa is Madagascar's top predator — like a cat-dog climber!", "It hunts lemurs in trees with flexible ankles.", "Madagascar's forests and scrub", "Lemurs, lizards, and birds", "About as long as a medium dog", "Ankles rotate so it can climb down trees headfirst.", "Rough tongue helps scrape meat from bones.", "Solitary hunters patrol large territories.", "Kits grow in tree hollow dens.", "Island forests give climbing trunks and prey.", "Sharp teeth and claws grab agile lemurs.", "Slender body fits along branches."),
    ("small-spotted-genet", "Small-spotted Genet", "🐱", "Mammal", "Forest", "Genets look like spotted cats but are related to civets!", "They climb trees and hunt at night.", "Woodlands and rocky hills in Africa and Europe", "Rodents, birds, insects, and fruit", "About as long as a house cat", "Long banded tails help them balance.", "Large ears hear mice rustling in the dark.", "They mark trails with scent from a gland.", "Retractable claws grip bark when climbing.", "Woodland edges give both cover and open hunting.", "Quick pounces catch prey on the ground.", "Spotted coat breaks up their outline in dappled light."),
    ("margay", "Margay", "🐆", "Mammal", "Jungle", "Margays can twist their ankles to climb down trees headfirst!", "They copy baby monkey calls to lure prey.", "Rainforests in Central and South America", "Small monkeys, birds, and rodents", "About as long as a house cat", "Huge eyes help them hunt in dim forest light.", "Margays are among the best tree-climbing cats.", "Kits practice climbing before they hunt alone.", "Flexible joints make branch walking look easy.", "Dense jungle trees are highways for margays.", "Silent stalking keeps prey from hearing them.", "Light build suits branches better than heavy ground chases."),
    ("spectacled-bear", "Spectacled Bear", "🐻", "Mammal", "Jungle", "Spectacled bears have light rings around their eyes!", "They are the only bears native to South America.", "Andean cloud forests and scrub", "Fruit, bromeliads, and small animals", "About as tall as a person's waist at the shoulder", "They build leafy platforms in trees to rest and feed.", "Strong claws tear open termite nests.", "Shy bears usually avoid people.", "Cubs stay with mothers over a year.", "Mountain forests offer fruit seasons and caves.", "Flexible lips pluck fruit from spiny plants.", "Medium-sized bears fit climbing trunks."),
    ("wolverine", "Wolverine", "🐺", "Mammal", "Arctic", "Wolverines have a fierce reputation and can drive bears off a kill!", "Their Latin name means glutton because they eat a lot.", "Northern forests and tundra in North America and Eurasia", "Carrion, small mammals, and berries", "About as big as a medium dog but very strong", "Huge paws work like snowshoes in winter.", "They roam enormous territories.", "Thick fur resists frost and snow.", "Jaws can crush frozen bones.", "Cold forests and tundra hide food under snow they dig up.", "Strong smell leads them to carcasses from far away.", "Low, wide bodies push through deep powder."),
    ("american-mink", "American Mink", "🦦", "Mammal", "Ocean", "Mink are sleek swimmers that hunt in rivers and coasts!", "Farmed mink gave us the word for dark brown fur.", "Streams, lakes, and coasts in North America", "Fish, crayfish, frogs, and small mammals", "About as long as a cat", "They slip into burrows and even raid chicken coops.", "Partially webbed feet push them through water.", "Thick oily fur sheds water when diving.", "Females line dens with fur and feathers.", "Rivers and marshes pack prey along banks.", "Quick bites behind the head catch slippery fish.", "Long, thin bodies dive through narrow gaps."),
    ("harbor-porpoise", "Harbor Porpoise", "🐬", "Mammal", "Ocean", "Harbor porpoises are small, shy porpoises of coastal bays!", "Unlike dolphins, they rarely ride boat bow waves.", "Cool coastal waters of the North Atlantic and Pacific", "Fish and squid near the seafloor", "About as long as a human child", "They surface briefly with a quiet puffing breath.", "Triangular dorsal fin is small compared to dolphins.", "Echolocation clicks find fish in murky water.", "Mothers nurse calves for several months.", "Shallow seas near shores hold schools of fish.", "They eat many small meals through the day.", "Compact bodies lose heat fast, so they stay well fed."),
    ("fin-whale", "Fin Whale", "🐋", "Mammal", "Ocean", "Fin whales are the second-largest animals on Earth!", "Asymmetrical jaw color may help them herd fish.", "Open oceans worldwide in cool to warm seas", "Tiny krill and small schooling fish filtered from water", "Longer than a school bus", "They can swim bursts over 20 miles per hour.", "Blow sprays tall and shaped like a cone.", "Baleen plates hang from the upper jaw like a curtain.", "Migrating fin whales follow seasonal food blooms.", "Open water plankton swarms define where they feed.", "They gulp huge mouthfuls then squeeze water out.", "Sleek bodies slice through water with little splash."),
    ("sperm-whale", "Sperm Whale", "🐋", "Mammal", "Ocean", "Sperm whales dive deeper than almost any mammal!", "They hunt giant squid in the dark deep sea.", "Deep oceans worldwide", "Squid, fish, and deep-sea creatures", "About as long as a school bus", "The head holds a waxy organ called spermaceti.", "Sperm whales click loudly for echolocation and talk.", "Pods of females and young stay together for years.", "A single blowhole sits at the front left of the snout.", "Deep trenches offer squid and fish far below sunlight.", "They can hold breath over an hour on deep dives.", "Block-shaped heads are one-third of body length."),
    ("pilot-whale", "Pilot Whale", "🐋", "Mammal", "Ocean", "Pilot whales are social dolphins with rounded heads!", "Mass strandings sometimes puzzle scientists.", "Warm and temperate seas worldwide", "Squid and fish caught in deep dives", "About as long as a small bus", "They form tight pods that stick together.", "Males are much larger than females.", "Echolocation finds prey in dark water.", "Calves nurse and learn from many adults.", "Offshore waters hold squid migrations they follow.", "Strong jaws grip slippery squid.", "Robust bodies handle long dives."),
    ("southern-stingray", "Southern Stingray", "🐟", "Fish", "Ocean", "Southern stingrays hide under sand with only eyes showing!", "Their barbed tail is used for defense, not attack.", "Sandy bottoms of the Atlantic and Gulf of Mexico", "Shellfish, worms, and crabs buried in sand", "Wingspan about as wide as a coffee table", "They flap wing-like fins to swim gracefully.", "Mouth and gills are on the underside.", "Electric sensors find prey hidden in sand.", "Females can have several pups a year.", "Sandy flats near coasts hide clams and worms.", "Crushing teeth break shells to eat soft insides.", "Flat shape lets them vanish under a thin sand coat."),
    ("great-hammerhead", "Great Hammerhead", "🦈", "Fish", "Ocean", "Hammerheads spread sensors along their wide head!", "The hammer shape may help them turn quickly.", "Warm coastal seas worldwide", "Stingrays, fish, and crustaceans", "About as long as a small car", "Eyes sit at the ends of the hammer for wide view.", "They sometimes swim on their side at the surface.", "Schools of hammerheads gather in some regions.", "Pups are born live, not from eggs.", "Reefs and sandy bays hold stingrays they hunt.", "Serrated teeth cut prey into chunks.", "Tall dorsal fin makes a clear silhouette."),
    ("goblin-shark", "Goblin Shark", "🦈", "Fish", "Ocean", "Goblin sharks have a long snout and jaw that shoots forward!", "Pink skin looks strange because blood vessels show through.", "Deep slopes in oceans near Japan and other regions", "Fish, squid, and crustaceans in deep water", "About as long as a small car", "They are rarely seen alive by people.", "Slingshot jaws snap out to grab prey.", "Small eyes suit dim deep-sea light.", "Slow swimmers ambush rather than chase.", "Dark depths below 800 feet are their main zone.", "Needle-like teeth snag soft deep-sea animals.", "Flabby bodies save energy in food-poor depths."),
    ("basking-shark", "Basking Shark", "🦈", "Fish", "Ocean", "Basking sharks swim with mouth wide open to filter plankton!", "They are the second-largest fish in the world.", "Cool seas of the Atlantic and Pacific", "Tiny plankton strained from huge gulps of water", "About as long as a bus", "Gill slits almost circle the head.", "Despite size, they eat animals smaller than ants.", "Harmless to people — no sharp teeth for biting.", "Summer plankton blooms draw them near coasts.", "Open water near surface holds seasonal plankton.", "They swim slowly with mouth agape for hours.", "Enormous livers help them float and store energy."),
    ("sea-lamprey", "Sea Lamprey", "🐟", "Fish", "Ocean", "Lampreys are ancient fish with round sucker mouths!", "Some lampreys attach to other fish to drink blood.", "Coastal rivers and oceans in the Atlantic", "Blood and fluids from host fish; also filter feeding when young", "About as long as your forearm", "Seven gill holes behind the eyes look like a ring.", "They build nests in gravel with stones moved by mouths.", "Lampreys have no jaws — only a sucking disk.", "Young larvae filter feed hidden in stream mud for years.", "Rivers linked to oceans let them migrate to spawn.", "Adults stop eating after spawning in some species.", "Eel-like bodies writhe up waterfalls to breed."),
    ("hagfish", "Hagfish", "🐟", "Fish", "Ocean", "Hagfish tie themselves in knots to scrape off slime!", "They can produce buckets of slime in minutes.", "Muddy seafloors in cold oceans worldwide", "Worms and dead animals they burrow into", "About as long as a scarf", "They have no jaws and feed through skin.", "Four hearts help pump blood in a simple body.", "Hagfish slime clogs gills of attackers.", "They enter dead whales through the mouth.", "Soft ocean mud hides worms they eat.", "Knotting behavior pulls food off their own head.", "Boneless bodies slip into tight carcasses."),
    ("coelacanth", "Coelacanth", "🐟", "Fish", "Ocean", "Coelacanths were called living fossils — known from fossils before live ones!", "Lobe fins look like stubby legs.", "Deep caves off eastern Africa and Indonesia", "Fish and squid near rocky slopes", "About as long as a human", "They give birth to live young.", "Rough scales feel like sandpaper.", "Night hunters drift slowly in currents.", "Fins move in an alternating pattern like early land walkers.", "Deep rocky reefs shelter them from waves.", "Slow metabolism suits scarce deep food.", "Heavy bodies are buoyant with oil-rich fat."),
    ("giant-oarfish", "Giant Oarfish", "🐟", "Fish", "Ocean", "Oarfish may be the longest bony fish in the world!", "Silvery ribbon bodies wash ashore after storms.", "Deep open water, rarely seen alive", "Tiny crustaceans and jelly animals", "Can reach longer than a school bus", "Red crests on the head may sense prey.", "They swim vertically, head up, in the deep.", "No scales — skin is silvery and fragile.", "Legends of sea serpents may come from oarfish.", "Open ocean depths keep them away from coasts.", "Small mouths eat plankton-sized food.", "Thin bodies ripple like ribbons when swimming."),
    ("barreleye", "Barreleye", "🐟", "Fish", "Ocean", "Barreleye fish have a transparent dome on their head!", "Green tubular eyes point upward to spot prey silhouettes.", "Deep tropical and temperate oceans", "Small crustaceans caught overhead", "About as long as your hand", "Eyes can rotate to look forward when feeding.", "They hang motionless in the water column.", "Transparent shield protects soft eyes.", "Mouth is tiny compared to the head.", "Dark water above them shows prey backlit by surface light.", "They steal food from siphonophores sometimes.", "Delicate bodies live far below sunlit waves."),
    ("fangtooth", "Fangtooth", "🐟", "Fish", "Ocean", "Fangtooth fish have huge teeth that do not fit inside their mouth!", "They are small but look scary.", "Deep oceans worldwide", "Fish and squid in the midnight zone", "About as long as your hand", "Teeth are so long the fish cannot close its mouth fully.", "Dark color hides them in black water.", "They migrate upward at night to feed.", "Large mouth gapes wide for big bites.", "Deep water has scattered prey they chase upward.", "Needle teeth hold slippery deep fish.", "Small bodies mean they eat prey nearly their own size."),
    ("red-king-crab", "Red King Crab", "🦀", "Crustacean", "Arctic", "Red king crabs are giants of cold northern seas!", "Fisheries move them to new areas by accident sometimes.", "Cold Pacific waters off Alaska and Russia", "Clams, worms, sea stars, and dead animals", "Leg span wider than a bicycle wheel", "They walk on eight walking legs, not the claws.", "Shell must be shed to grow — a soft stage follows.", "Males often have one claw much larger.", "Millions of larvae drift in plankton before settling.", "Cold seabeds with sand and mud hold food.", "Powerful claws crush shells of prey.", "Spiny shells protect against predators."),
    ("giant-isopod", "Giant Isopod", "🐛", "Crustacean", "Ocean", "Giant isopods look like enormous pill bugs!", "They scavenge on the deep seafloor.", "Deep Atlantic and Pacific floors", "Dead whales, fish, and slow prey", "About as long as a shoe", "Seven pairs of legs walk along mud.", "They can roll into a ball like roly-polies.", "Slow metabolism lets them wait months between meals.", "Large eyes catch dim deep-sea light.", "Abyssal plains are their main neighborhood.", "Mandibles shred rotting food.", "Flattened bodies squeeze under rocks."),
    ("purple-sea-urchin", "Purple Sea Urchin", "🦔", "Invertebrate", "Ocean", "Sea urchins are spiny grazers that mow down kelp!", "Their mouth has five teeth that scrape rock.", "Rocky shores of the Pacific Ocean", "Algae and kelp they scrape from rocks", "Ball about as big as an apple", "Spines move on ball-and-socket joints.", "Tube feet between spines grip surfaces.", "Urchin roe is food in some countries.", "They hide in rock crevices from waves.", "Kelp forests and rocky reefs supply algae.", "Teeth grow continuously like a rodent.", "Round tests (shells) remain after spines fall off."),
    ("sand-dollar", "Sand Dollar", "🦔", "Invertebrate", "Ocean", "Sand dollars are flat urchins that live in sandy bottoms!", "Living sand dollars are covered in tiny spines.", "Sandy floors of temperate oceans", "Tiny particles and organisms filtered from sand", "About as wide as a cookie", "Five petal-shaped patterns show where tube feet were.", "They burrow so only the edge sticks out.", "Spines move food toward the mouth on the underside.", "Larvae drift before settling as adults.", "Calm sandy bays let them stay buried safely.", "Mouth parts chew organic film off grains.", "Flattened shape resists waves rolling them."),
    ("aye-aye", "Aye-aye", "🐒", "Mammal", "Jungle", "Aye-ayes use a long middle finger to tap wood and find grubs!", "Many people in Madagascar once thought they brought bad luck.", "Rainforests of Madagascar", "Insect larvae hidden inside tree bark", "About as long as a house cat", "Huge ears hear larvae moving inside wood.", "Bushy tail is longer than other lemurs.", "Glowing eyes reflect light at night.", "Only one young is raised at a time.", "Island trees give bark full of insect tunnels.", "Hooked finger pulls grubs out after tapping.", "Odd looks come from special feeding tools."),
    ("indri", "Indri", "🐒", "Mammal", "Jungle", "Indris sing loud morning calls that echo through forests!", "They are the largest living lemurs.", "Eastern rainforests of Madagascar", "Leaves, fruit, and flowers", "About as tall as a child when upright", "They cannot hang by their tails — tails are short stubs.", "Powerful legs leap vertically between trunks.", "Black and white fur stands out in green forest.", "Pairs sing duets to defend territory.", "Treetops in wet forests supply leaves all day.", "Hands grip branches like climbing hooks.", "Stocky bodies support loud calling and leaping."),
    ("coquerels-sifaka", "Coquerel's Sifaka", "🐒", "Mammal", "Jungle", "Sifakas dance sideways on the ground with arms up!", "On trees they leap upright like kangaroos.", "Dry forests of western Madagascar", "Leaves, fruit, and bark", "About as long as a large cat", "White fur contrasts with maroon arms and thighs.", "They rarely drink — moisture comes from food.", "Group members groom each other often.", "Infants cling to mothers' bellies at first.", "Spiny dry forest trees give tough leaves.", "Careful leaf choice avoids toxic plants.", "Long legs make ground dancing look comical."),
    ("galapagos-tortoise", "Galapagos Tortoise", "🐢", "Reptile", "Grassland", "Galapagos tortoises can live more than 100 years!", "Different islands have shell shapes suited to local plants.", "Galapagos Islands volcanic highlands", "Grasses, cactus pads, and fruits", "Shell longer than a kitchen table", "They store water and fat inside for dry seasons.", "Domed shells suit ground feeding; saddle shells reach higher plants.", "Slow metabolism needs little daily food.", "They wallow in mud to cool off.", "Island meadows and scrub give prickly pear cactus.", "Strong jaws crush tough plants.", "Massive legs support hundreds of pounds."),
    ("tuatara", "Tuatara", "🦎", "Reptile", "Ocean", "Tuataras are living fossils from New Zealand — not true lizards!", "They have a third eye on top of the head (under skin).", "Cool coastal islands and forests of New Zealand", "Insects, worms, and small lizards", "About as long as a forearm", "They prefer cool weather and bask in sun.", "Spiny crest runs down the back and tail.", "Can live over 100 years.", "Males fight with crest displays.", "Island burrows and forests hide invertebrate prey.", "Jaws slice insects with sharp teeth.", "Slow growth means late maturity."),
    ("common-basilisk", "Common Basilisk", "🦎", "Reptile", "Jungle", "Basilisk lizards run on water on their hind legs!", "They are nicknamed Jesus Christ lizards.", "Rainforest streams in Central America", "Insects, small fish, and flowers", "About as long as your forearm with tail", "Long toes and fringes slap water to stay up briefly.", "They dive into streams when scared.", "Males have crests on head and back.", "Tail cannot grow back if lost.", "Streamside jungle gives insects and escape water.", "Quick jaws snap up flies and crickets.", "Light build helps sprint on surface film."),
    ("blue-tongue-skink", "Blue-tongue Skink", "🦎", "Reptile", "Desert", "Blue-tongue skinks stick out a bright blue tongue to scare predators!", "They look like small snakes from a distance.", "Woodlands and suburbs in Australia", "Snails, insects, fruit, and flowers", "About as long as a ruler", "Short legs make them slow but sturdy.", "They give live birth instead of laying eggs.", "Armored scales feel like chain mail.", "They hiss and flatten bodies when threatened.", "Australian bush gives snails and fallen fruit.", "Strong jaws crush snail shells.", "Wide bodies look thicker than most lizards."),
    ("black-mamba", "Black Mamba", "🐍", "Reptile", "Grassland", "Black mambas are fast, long African snakes — not always black!", "Inside the mouth is dark, which gave them their name.", "Savannas and rocky hills in sub-Saharan Africa", "Small mammals and birds", "About as long as a small car", "They can move very quickly on the ground.", "Neurotoxic venom requires quick medical care.", "They raise the front of the body when threatened.", "Prefer to escape rather than bite if they can.", "Open savanna gives sun and hiding rock cracks.", "They strike repeatedly if cornered.", "Slim bodies slip through grass silently."),
    ("gray-tree-frog", "Gray Tree Frog", "🐸", "Amphibian", "Forest", "Gray tree frogs can change from gray to green!", "Sticky toe pads let them climb windows and trees.", "Woodlands in eastern North America", "Insects and spiders caught at night", "About as long as a thumb", "They freeze in winter and thaw in spring.", "Loud trilling calls fill warm nights.", "Skin can taste and absorb water.", "Eggs hatch in ponds; adults live in trees.", "Forest pools and backyard ponds breed tadpoles.", "Tongues flip insects into the mouth.", "Plump toe pads grip smooth surfaces."),
    ("blue-poison-dart-frog", "Blue Poison Dart Frog", "🐸", "Amphibian", "Jungle", "Bright blue skin warns predators that this frog is toxic!", "Wild frogs get poison from ants they eat.", "Rainforests in Suriname", "Tiny ants and mites", "About as small as a thumb", "Parents carry tadpoles to water in bromeliad cups.", "Brilliant color says do not eat me.", "Captive frogs without certain ants are less toxic.", "Males guard eggs on the forest floor.", "Bromeliad plants hold rainwater nurseries.", "They hunt with a quick tongue flick.", "Tiny size makes them easy to miss on leaves."),
    ("lionfish", "Lionfish", "🐟", "Fish", "Ocean", "Lionfish have venomous spines and beautiful striped fins!", "They are invasive in parts of the Atlantic.", "Coral reefs and rocky reefs in warm seas", "Small fish and shrimp cornered by spreading fins", "About as long as a forearm", "Fan-like fins herd prey before a gulp.", "Spines deliver painful stings to predators and people.", "They hunt mostly at dawn and dusk.", "One female can release thousands of eggs.", "Reef crevices hide prey they corner.", "Large mouth creates suction to swallow fish.", "Slow swimming relies on camouflage."),
    ("blue-marlin", "Blue Marlin", "🐟", "Fish", "Ocean", "Blue marlins are powerful fish with spear-like bills!", "Sport fishers respect their long fights on the line.", "Warm open oceans worldwide", "Tuna, mackerel, and squid", "Bill to tail longer than a car", "They heat their eyes and brain for sharper deep hunting.", "Spear bill may stun schooling fish.", "Females are much larger than males.", "Larvae are tiny; adults grow huge fast.", "Open sea hunting follows warm currents.", "Fast bursts chase fast prey.", "Streamlined bodies cut drag at speed."),
    ("atlantic-sailfish", "Atlantic Sailfish", "🐟", "Fish", "Ocean", "Sailfish raise a tall dorsal fin like a sail!", "They are among the fastest fish in the sea.", "Warm Atlantic surface waters", "Schooling fish herded with their bill", "About as long as a tall person", "Colors flash when excited.", "They work together to herd baitfish balls.", "Bill slashes injure prey for easier eating.", "Sail can fold down in a groove.", "Surface waters hold sardine schools they chase.", "Bursts near 60 mph make them blur.", "Slender bills slash sideways through schools."),
    ("anchovy", "Anchovy", "🐟", "Fish", "Ocean", "Anchovies form giant shimmering schools in the sea!", "They are small fish eaten by whales, birds, and people.", "Coastal and open waters worldwide", "Plankton and tiny drifting animals", "About as long as your finger", "A stripe along the side flashes silver.", "Schools twist like one giant animal.", "Eggs float and hatch into larvae at sea.", "Filter feeding strains food from water.", "Coastal upwellings bring plankton they need.", "They are food for many ocean hunters.", "Small size lets millions survive together."),
    ("sardine", "Sardine", "🐟", "Fish", "Ocean", "Sardines stay safe by swimming in tight, swirling balls!", "Their name comes from the island of Sardinia.", "Temperate and tropical seas worldwide", "Plankton and small crustaceans", "About as long as your hand", "Scales reflect light so predators get confused.", "Some sardine runs migrate along coasts.", "They are relatives of herring.", "Fast turns in schools reduce catches by predators.", "Cool upwelling seas grow plankton blooms.", "Gill rakers trap tiny food particles.", "Silvery sides hide them in sunlit water."),
    ("betta", "Betta", "🐟", "Fish", "Ocean", "Betta fish breathe air with a special labyrinth organ!", "Males flare fins and fight other males.", "Shallow rice paddies and streams in Southeast Asia", "Insects, larvae, and small crustaceans", "About as long as your hand", "Wild bettas are duller than pet store colors.", "Males build bubble nests at the surface.", "Females lay eggs that males guard.", "They gulp air when water is low in oxygen.", "Warm shallow waters hold insects above mud.", "Upward mouth snatches prey at the surface.", "Long fins are bred for beauty in aquariums."),
    ("guppy", "Guppy", "🐟", "Fish", "Ocean", "Guppies are tiny fish famous in aquariums worldwide!", "Females can store sperm and have many broods.", "Streams and ponds in South America and worldwide", "Algae, small insects, and detritus", "About as long as a paperclip", "Males are more colorful to impress females.", "Live birth means no egg stage for babies.", "They adapt quickly — useful for science studies.", "Tail shapes vary wildly in pet breeds.", "Quiet ponds give warm water and food bits.", "They pick food from surface and midwater.", "Small bodies fit in puddles after rain."),
    ("mountain-goat", "Mountain Goat", "🐐", "Mammal", "Arctic", "Mountain goats climb near-vertical cliffs!", "They are more closely related to antelopes than domestic goats.", "Alpine peaks of western North America", "Grasses, lichens, and shrubs on cliffs", "About as tall as a child's shoulder", "White coats and beards help in snowy peaks.", "Rubber-like pads grip rock with rough edges.", "Kids practice climbing soon after birth.", "Horns grow rings like tree trunks show age.", "High rocky slopes have few predators.", "They lick minerals from rocks at salt licks.", "Thick fur insulates on windy ridges."),
    ("alpine-ibex", "Alpine Ibex", "🐐", "Mammal", "Arctic", "Male ibex clash horns on cliff edges!", "Horns can weigh over 30 pounds combined.", "High Alps and other European mountains", "Grass, herbs, and lichens on steep slopes", "About as tall as a waist at the shoulder", "They descend to valleys in winter.", "Hooves are soft on inside, hard outside for grip.", "Kids leap on scary slopes within days.", "Horns curve backward in a grand arc.", "Steep alpine meadows limit predators.", "They balance on tiny ledges to reach plants.", "Muscular necks power horn clashes."),
    ("springbok", "Springbok", "🦌", "Mammal", "Grassland", "Springboks pronk — jump straight up with stiff legs!", "National animal of South Africa.", "Dry grasslands of southern Africa", "Grass and leaves", "About as tall as a waist", "Dark stripes on the sides break up their outline.", "Herds migrate after rain green-up.", "Speed and leaps confuse predators.", "White rump flashes when alarmed.", "Open savanna gives long sightlines.", "They get moisture from plants in dry times.", "Lean legs built for sudden hops."),
    ("greater-kudu", "Greater Kudu", "🦌", "Mammal", "Forest", "Male kudus have spiraling horns up to six feet along the curl!", "Stripes help them hide in bush.", "Woodlands and thickets in eastern and southern Africa", "Leaves, fruit, and grass", "About as tall as a horse at the shoulder", "They freeze rather than run if they think they are hidden.", "Horns grow slowly in a tight spiral.", "Big ears swivel to catch lion sounds.", "Bulls often live alone; cows form groups.", "Brushy forests give cover and browse.", "Long neck reaches high branches.", "White cheek stripes and spine lines camouflage."),
    ("giant-centipede", "Giant Centipede", "🐛", "Arachnid", "Jungle", "Giant centipedes have one pair of legs per body segment!", "They are fast predators with venom claws.", "Tropical forests worldwide", "Insects, spiders, and small vertebrates", "About as long as a ruler or longer", "First pair of legs are modified fangs.", "They hunt at night using antennae.", "Flexible bodies slip into burrows.", "Some species swim briefly.", "Leaf litter in humid forests hides prey.", "Venom subdues animals bigger than their head.", "Many legs ripple in a wave when running."),
    ("cone-snail", "Cone Snail", "🐚", "Mollusk", "Ocean", "Cone snails harpoon fish with a venomous tooth!", "Pretty shells hide a dangerous hunter.", "Tropical coral reefs and sandy flats", "Fish caught with a harpoon-like radula tooth", "Shell about as long as your thumb", "Patterns on shells attract collectors.", "They move on a muscular foot.", "Some venoms are studied for medicine.", "Harpoon tooth fires from a proboscis tube.", "Reef sand hides them waiting to ambush.", "Instant venom paralyzes fish prey.", "Slow snail body does not chase prey."),
    ("chinchilla", "Chinchilla", "🐭", "Mammal", "Desert", "Chinchilla fur is so dense fleas cannot live in it!", "They bathe in volcanic dust, not water.", "Cool dry mountains of the Andes", "Grass, seeds, and bark", "About as long as a squirrel", "Up to 80 hairs sprout from one follicle.", "Huge ears release heat.", "They jump six feet straight up.", "Night active to avoid heat and predators.", "Rocky Andean slopes give crevices and sparse plants.", "Dust baths keep fur clean and dry.", "Soft fur was overhunted historically."),
    ("long-nosed-bandicoot", "Long-nosed Bandicoot", "🐭", "Mammal", "Forest", "Bandicoots have rabbit-like back legs and pointy snouts!", "They dig cone-shaped holes looking for food.", "Forests and gardens in Australia", "Insects, worms, and roots", "About as long as a rabbit", "Pouch opens backward so dirt does not enter when digging.", "They are marsupials, not rodents.", "Short lives but fast breeding.", "Nocturnal snouts poke leaf litter at night.", "Australian bush soil is full of grubs.", "Clawed feet excavate soil rapidly.", "Compact bodies fit dense undergrowth."),
    ("southern-cuscus", "Southern Cuscus", "🐨", "Mammal", "Jungle", "Cuscuses are marsupials that climb slowly like sloths!", "Prehensile tails grip branches.", "Rainforests in New Guinea and Australia", "Leaves and fruit", "About as long as a cat", "Thick woolly fur can be spotted or plain.", "They move at night and rest by day.", "Opposable digits on hind feet help grip.", "Young ride on mothers' backs.", "Canopy leaves are their main food.", "Slow climbing saves energy.", "Rounded faces look bear-like."),
    ("pistol-shrimp", "Pistol Shrimp", "🦐", "Crustacean", "Ocean", "Pistol shrimp snap claws to make a bubble louder than a gunshot!", "The snap stuns prey with shock waves.", "Coral reefs and burrows worldwide", "Small fish and shrimp stunned by snaps", "About as long as your finger", "One claw is huge, the other small.", "Some share burrows with goby fish lookouts.", "Snapping claw cavitation heats water briefly.", "Burrows pile sand at reef edges.", "Reef crevices hide partners and prey.", "Shock waves knock prey senseless.", "Asymmetric claws are tools and weapons."),
    ("eastern-quoll", "Eastern Quoll", "🐱", "Mammal", "Forest", "Eastern quolls are spotted marsupial hunters!", "They are extinct in mainland Australia but survive in Tasmania.", "Tasmanian forests and farmlands", "Insects, mice, and carrion", "About as long as a cat", "Spots vary on creamy or dark fur.", "They carry young in a pouch facing backward.", "Quick runners chase prey at night.", "Scent marks outline territories.", "Cool island forests give prey and dens.", "Sharp teeth crunch beetles and small mammals.", "Slim bodies slip through grass."),
    ("sawfish", "Sawfish", "🐟", "Fish", "Ocean", "Sawfish rostrums are lined with teeth-like denticles!", "They are rays, not sharks.", "Shallow coastal waters and rivers in tropics", "Fish stunned or sliced by the saw", "Saw can be a third of body length", "Electrosensors on the saw find prey buried.", "They are critically endangered.", "Pups born with soft rostrums that harden.", "Saws may also dig in mud for food.", "Muddy estuaries hide fish they detect.", "Side-to-side swipes injure schooling fish.", "Flattened ray bodies hide on the bottom."),
    ("nurse-shark", "Nurse Shark", "🦈", "Fish", "Ocean", "Nurse sharks rest in piles on the seafloor!", "They suck prey like a vacuum cleaner.", "Warm shallow reefs and mangroves", "Shellfish, fish, and squid sucked from holes", "About as long as a couch", "Barbels by the mouth feel for food.", "Generally calm around divers if not harassed.", "Nocturnal feeding, daytime resting.", "Skin feels like sandpaper.", "Reef caves and ledges are daytime bedrooms.", "Strong suction pulls prey from crevices.", "Broad head and small mouth suit bottom feeding."),
    ("mahi-mahi", "Mahi-mahi", "🐟", "Fish", "Ocean", "Mahi-mahi flash brilliant green and gold then fade after death!", "Also called dolphinfish — not related to dolphins.", "Warm open oceans near floating debris", "Flying fish, squid, and smaller fish", "About as long as a tall person", "Males have square flat heads; females rounder.", "They grow extremely fast in warm water.", "They spawn often in open sea.", "Follow currents and floating weed lines.", "Open ocean surface holds prey near flotsam.", "Sharp teeth grip slippery fish.", "Laterally compressed bodies sprint in bursts."),
    ("leafy-sea-dragon", "Leafy Sea Dragon", "🐟", "Fish", "Ocean", "Leafy sea dragons look like drifting kelp leaves!", "They are relatives of seahorses.", "Southern Australian kelp forests", "Tiny crustaceans sucked into long snouts", "About as long as a forearm", "Leaf-like fins are only for camouflage.", "Males carry eggs on a tail patch.", "They drift slowly — no stomach, eat often.", "Protected by law in Australia.", "Kelp beds hide them from fish predators.", "Pipette mouth targets mysids.", "Fragile appendages sway like seaweed."),
    ("nudibranch", "Nudibranch", "🐚", "Mollusk", "Ocean", "Nudibranchs are sea slugs with wild colors and no shell!", "Some steal stinging cells from prey they eat.", "Coral reefs and rocky shores worldwide", "Sponges, anemones, and bryozoans", "From grain-sized to a foot long", "Gills look like feathery tufts on the back.", "Bright colors warn predators they may be toxic.", "They are hermaphrodites — both can lay eggs.", "Some swim by flexing the body.", "Reef rocks host sponges they graze.", "Toxic prey makes some species dangerous to eat.", "Soft bodies fit into reef holes."),
    ("sea-pen", "Sea Pen", "🦔", "Invertebrate", "Ocean", "Sea pens look like old quill pens rooted in sand!", "Colonies of polyps work together as one animal.", "Soft bottoms from shallow to deep sea", "Plankton caught by tentacles on each polyp", "From a few inches to over six feet tall", "They glow with bioluminescence in some species.", "Whole colony withdraws into sand when touched.", "Stem anchors in mud while top feeds in current.", "Some fish hide among the branches.", "Calm muddy floors let them stand upright.", "Polyps share nutrients inside the colony.", "Feathery shape catches drifting food."),
    ("ribbon-worm", "Ribbon Worm", "🐛", "Invertebrate", "Ocean", "Ribbon worms can shoot a sticky proboscis to catch prey!", "Some proboscises are longer than the worm body.", "Mud and sand under rocks and seaweed", "Worms, small animals, and sometimes each other", "From tiny threads to six feet long", "Bright colors warn or camouflage.", "They regenerate lost parts in some species.", "Proboscis may have poison in hunters.", "Slow crawling on slime trails.", "Intertidal zones under stones hide prey.", "Proboscis wraps prey like a lasso.", "Soft flat bodies slip into cracks."),
    ("cotton-top-tamarin", "Cotton-top Tamarin", "🐒", "Mammal", "Jungle", "Cotton-top tamarins have a white mohawk crest!", "They are critically endangered in Colombian forests.", "Rainforest edges in northwest Colombia", "Fruit, insects, and tree gum", "About as long as a squirrel", "Family groups share raising babies.", "More than 40 calls communicate moods.", "They leap over 10 feet between branches.", "Only dominant pair breeds often.", "Forest fragments give fruit and insects.", "Long claws dig for gum on bark.", "Light bodies race along thin twigs."),
    ("sloth-bear", "Sloth Bear", "🐻", "Mammal", "Jungle", "Sloth bears suck up termites like a vacuum!", "They carry cubs on their backs.", "Dry and wet forests of India and Sri Lanka", "Termites, ants, fruit, and honey", "About as tall as a waist at shoulder", "Long lips can close outside the nose while sucking insects.", "Curved claws rip open termite mounds.", "Shaggy fur hangs loosely.", "They snort and clack teeth when threatened.", "Forest clearings hold termite hills.", "Flexible lips funnel insects into the mouth.", "Sloped back and long claws suit digging."),
    ("sable", "Sable", "🐾", "Mammal", "Forest", "Sables are sleek martens prized for dark winter fur!", "They leap in trees hunting squirrels.", "Taiga forests across Russia and China", "Small mammals, birds, and berries", "About as long as a cat", "Dark coat lightens somewhat in summer.", "They mark trails with scent from anal glands.", "Excellent climbers with semi-retractable claws.", "Snow does not stick well to oily guard hairs.", "Cold conifer forests hide rodents under snow.", "Quick raids on nests and burrows.", "Long bushy tail wraps for warmth."),
    ("least-weasel", "Least Weasel", "🐾", "Mammal", "Grassland", "Least weasels are the smallest carnivores in the world!", "They can follow mice into burrows.", "Fields and meadows in the Northern Hemisphere", "Mice, voles, and small birds", "About as long as a hamster", "Brown in summer, white in snowy regions in winter.", "Long thin bodies fit mouse tunnels.", "High metabolism means they eat often.", "Females can have several litters yearly.", "Grasslands full of rodent tunnels.", "Bites to the head kill prey quickly.", "Short legs still run fast in open."),
    ("devil-ray", "Devil Ray", "🐟", "Fish", "Ocean", "Devil rays have horn-like head fins and leap from the sea!", "They filter feed like manta relatives.", "Warm oceans worldwide", "Plankton and small fish strained from water", "Wingspan wider than a door", "Cephalic fins curl into horn shapes.", "They sometimes jump completely out of water.", "Skin mucus may reduce parasites.", "Large brains for fish standards.", "Open sea plankton layers feed them.", "Gill rakers trap tiny food.", "Diamond-shaped bodies glide with wingbeats."),
    ("japanese-spider-crab", "Japanese Spider Crab", "🦀", "Crustacean", "Ocean", "Japanese spider crabs have the longest leg span of any crab!", "Legs can stretch wider than a car.", "Deep Pacific waters near Japan", "Dead animals, algae, and slow prey", "Body shell about as big as a dinner plate", "Legs grow back after molting if lost.", "They walk on stilt-like limbs.", "Gentle giants despite scary looks.", "Sponge and anemones sometimes grow on their shell.", "Deep rocky slopes give shelter.", "Long legs reach food far from the body.", "Knobby shell camouflages on rock."),
    ("bearded-dragon", "Bearded Dragon", "🦎", "Reptile", "Desert", "Bearded dragons puff a spiky throat beard when threatened!", "Popular pet lizards from Australia.", "Dry woodlands and deserts of Australia", "Insects, flowers, and leafy greens", "About as long as a forearm", "They wave one arm slowly to communicate.", "Beard turns black when upset.", "They bask under lamps or desert sun.", "Can run on hind legs briefly.", "Arid scrub gives insects and flowers.", "Sticky tongue grabs crickets.", "Spiky scales make them look tougher."),
    ("emerald-tree-boa", "Emerald Tree Boa", "🐍", "Reptile", "Jungle", "Emerald tree boas loop neon green coils on branches!", "Heat-sensing pits line the lips.", "Amazon rainforest canopy", "Birds and small mammals at night", "About as long as a child", "White markings look like lightning bolts.", "They bear live young instead of laying eggs.", "Hanging tails hook branches.", "Color helps hide among leaves.", "Rainforest treetops are hunting highways.", "Slow strikes grab warm-blooded prey.", "Prehensile tail acts as a fifth hand."),
    ("dall-sheep", "Dall Sheep", "🐏", "Mammal", "Arctic", "Dall sheep rams clash curly horns on mountain cliffs!", "White coats match snowy peaks.", "Alpine ranges of Alaska and western Canada", "Grasses and sedges on cliffs", "About as tall as a waist at shoulder", "Horns grow each summer, leaving rings.", "Ewes and lambs stay on safer ledges.", "Golden horns contrast snow.", "They use the same trails for generations.", "High rocky slopes avoid many predators.", "Sure hooves on edges that scare hikers.", "Thick winter coats shed in spring."),
    ("hamerkop", "Hamerkop", "🐦", "Bird", "Grassland", "Hamerkops build huge stick nests bigger than a person!", "They stamp their feet to stir up prey.", "Wetlands in sub-Saharan Africa", "Frogs, fish, and insects in shallow water", "About as long as a chicken", "Hammer-shaped head and crest give them their name.", "Nests can hold many unrelated birds roosting.", "They perform bowing displays.", "Brown plumage blends with mud.", "Marsh edges give shallow hunting.", "Quick jabs catch small water animals.", "Medium wading bird with long bill."),
    ("glow-worm", "Glow Worm", "🐛", "Insect", "Forest", "Glow worm larvae light up caves to attract flying prey!", "Only some stages glow — not always the adult.", "Caves and damp forests in Australia and New Zealand", "Flying insects caught in sticky snares", "Larva about as long as a matchstick", "Bioluminescence comes from a chemical reaction.", "Snares are sticky threads hung from cave ceilings.", "Adults may not feed at all in some species.", "Females look like larvae without wings.", "Dark wet habitats trap flying insects.", "Larvae reel in prey caught on silk.", "Soft glowing bodies dot cave roofs."),
    ("clown-knifefish", "Clown Knifefish", "🐟", "Fish", "Ocean", "Knifefish swim using a long fin under the body!", "They can move forward and backward easily.", "Slow rivers and lakes in Southeast Asia", "Small fish, insects, and crustaceans", "About as long as your arm", "Knife-shaped body is flat side to side.", "Weak electric sense helps in murky water.", "Popular in aquariums for odd looks.", "They are mostly nocturnal hunters.", "Warm still waters hide prey in plants.", "Large mouth creates suction feeding.", "Undulating fin ripples like a wave."),
    ("flying-gurnard", "Flying Gurnard", "🐟", "Fish", "Ocean", "Flying gurnards spread huge wing-like pectoral fins!", "They do not truly fly — fins startle predators.", "Sandy and muddy shores in warm seas", "Small crustaceans and fish on the bottom", "About as long as a dinner plate", "Bright fin spots flash when threatened.", "Armored heads crunch hard prey.", "They crawl on leg-like pelvic fins.", "Grunting sounds come from swim bladders.", "Shallow sandy bays hide shrimp.", "Spiny fins discourage bites.", "Wide fins look like a butterfly underwater."),
    ("viperfish", "Viperfish", "🐟", "Fish", "Ocean", "Viperfish have fangs so long they fold outside the head!", "Bioluminescent spots lure prey in the deep.", "Deep oceans worldwide", "Fish and squid attracted to light organs", "About as long as your forearm", "Hinged skull lets them swallow large prey.", "Dark silver bodies hide in black water.", "They rise nearer surface at night.", "Teeth are transparent in some species.", "Midnight zone food is scarce and scattered.", "Light organs dangle like fishing lures.", "Needle teeth impale fast-moving prey."),
    ("hoatzin", "Hoatzin", "🐦", "Bird", "Jungle", "Hoatzins digest leaves like cows and smell like fresh hay!", "Chicks have claws on their wings to climb trees.", "Swamps and river forests in the Amazon", "Leaves and tender plants", "About as long as a goose", "Punk crest and blue face make a wild look.", "They are poor fliers with small breast muscles.", "Bacteria in the crop ferment tough leaves.", "Nest over water may reduce predator raids.", "Riverine forests give leaves and branches.", "Crop fermentation takes time like a ruminant.", "Clawed wings help young escape water."),
    ("resplendent-quetzal", "Resplendent Quetzal", "🐦", "Bird", "Jungle", "Male quetzals have tail feathers longer than their body!", "Ancient Maya valued their green plumes.", "Cloud forests in Central America", "Wild avocados and other fruit", "Body about pigeon-sized; tail much longer", "Emerald green shines in forest light.", "They nest in rotting tree holes.", "Tail streamers curve in graceful arcs.", "Cannot survive without intact cloud forest.", "Mountain fruit trees feed breeding pairs.", "Swallow fruit whole and regurgitate pits.", "Lightweight bones help short flights between trees."),
    ("kea", "Kea", "🐦", "Bird", "Arctic", "Kea parrots are playful mountain birds of New Zealand!", "They pull rubber off cars and investigate everything.", "Alpine zones of New Zealand South Island", "Plants, berries, insects, and carrion", "About as long as a crow", "Orange underwing flashes in flight.", "They use tools and solve puzzles in studies.", "Snow does not stop their curiosity.", "Flocks socialize loudly.", "Alpine grasslands and ski areas bring food scraps.", "Strong beaks open tough skins and nuts.", "Rounded wings soar on mountain winds."),
    ("tamandua", "Tamandua", "🐜", "Mammal", "Jungle", "Tamanduas are tree anteaters with partial finger claws!", "They have a strong smell when threatened.", "Forests from Mexico to Brazil", "Ants and termites licked with a long tongue", "About as long as a large cat", "Prehensile tail grips branches.", "Coat can be blond, black, or mixed.", "They tear open nests with one clawed hand.", "Tongue flicks in and out up to 150 times a minute.", "Trees and ground both hold ant colonies.", "Sticky saliva traps thousands of ants.", "Furry tail acts as a blanket when sleeping."),
    ("cookiecutter-shark", "Cookiecutter Shark", "🦈", "Fish", "Ocean", "Cookiecutter sharks bite round plugs out of bigger animals!", "They glow with photophores except near one dark collar.", "Deep tropical oceans", "Flesh scooped from fish, whales, and sometimes submarines", "About as long as a shoe", "Teeth lock together like a cookie cutter.", "They rise from deep water at night.", "Small body but bold biting.", "Lips suction onto prey before the twist.", "Deep water hosts larger animals to nip.", "Scoop wounds heal on survivors over time.", "Cylindrical body suits vertical migration."),
    ("comb-jelly", "Comb Jelly", "Invertebrate", "Ocean", "Comb jellies rainbow-pulse rows of beating cilia!", "They are not true jellyfish — no stinging cells.", "Oceans from surface to deep water", "Plankton and small fish caught with sticky cells", "From marble-sized to several feet long", "Eight comb rows refract light into colors.", "Most are transparent and delicate.", "Some species eat other comb jellies.", "They are mostly carnivorous drifters.", "Open water drift brings plankton patches.", "Colloblast cells harpoon tiny prey.", "Soft gelatin bodies pulse through water."),
    ("hatchetfish", "Hatchetfish", "🐟", "Fish", "Ocean", "Hatchetfish have bellies that glow to hide their shadow!", "Knife-thin bodies live in the deep.", "Mid-depth oceans worldwide", "Plankton and small crustaceans", "About as long as your thumb", "Light organs on the belly match downwelling light.", "Huge eyes point upward for prey silhouettes.", "They migrate up at night to feed.", "Silver sides are mirrors in the dark.", "Twilight zone water hides them from below.", "Tiny mouths strain small food.", "Deep bodies look like hatchet blades."),
]

def build_animal(spec):
    base_keys = (
        "id",
        "name",
        "emoji",
        "type",
        "habitat",
        "funFact",
        "extraFact",
        "livesIn",
        "diet",
        "size",
    )
    d = dict(zip(base_keys, spec[:10]))
    extras = list(spec[10:17])
    while len(extras) < 7:
        extras.append(d["size"])
    fun2, fun3, dyk2, dyk3, live2, live3, size2 = extras[:7]
    diet2 = f"Food in {d['habitat'].lower()} areas matches what their bodies need."
    diet3 = f"Meal size changes as they grow from young to adult."
    size3 = size2
    return {
        "id": d["id"],
        "name": d["name"],
        "emoji": d["emoji"],
        "type": d["type"],
        "habitat": d["habitat"],
        "livesIn": d["livesIn"],
        "diet": d["diet"],
        "size": d["size"],
        "funFact": d["funFact"],
        "extraFact": d["extraFact"],
        "funFacts": [d["funFact"], fun2, fun3],
        "didYouKnowFacts": [d["extraFact"], dyk2, dyk3],
        "livesInFacts": [d["livesIn"], live2, live3],
        "dietFacts": [d["diet"], diet2, diet3],
        "sizeFacts": [d["size"], size2, size3],
    }


def main():
    animals = [build_animal(s) for s in SPECS[:99]]
    if len(animals) != 99:
        raise SystemExit(f"Expected 99 specs, got {len(animals)}")
    with OUT.open("w", encoding="utf-8") as f:
        for a in animals:
            f.write(json.dumps(a, ensure_ascii=False) + "\n")
    print(f"Wrote {len(animals)} animals to {OUT.name}")


if __name__ == "__main__":
    main()
