#!/usr/bin/env python3
"""Generate animals_99.jsonl for Wild Wonders encyclopedia."""
import json
from pathlib import Path

OUT = Path(__file__).parent / "animals_99.jsonl"

ANIMALS = [
    {"id": "cardinal", "name": "Cardinal", "emoji": "🐦", "type": "Bird", "habitat": "Forest",
     "livesIn": "North America — woods, gardens, and backyards", "diet": "Seeds, fruit, and insects",
     "size": "About as long as your hand", "funFact": "Male cardinals are bright red all year!",
     "extraFact": "Cardinals often visit bird feeders in winter.",
     "funFacts": ["Male cardinals are bright red all year!", "Females are brown with reddish wings and crest.", "They sing loud whistles from treetops."],
     "didYouKnowFacts": ["Cardinals do not migrate south for winter in many areas.", "A pair may stay together through several seasons.", "Their crest rises when they are excited or alert."],
     "livesInFacts": ["North America — woods, gardens, and backyards", "Thick bushes give cover from hawks and cats.", "They nest in shrubs and small trees."],
     "dietFacts": ["Seeds, fruit, and insects", "Strong beaks crack sunflower seeds easily.", "Parents feed insects to chicks for protein."],
     "sizeFacts": ["About as long as your hand", "They weigh less than a deck of cards.", "Short wings let them dart through branches."]},
    {"id": "great-blue-heron", "name": "Great Blue Heron", "emoji": "🦩", "type": "Bird", "habitat": "Ocean",
     "livesIn": "North America — marshes, lakes, and coasts", "diet": "Fish, frogs, and small animals",
     "size": "Taller than most kids — wings wider than you are tall", "funFact": "It freezes like a statue, then spears fish with its bill!",
     "extraFact": "Herons nest in groups called rookeries high in trees.",
     "funFacts": ["It freezes like a statue, then spears fish with its bill!", "Long legs let it wade in deep water.", "It flies with its neck folded in an S shape."],
     "didYouKnowFacts": ["One heron can eat hundreds of fish in a week.", "Young herons leave the nest at about two months old.", "Its wingspan can reach six feet."],
     "livesInFacts": ["North America — marshes, lakes, and coasts", "Shallow water is perfect for hunting.", "Rookeries are often on islands away from predators."],
     "dietFacts": ["Fish, frogs, and small animals", "It swallows prey whole, head first.", "Snakes and mice are caught on land too."],
     "sizeFacts": ["Taller than most kids — wings wider than you are tall", "Adults stand about four feet tall.", "Light hollow bones help them fly."]},
    {"id": "stork", "name": "Stork", "emoji": "🦩", "type": "Bird", "habitat": "Grassland",
     "livesIn": "Europe, Africa, and Asia — wetlands and fields", "diet": "Frogs, fish, insects, and small reptiles",
     "size": "About as tall as a nine-year-old", "funFact": "Storks clatter their huge bills to talk to each other!",
     "extraFact": "Many storks migrate thousands of miles each year.",
     "funFacts": ["Storks clatter their huge bills to talk to each other!", "They build huge stick nests on roofs and poles.", "Long legs help them stride through shallow water."],
     "didYouKnowFacts": ["White storks often return to the same nest every year.", "Parents take turns warming eggs.", "Baby storks beg loudly for food."],
     "livesInFacts": ["Europe, Africa, and Asia — wetlands and fields", "Open fields let them spot prey while walking.", "Nests on high places stay safer from foxes."],
     "dietFacts": ["Frogs, fish, insects, and small reptiles", "They stab prey quickly with a sharp bill.", "Parents carry food in their throat pouch for chicks."],
     "sizeFacts": ["About as tall as a nine-year-old", "Wings can span more than six feet.", "Bills are long and straight for spearing."]},
    {"id": "sandhill-crane", "name": "Sandhill Crane", "emoji": "🦩", "type": "Bird", "habitat": "Grassland",
     "livesIn": "North America — prairies, marshes, and fields", "diet": "Grains, seeds, insects, and small animals",
     "size": "About as tall as a grown-up's chest", "funFact": "Sandhill cranes dance by leaping, bowing, and flapping!",
     "extraFact": "Their loud trumpeting calls carry for miles.",
     "funFacts": ["Sandhill cranes dance by leaping, bowing, and flapping!", "They fly in long V-shaped flocks during migration.", "A red patch of skin sits on their forehead."],
     "didYouKnowFacts": ["Some sandhill cranes live more than 20 years.", "Pairs often stay together for life.", "They sleep standing in shallow water for safety."],
     "livesInFacts": ["North America — prairies, marshes, and fields", "Wet meadows give food and safe roosting.", "Huge flocks gather at migration stopover sites."],
     "dietFacts": ["Grains, seeds, insects, and small animals", "They probe mud with their bill for roots.", "Corn fields are favorite feeding spots in fall."],
     "sizeFacts": ["About as tall as a grown-up's chest", "Wingspan can reach seven feet.", "Long necks help them reach food in water."]},
    {"id": "hoopoe", "name": "Hoopoe", "emoji": "🐦", "type": "Bird", "habitat": "Grassland",
     "livesIn": "Europe, Africa, and Asia — parks, savannas, and gardens", "diet": "Insects, worms, and small reptiles",
     "size": "About as long as a school ruler", "funFact": "Hoopoes raise a fan-shaped crest on their head!",
     "extraFact": "Nestlings can squirt smelly liquid at predators.",
     "funFacts": ["Hoopoes raise a fan-shaped crest on their head!", "Their bill is long and curved for probing soil.", "Wings show bold black-and-white bars in flight."],
     "didYouKnowFacts": ["Hoopoes nest in holes in trees or walls.", "Parents feed chicks inside the nest for weeks.", "Their name comes from the sound 'hoop-hoop'."],
     "livesInFacts": ["Europe, Africa, and Asia — parks, savannas, and gardens", "Short grass makes it easy to find bugs.", "They often perch on fences while hunting."],
     "dietFacts": ["Insects, worms, and small reptiles", "They flick leaves aside with their bill.", "Larvae and beetles are favorite meals."],
     "sizeFacts": ["About as long as a school ruler", "Crest feathers can stand tall or lie flat.", "They have a light, floppy flight style."]},
    {"id": "magpie", "name": "Magpie", "emoji": "🐦", "type": "Bird", "habitat": "Forest",
     "livesIn": "Europe, Asia, and western North America — open woods and towns", "diet": "Insects, fruit, seeds, eggs, and scraps",
     "size": "About as long as a football", "funFact": "Magpies are among the smartest birds and can solve puzzles!",
     "extraFact": "Their feathers shine green and blue in sunlight.",
     "funFacts": ["Magpies are among the smartest birds and can solve puzzles!", "They hop and walk on the ground while searching for food.", "Long tails help them steer in quick flights."],
     "didYouKnowFacts": ["Magpies sometimes hide shiny objects they find.", "They warn the flock with sharp alarm calls.", "Large domed nests are built high in trees."],
     "livesInFacts": ["Europe, Asia, and western North America — open woods and towns", "Parks and farms offer plenty of food.", "They adapt well near human homes."],
     "dietFacts": ["Insects, fruit, seeds, eggs, and scraps", "They eat carrion and leftover picnic food too.", "Young birds need lots of protein from bugs."],
     "sizeFacts": ["About as long as a football", "Black-and-white pattern is easy to spot.", "Tail can be half their total length."]},
    {"id": "raven", "name": "Raven", "emoji": "🐦‍⬛", "type": "Bird", "habitat": "Forest",
     "livesIn": "Northern forests, mountains, and coasts worldwide", "diet": "Carrion, small animals, eggs, seeds, and berries",
     "size": "Wings wider than your arms stretched out", "funFact": "Ravens can mimic sounds, including human words!",
     "extraFact": "They play by sliding down snowbanks on their backs.",
     "funFacts": ["Ravens can mimic sounds, including human words!", "They soar on thermals like hawks.", "Thick bills can crack hard nuts and bones."],
     "didYouKnowFacts": ["Ravens mate for life and defend a territory.", "They use tools, like sticks, to reach food.", "Wedge-shaped tails help tell them from crows."],
     "livesInFacts": ["Northern forests, mountains, and coasts worldwide", "Cliffs and tall trees are favorite nest sites.", "They thrive in cold, wild places."],
     "dietFacts": ["Carrion, small animals, eggs, seeds, and berries", "Wolves may follow ravens to find carcasses.", "They hide extra food for later meals."],
     "sizeFacts": ["Wings wider than your arms stretched out", "Ravens are much bigger than common crows.", "Shaggy throat feathers puff out when calling."]},
    {"id": "jackdaw", "name": "Jackdaw", "emoji": "🐦‍⬛", "type": "Bird", "habitat": "Farm",
     "livesIn": "Europe and western Asia — towns, farms, and cliffs", "diet": "Insects, seeds, scraps, and small animals",
     "size": "Smaller than a crow — about two hands long", "funFact": "Jackdaws have pale gray eyes that look almost white!",
     "extraFact": "They nest in chimneys, towers, and cliff holes.",
     "funFacts": ["Jackdaws have pale gray eyes that look almost white!", "They fly in tight flocks over fields.", "A silver-gray patch covers the back of their head."],
     "didYouKnowFacts": ["Jackdaws pair up and stay close all year.", "They pick up and play with small objects.", "Chicks hatch blind and naked."],
     "livesInFacts": ["Europe and western Asia — towns, farms, and cliffs", "Church steeples are classic nesting spots.", "Open farmland gives easy insect hunting."],
     "dietFacts": ["Insects, seeds, scraps, and small animals", "They follow plows to catch worms turned up.", "Parents feed chicks many times each hour."],
     "sizeFacts": ["Smaller than a crow — about two hands long", "Compact body fits into narrow nest holes.", "Quick wingbeats keep them agile in towns."]},
    {"id": "storm-petrel", "name": "Storm Petrel", "emoji": "🐦", "type": "Bird", "habitat": "Ocean",
     "livesIn": "Open oceans — comes to rocky islands only to nest", "diet": "Tiny fish, plankton, and squid caught at sea",
     "size": "About as small as your palm", "funFact": "Storm petrels 'walk' on the waves by patting the water with their feet!",
     "extraFact": "They return to the same burrow nest year after year.",
     "funFacts": ["Storm petrels 'walk' on the waves by patting the water with their feet!", "They fly low over the sea even in rough weather.", "Most of their life is spent far from land."],
     "didYouKnowFacts": ["They nest in underground burrows on islands.", "Oil from their stomach helps feed the chick.", "Sailors once called them 'Mother Carey's chickens.'"],
     "livesInFacts": ["Open oceans — comes to rocky islands only to nest", "Dark nights hide them from gulls near colonies.", "Islands free of rats are safer for nesting."],
     "dietFacts": ["Tiny fish, plankton, and squid caught at sea", "They dip their bill to grab food from the surface.", "Strong smell of fish oil marks their burrows."],
     "sizeFacts": ["About as small as your palm", "Lightweight body rides on ocean winds.", "Wings flutter quickly like a bat."]},
    {"id": "cormorant", "name": "Cormorant", "emoji": "🐦", "type": "Bird", "habitat": "Ocean",
     "livesIn": "Coasts and lakes worldwide — perches on rocks and docks", "diet": "Fish caught underwater",
     "size": "About as long as your arm", "funFact": "Cormorants dive deep and chase fish with their feet!",
     "extraFact": "Their feathers soak up water, so they must dry their wings in the sun.",
     "funFacts": ["Cormorants dive deep and chase fish with their feet!", "They swallow fish whole, head first.", "Webbed feet work like flippers underwater."],
     "didYouKnowFacts": ["Some fishermen once used trained cormorants to catch fish.", "They often spread wings wide to dry after diving.", "Colonies can smell strongly of fish."],
     "livesInFacts": ["Coasts and lakes worldwide — perches on rocks and docks", "Cliffs and trees hold messy stick nests.", "Calm bays make hunting easier."],
     "dietFacts": ["Fish caught underwater", "A hooked tip on the upper bill grips slippery fish.", "They may hunt in groups, herding fish together."],
     "sizeFacts": ["About as long as your arm", "Long neck and snake-like head help them strike.", "They can stay underwater for over a minute."]},
    {"id": "grebe", "name": "Grebe", "emoji": "🦆", "type": "Bird", "habitat": "Ocean",
     "livesIn": "Lakes and ponds in North America, Europe, and beyond", "diet": "Fish, insects, and small water animals",
     "size": "About as long as a loaf of bread", "funFact": "Grebe chicks ride on a parent's back like a boat!",
     "extraFact": "Grebes run on water to take off because their legs sit far back.",
     "funFacts": ["Grebe chicks ride on a parent's back like a boat!", "They dive straight down instead of flying up first.", "Feet have lobed toes, not full webbing."],
     "didYouKnowFacts": ["Grebes eat their own feathers to line the stomach.", "Courtship includes weed-dancing and head shaking.", "They build floating nests anchored to plants."],
     "livesInFacts": ["Lakes and ponds in North America, Europe, and beyond", "Reeds hide nests from predators.", "They need open water for running takeoffs."],
     "dietFacts": ["Fish, insects, and small water animals", "Chicks swallow feathers fed by parents.", "They spear prey with a sharp bill."],
     "sizeFacts": ["About as long as a loaf of bread", "Legs set far back make walking on land awkward.", "Compact body is built for diving."]},
    {"id": "white-ibis", "name": "White Ibis", "emoji": "🦩", "type": "Bird", "habitat": "Ocean",
     "livesIn": "Southeastern United States — marshes, lawns, and parks", "diet": "Insects, crayfish, frogs, and small fish",
     "size": "About as tall as your knee", "funFact": "White ibises probe mud with a long curved bill!",
     "extraFact": "Bright red legs and face show up in breeding season.",
     "funFacts": ["White ibises probe mud with a long curved bill!", "Juveniles are brown and white speckled.", "They fly in lines or V shapes with necks outstretched."],
     "didYouKnowFacts": ["Flocks follow lawn mowers to catch stirred-up bugs.", "They nest in trees near water in colonies.", "Rainy weather brings worms to the surface for easy meals."],
     "livesInFacts": ["Southeastern United States — marshes, lawns, and parks", "Shallow wetlands are main feeding grounds.", "Urban parks are common now in Florida."],
     "dietFacts": ["Insects, crayfish, frogs, and small fish", "Sensitive bill tip feels prey in mud.", "Parents regurgitate food for chicks."],
     "sizeFacts": ["About as tall as your knee", "Wings show black tips in flight.", "Curved bill is perfect for probing."]},
    {"id": "roseate-spoonbill", "name": "Roseate Spoonbill", "emoji": "🦩", "type": "Bird", "habitat": "Ocean",
     "livesIn": "Southern United States and South America — coastal marshes", "diet": "Small fish, shrimp, insects, and plants filtered from water",
     "size": "About as tall as a third-grader", "funFact": "Its spoon-shaped bill sweeps side to side in shallow water!",
     "extraFact": "Pink color comes from the crustaceans they eat.",
     "funFacts": ["Its spoon-shaped bill sweeps side to side in shallow water!", "Bright pink feathers stand out in green marshes.", "They often feed in groups with other wading birds."],
     "didYouKnowFacts": ["Young spoonbills hatch white and turn pink later.", "They nest in mangrove trees over water.", "Plume hunting once nearly wiped them out."],
     "livesInFacts": ["Southern United States and South America — coastal marshes", "Muddy flats are full of tiny prey.", "Mangroves protect nests from raccoons."],
     "dietFacts": ["Small fish, shrimp, insects, and plants filtered from water", "Bill sensors feel prey when water drains out.", "Carotenoids in shrimp make feathers pink."],
     "sizeFacts": ["About as tall as a third-grader", "Wingspan can reach five feet.", "Flat spoon bill is unlike any heron's beak."]},
    {"id": "groundhog", "name": "Groundhog", "emoji": "🦫", "type": "Mammal", "habitat": "Grassland",
     "livesIn": "Eastern North America — meadows and forest edges", "diet": "Grass, clover, berries, and garden plants",
     "size": "About as heavy as a large watermelon", "funFact": "Groundhogs dig burrows with separate rooms for sleeping and bathroom!",
     "extraFact": "They hibernate all winter in a deep sleep underground.",
     "funFacts": ["Groundhogs dig burrows with separate rooms for sleeping and bathroom!", "They stand on hind legs to watch for danger.", "Teeth keep growing and must be worn down by chewing."],
     "didYouKnowFacts": ["A groundhog burrow can be 30 feet long with many exits.", "They are also called woodchucks.", "In spring they lose half their body weight from hibernation."],
     "livesInFacts": ["Eastern North America — meadows and forest edges", "Burrow entrances are often under fence lines.", "Loose soil near fields is easy to dig."],
     "dietFacts": ["Grass, clover, berries, and garden plants", "They eat heavily in late summer to store fat.", "Farmers sometimes find them in vegetable patches."],
     "sizeFacts": ["About as heavy as a large watermelon", "Stocky body is built for digging.", "Short legs power strong claws through dirt."]},
    {"id": "yellow-bellied-marmot", "name": "Yellow-Bellied Marmot", "emoji": "🦫", "type": "Mammal", "habitat": "Grassland",
     "livesIn": "Western North America — rocky mountain meadows", "diet": "Grasses, flowers, and herbs",
     "size": "About as long as a house cat", "funFact": "Marmots whistle loudly to warn the colony of eagles!",
     "extraFact": "They sunbathe on rocks for hours each morning.",
     "funFacts": ["Marmots whistle loudly to warn the colony of eagles!", "They live in family groups in rocky burrows.", "Fat builds up all summer for long winter sleep."],
     "didYouKnowFacts": ["Marmots can spend eight months hibernating underground.", "Colonies share lookout duties on tall rocks.", "Their belly fur is yellowish, giving them their name."],
     "livesInFacts": ["Western North America — rocky mountain meadows", "Boulders give sunning spots and quick escape holes.", "Alpine meadows bloom with their favorite plants."],
     "dietFacts": ["Grasses, flowers, and herbs", "They graze in morning and evening to avoid heat.", "Late-season eating packs on winter fat."],
     "sizeFacts": ["About as long as a house cat", "Chunky body stores energy for hibernation.", "Short ears reduce heat loss in cold mountains."]},
    {"id": "american-pika", "name": "American Pika", "emoji": "🐭", "type": "Mammal", "habitat": "Arctic",
     "livesIn": "High rocky mountains in western North America", "diet": "Grass, wildflowers, and soft plants",
     "size": "About as big as a tennis ball", "funFact": "Pikas gather hay piles bigger than themselves for winter!",
     "extraFact": "They do not hibernate — they eat stored plants under the snow.",
     "funFacts": ["Pikas gather hay piles bigger than themselves for winter!", "They bark 'eep' when a hawk flies overhead.", "Round ears and no tail help them stay warm."],
     "didYouKnowFacts": ["Pikas are related to rabbits, not mice.", "They dry plants in the sun before storing them.", "Climate warming threatens their cool mountain homes."],
     "livesInFacts": ["High rocky mountains in western North America", "Talus slopes of broken rock hide their dens.", "Cool air flows through rock piles in summer."],
     "dietFacts": ["Grass, wildflowers, and soft plants", "Hay piles must last through months of snow.", "They also eat lichens and moss in lean times."],
     "sizeFacts": ["About as big as a tennis ball", "Thick fur keeps them warm above the tree line.", "Small size lets them slip between rocks quickly."]},
    {"id": "black-tailed-prairie-dog", "name": "Black-Tailed Prairie Dog", "emoji": "🐿️", "type": "Mammal", "habitat": "Grassland",
     "livesIn": "Great Plains of North America — shortgrass prairie", "diet": "Grass, seeds, and leafy plants",
     "size": "About as long as a shoe", "funFact": "Prairie dogs jump-yip to celebrate when danger is gone!",
     "extraFact": "Their towns can cover hundreds of acres underground.",
     "funFacts": ["Prairie dogs jump-yip to celebrate when danger is gone!", "They kiss by touching teeth to recognize friends.", "Burrows have listening posts near the surface."],
     "didYouKnowFacts": ["Different barks warn about hawks, humans, or snakes.", "Owls and ferrets sometimes share their burrows.", "Colonies once numbered in the millions on the plains."],
     "livesInFacts": ["Great Plains of North America — shortgrass prairie", "Short grass lets them see predators far away.", "Underground tunnels link many family groups."],
     "dietFacts": ["Grass, seeds, and leafy plants", "Clipping grass keeps plants tender and green.", "They drink very little water from plants alone."],
     "sizeFacts": ["About as long as a shoe", "Black tail tip is easy to spot when they stand.", "Strong claws dig tunnels in hard prairie soil."]},
    {"id": "common-shrew", "name": "Common Shrew", "emoji": "🐭", "type": "Mammal", "habitat": "Forest",
     "livesIn": "Europe and Asia — leaf litter, gardens, and hedgerows", "diet": "Insects, worms, and spiders",
     "size": "Smaller than your thumb — one of the tiniest mammals", "funFact": "A shrew must eat every few hours or it starves!",
     "extraFact": "Their heart beats hundreds of times per minute.",
     "funFacts": ["A shrew must eat every few hours or it starves!", "Pointed snout wiggles constantly while hunting.", "They use echo-like clicks to explore dark tunnels."],
     "didYouKnowFacts": ["Shrew saliva can paralyze small prey.", "They are not rodents — they are insect-eating relatives of moles.", "Many shrews live only about one year."],
     "livesInFacts": ["Europe and Asia — leaf litter, gardens, and hedgerows", "Logs and stones hide runways underneath.", "They tunnel through moss and loose soil."],
     "dietFacts": ["Insects, worms, and spiders", "High metabolism needs more than their own weight in food daily.", "They cache live insects for emergency snacks."],
     "sizeFacts": ["Smaller than your thumb — one of the tiniest mammals", "Velvety fur is brown on top and pale below.", "Tiny eyes mean they hunt mostly by smell and touch."]},
    {"id": "muskrat", "name": "Muskrat", "emoji": "🦫", "type": "Mammal", "habitat": "Ocean",
     "livesIn": "North America wetlands — marshes, ponds, and slow rivers", "diet": "Cattails, roots, and aquatic plants",
     "size": "About as long as a small backpack", "funFact": "Muskrats build dome lodges from plants in the middle of ponds!",
     "extraFact": "Their tail is flat like a paddle for swimming.",
     "funFacts": ["Muskrats build dome lodges from plants in the middle of ponds!", "They can stay underwater several minutes.", "Whiskers help them find food in murky water."],
     "didYouKnowFacts": ["Muskrats are not rats — they are large wetland rodents.", "They mark trails with scented oil from glands.", "Owls and mink hunt them at night."],
     "livesInFacts": ["North America wetlands — marshes, ponds, and slow rivers", "Bank burrows have underwater entrances.", "Ice on ponds still lets them swim below."],
     "dietFacts": ["Cattails, roots, and aquatic plants", "They also eat clams and frogs sometimes.", "Winter food is stored in the lodge."],
     "sizeFacts": ["About as long as a small backpack", "Webbed hind feet power swimming.", "Dense fur traps air for warmth in cold water."]},
    {"id": "saiga", "name": "Saiga", "emoji": "🦌", "type": "Mammal", "habitat": "Grassland",
     "livesIn": "Central Asian steppes — dry grasslands and deserts", "diet": "Grasses, herbs, and lichens",
     "size": "About as tall as a pony at the shoulder", "funFact": "Saigas have a huge droopy nose that filters dusty air!",
     "extraFact": "Males carry twisted horns used in shoving matches.",
     "funFacts": ["Saigas have a huge droopy nose that filters dusty air!", "Herds migrate long distances to find fresh grass.", "Their coat changes color between summer and winter."],
     "didYouKnowFacts": ["Saiga populations crashed but are slowly recovering.", "Twins are common among saiga calves.", "The nose warms cold winter air before it reaches the lungs."],
     "livesInFacts": ["Central Asian steppes — dry grasslands and deserts", "Open plains let them spot wolves from far away.", "They cross borders in huge seasonal herds."],
     "dietFacts": ["Grasses, herbs, and lichens", "They can eat plants that are too salty for other grazers.", "Snow is scraped away with hooves to reach dry grass."],
     "sizeFacts": ["About as tall as a pony at the shoulder", "Bulbous nose is unique among antelopes.", "Stocky body handles harsh winds and cold."]},
    {"id": "takin", "name": "Takin", "emoji": "🐐", "type": "Mammal", "habitat": "Forest",
     "livesIn": "Himalayan mountains — bamboo forests and cliffs", "diet": "Leaves, bark, and bamboo",
     "size": "As heavy as a large adult human", "funFact": "The takin is Bhutan's national animal and climbs steep cliffs!",
     "extraFact": "Their oily coat smells a bit like horse and musk.",
     "funFacts": ["The takin is Bhutan's national animal and climbs steep cliffs!", "Horns curve back along a big shaggy head.", "Herds move to lower forests in winter."],
     "didYouKnowFacts": ["Takins are related to goats and sheep.", "Snow leopards are their main mountain predator.", "They wallow in mud to cool off in summer."],
     "livesInFacts": ["Himalayan mountains — bamboo forests and cliffs", "Thick fur protects them from freezing winds.", "Steep terrain keeps them away from many hunters."],
     "dietFacts": ["Leaves, bark, and bamboo", "Powerful lips strip leaves from twigs.", "They browse standing on hind legs for high branches."],
     "sizeFacts": ["As heavy as a large adult human", "Golden face and dark legs stand out.", "Hooves grip rocky trails like mountain boots."]},
    {"id": "babirusa", "name": "Babirusa", "emoji": "🐗", "type": "Mammal", "habitat": "Jungle",
     "livesIn": "Indonesian islands — tropical forests and riverbanks", "diet": "Fruit, leaves, roots, and small animals",
     "size": "About as long as a big dog", "funFact": "Male babirusas have tusks that curve up through the snout!",
     "extraFact": "They wallow in mud to cool off and remove parasites.",
     "funFacts": ["Male babirusas have tusks that curve up through the snout!", "They are also called deer-pigs.", "Long legs help them run through swampy forest."],
     "didYouKnowFacts": ["Upper tusks can grow so long they risk piercing the skull.", "They eat fallen fruit that helps spread jungle seeds.", "Sows leave the group to raise piglets alone."],
     "livesInFacts": ["Indonesian islands — tropical forests and riverbanks", "Mud wallows are social meeting spots.", "River edges give drinking water and soft ground."],
     "dietFacts": ["Fruit, leaves, roots, and small animals", "Tusks are used in fights more than for feeding.", "They root in soil like pigs for tasty tubers."],
     "sizeFacts": ["About as long as a big dog", "Sparse hair shows grayish skin.", "Curved lower tusks stick out from the jaw."]},
    {"id": "pygmy-marmoset", "name": "Pygmy Marmoset", "emoji": "🐒", "type": "Mammal", "habitat": "Jungle",
     "livesIn": "Amazon rainforest — treetops along rivers", "diet": "Tree gum, sap, insects, and fruit",
     "size": "Smaller than a hamster — world's tiniest monkey", "funFact": "Pygmy marmosets gnaw holes in bark to sip sticky tree gum!",
     "extraFact": "A whole family group may weigh less than one apple.",
     "funFacts": ["Pygmy marmosets gnaw holes in bark to sip sticky tree gum!", "They leap between thin branches like squirrels.", "Claws help them cling while feeding upright."],
     "didYouKnowFacts": ["Twins are the usual birth for this species.", "Only the dominant female usually has babies.", "Their tail is longer than their body."],
     "livesInFacts": ["Amazon rainforest — treetops along rivers", "River-edge trees have gum they love.", "Dense vines give highways through the canopy."],
     "dietFacts": ["Tree gum, sap, insects, and fruit", "Gum holes are defended from other marmosets.", "Insects add protein between sap meals."],
     "sizeFacts": ["Smaller than a hamster — world's tiniest monkey", "Striped tail helps group members follow each other.", "Fur is mixed brown, yellow, and gray."]},
    {"id": "gray-langur", "name": "Gray Langur", "emoji": "🐒", "type": "Mammal", "habitat": "Jungle",
     "livesIn": "India and South Asia — forests, temples, and towns", "diet": "Leaves, fruit, flowers, and seeds",
     "size": "Body about as long as a toddler", "funFact": "Gray langurs leap 10 feet between branches with their long tails!",
     "extraFact": "They are also called Hanuman langurs after a monkey god.",
     "funFacts": ["Gray langurs leap 10 feet between branches with their long tails!", "Black faces and silver-gray fur are easy to recognize.", "Troops include many females and one dominant male."],
     "didYouKnowFacts": ["Langurs warn troops with loud barks when leopards appear.", "Babies are bright orange at first, then turn gray.", "They sometimes live near humans in cities and temples."],
     "livesInFacts": ["India and South Asia — forests, temples, and towns", "Tall trees are sleeping and escape platforms.", "Sacred status in some places protects them."],
     "dietFacts": ["Leaves, fruit, flowers, and seeds", "Leaf-heavy diets need a special stomach to digest.", "They raid crops when forest food is scarce."],
     "sizeFacts": ["Body about as long as a toddler", "Tail can be longer than the body for balance.", "Long limbs are built for climbing, not running on ground."]},
    {"id": "fossa", "name": "Fossa", "emoji": "🐆", "type": "Mammal", "habitat": "Jungle",
     "livesIn": "Madagascar — rainforests and dry forest", "diet": "Lemurs, birds, and small animals",
     "size": "About as long as a medium dog", "funFact": "The fossa is Madagascar's top predator and climbs trees like a cat!",
     "extraFact": "Its ankle can rotate so it can climb down trunks headfirst.",
     "funFacts": ["The fossa is Madagascar's top predator and climbs trees like a cat!", "A long tail helps balance on branches.", "It looks part cat, part mongoose, but is its own family."],
     "didYouKnowFacts": ["Fossas hunt mostly at night.", "Scent glands mark territory on trees.", "They mate in trees on a brief seasonal visit."],
     "livesInFacts": ["Madagascar — rainforests and dry forest", "Only found on this island, nowhere else wild.", "Tree lemurs are main prey in the canopy."],
     "dietFacts": ["Lemurs, birds, and small animals", "Sharp claws and teeth grab agile lemurs.", "They also eat lizards and wild pigs sometimes."],
     "sizeFacts": ["About as long as a medium dog", "Muscular hind legs power long leaps.", "Short reddish-brown coat blends with forest shadows."]},
    {"id": "small-spotted-genet", "name": "Small-Spotted Genet", "emoji": "🐱", "type": "Mammal", "habitat": "Forest",
     "livesIn": "Africa and southern Europe — woods, scrub, and farms", "diet": "Rodents, birds, insects, and fruit",
     "size": "About as long as a house cat", "funFact": "Genets have spotted fur and a ringed tail like a mini leopard!",
     "extraFact": "They can squeeze their flexible body through tight gaps.",
     "funFacts": ["Genets have spotted fur and a ringed tail like a mini leopard!", "They climb trees and hunt on the ground.", "Large ears swivel toward the tiniest rustle."],
     "didYouKnowFacts": ["Genets scent-mark with a gland under the tail.", "They are active at dusk and dawn.", "They arch their backs when threatened."],
     "livesInFacts": ["Africa and southern Europe — woods, scrub, and farms", "Stone walls and barns are hiding spots.", "They rest in tree hollows during the day."],
     "dietFacts": ["Rodents, birds, insects, and fruit", "Quick pounces catch mice in grass.", "Seasonal fruit supplements their meat diet."],
     "sizeFacts": ["About as long as a house cat", "Spots and stripes break up their outline.", "Retractable claws help them climb bark."]},
    {"id": "margay", "name": "Margay", "emoji": "🐆", "type": "Mammal", "habitat": "Jungle",
     "livesIn": "Central and South American rainforests", "diet": "Small monkeys, birds, squirrels, and fruit",
     "size": "About as long as a house cat", "funFact": "Margays can twist their ankles to climb down trees headfirst!",
     "extraFact": "They copy baby monkey calls to lure prey closer.",
     "funFacts": ["Margays can twist their ankles to climb down trees headfirst!", "Huge eyes help them hunt in moonlight.", "Spotted coat looks like a clouded leopard in miniature."],
     "didYouKnowFacts": ["Margays are among the best tree-climbing cats.", "They sometimes hunt on the ground after rain.", "Kittens learn to climb before they are fully grown."],
     "livesInFacts": ["Central and South American rainforests", "Dense canopy is their main highway.", "They need large forest patches to survive."],
     "dietFacts": ["Small monkeys, birds, squirrels, and fruit", "One leap can land on a bird in mid-flight.", "Agile paws grab squirrels on thin branches."],
     "sizeFacts": ["About as long as a house cat", "Long tail is half their length for balance.", "Lightweight body suits life high in trees."]},
    {"id": "spectacled-bear", "name": "Spectacled Bear", "emoji": "🐻", "type": "Mammal", "habitat": "Jungle",
     "livesIn": "Andes mountains — cloud forests from Venezuela to Bolivia", "diet": "Fruit, bromeliads, insects, and small animals",
     "size": "Smaller than a grizzly — about as tall as a big dog standing", "funFact": "Spectacled bears are South America's only wild bears!",
     "extraFact": "Light fur rings around the eyes look like glasses.",
     "funFacts": ["Spectacled bears are South America's only wild bears!", "They build leafy platforms in trees to reach fruit.", "Long claws help them climb and tear apart logs."],
     "didYouKnowFacts": ["They eat huge amounts of bromeliad plants.", "Cubs stay with their mother for over a year.", "Farmers sometimes find them in corn fields."],
     "livesInFacts": ["Andes mountains — cloud forests from Venezuela to Bolivia", "Foggy forests are full of fruit and flowers.", "They sleep in tree nests or cliff caves."],
     "dietFacts": ["Fruit, bromeliads, insects, and small animals", "Only about 5% of their diet is meat.", "Hard palm nuts are cracked with strong jaws."],
     "sizeFacts": ["Smaller than a grizzly — about as tall as a big dog standing", "Shaggy black fur sheds rain in the clouds.", "They are the most vegetarian of all bears."]},
    {"id": "wolverine", "name": "Wolverine", "emoji": "🦡", "type": "Mammal", "habitat": "Arctic",
     "livesIn": "Northern forests and tundra — North America, Europe, Asia", "diet": "Carrion, rodents, berries, and prey they hunt",
     "size": "About as heavy as a medium dog", "funFact": "Wolverines travel huge distances and can fight off bears for food!",
     "extraFact": "Their fur resists frost so snow does not stick to it.",
     "funFacts": ["Wolverines travel huge distances and can fight off bears for food!", "Strong jaws can crush frozen bones.", "Broad paws work like snowshoes in deep powder."],
     "didYouKnowFacts": ["They store food in snow refrigerators for later.", "A wolverine's scientific name means 'glutton.'", "They are rare and hard to spot in the wild."],
     "livesInFacts": ["Northern forests and tundra — North America, Europe, Asia", "Huge home ranges cross mountains and valleys.", "Deep snow does not stop their winter travel."],
     "dietFacts": ["Carrion, rodents, berries, and prey they hunt", "They follow wolves to leftover kills.", "Hooves and antlers are chewed for marrow."],
     "sizeFacts": ["About as heavy as a medium dog", "Low-slung body is built for endurance, not speed.", "A bushy tail adds balance on rocky slopes."]},
    {"id": "american-mink", "name": "American Mink", "emoji": "🦦", "type": "Mammal", "habitat": "Forest",
     "livesIn": "North America — streams, lakes, and wetlands", "diet": "Fish, frogs, crayfish, and small mammals",
     "size": "About as long as a ruler", "funFact": "Minks swim underwater and can catch fish bigger than their head!",
     "extraFact": "Their dark fur was once prized for coats.",
     "funFacts": ["Minks swim underwater and can catch fish bigger than their head!", "They slip into burrows to grab rabbits or muskrats.", "Whiskers sense prey in muddy water."],
     "didYouKnowFacts": ["Minks stash extra food in their den.", "They can spray a stinky musk like skunks.", "Farm-raised mink are different from wild ones."],
     "livesInFacts": ["North America — streams, lakes, and wetlands", "Bank dens have underwater doorways.", "Ice does not stop them from diving below."],
     "dietFacts": ["Fish, frogs, crayfish, and small mammals", "Quick bites behind the head kill prey fast.", "They hunt more in dawn and dusk."],
     "sizeFacts": ["About as long as a ruler", "Sleek body slips through narrow tunnels.", "Partially webbed feet push through currents."]},
    {"id": "harbor-porpoise", "name": "Harbor Porpoise", "emoji": "🐬", "type": "Mammal", "habitat": "Ocean",
     "livesIn": "Cool coastal waters of the North Atlantic and Pacific", "diet": "Small fish and squid",
     "size": "About as long as a grown-up is tall", "funFact": "Harbor porpoises are shy and rarely leap out of the water!",
     "extraFact": "They are among the smallest ocean dolphins.",
     "funFacts": ["Harbor porpoises are shy and rarely leap out of the water!", "Triangular dorsal fin is small and curved.", "They click quietly to find fish in murky bays."],
     "didYouKnowFacts": ["Fishing nets accidentally trap many porpoises.", "Calves are born tail-first in the water.", "They must surface every few minutes to breathe."],
     "livesInFacts": ["Cool coastal waters of the North Atlantic and Pacific", "Harbor mouths and bays are favorite zones.", "Shallow water keeps them near fish schools."],
     "dietFacts": ["Small fish and squid", "They chase herring and sand lance.", "Echolocation helps hunting at night."],
     "sizeFacts": ["About as long as a grown-up is tall", "Rounded head lacks the bottle-nose of bigger dolphins.", "Dark gray back blends with the sea surface."]},
    {"id": "fin-whale", "name": "Fin Whale", "emoji": "🐋", "type": "Mammal", "habitat": "Ocean",
     "livesIn": "Open oceans worldwide — migrates between cold and warm seas", "diet": "Tiny krill and small schooling fish",
     "size": "Longer than a school bus — second-largest animal on Earth", "funFact": "Fin whales can gulp a swimming-pool-sized mouthful of water and food!",
     "extraFact": "Asymmetrical jaw coloring is white on the right, dark on the left.",
     "funFacts": ["Fin whales can gulp a swimming-pool-sized mouthful of water and food!", "They are called the 'greyhound of the sea' for speed.", "Low rumbling calls travel hundreds of miles underwater."],
     "didYouKnowFacts": ["A fin whale's heart can weigh as much as a small car.", "They lunge-feed through dense krill swarms.", "Blowholes spray a tall column when they surface."],
     "livesInFacts": ["Open oceans worldwide — migrates between cold and warm seas", "Polar summer feeding gives way to warmer winter waters.", "Deep water is no barrier to their travel."],
     "dietFacts": ["Tiny krill and small schooling fish", "Baleen plates filter food from seawater.", "They eat several tons of food per day in summer."],
     "sizeFacts": ["Longer than a school bus — second-largest animal on Earth", "Sleek body is built for fast long-distance swimming.", "A ridge behind the dorsal fin gives them their nickname 'razorback.'"]},
    {"id": "sperm-whale", "name": "Sperm Whale", "emoji": "🐋", "type": "Mammal", "habitat": "Ocean",
     "livesIn": "Deep oceans worldwide — dives far below the surface", "diet": "Giant squid, fish, and deep-sea creatures",
     "size": "Longer than two school buses", "funFact": "Sperm whales hunt giant squid in the dark deep sea!",
     "extraFact": "Their huge head holds a waxy oil called spermaceti.",
     "funFacts": ["Sperm whales hunt giant squid in the dark deep sea!", "They dive over an hour and a mile deep.", "Square-shaped head is one-third of their body length."],
     "didYouKnowFacts": ["Moby Dick was based on a sperm whale.", "Family groups are led by older females.", "Clicks they make are the loudest animal sounds known."],
     "livesInFacts": ["Deep oceans worldwide — dives far below the surface", "Warm and cold currents both appear in their range.", "Males roam farther than females and calves."],
     "dietFacts": ["Giant squid, fish, and deep-sea creatures", "Suction scars on skin show battles with squid.", "They swallow prey whole in the deep."],
     "sizeFacts": ["Longer than two school buses", "Flukes can be as wide as a car is long.", "Wrinkled skin looks prune-like after long dives."]},
    {"id": "pilot-whale", "name": "Pilot Whale", "emoji": "🐋", "type": "Mammal", "habitat": "Ocean",
     "livesIn": "Deep temperate and tropical seas worldwide", "diet": "Squid, fish, and octopus",
     "size": "About as long as a school bus", "funFact": "Pilot whales stick in tight pods like one big family!",
     "extraFact": "They are actually large dolphins, not true whales.",
     "funFacts": ["Pilot whales stick in tight pods like one big family!", "Males stay with their mother for life.", "Rounded heads give them a melon-shaped profile."],
     "didYouKnowFacts": ["Mass strandings sometimes trap whole pods on beaches.", "They echolocate to find squid in deep water.", "Short-finned and long-finned species live in different oceans."],
     "livesInFacts": ["Deep temperate and tropical seas worldwide", "Offshore canyons concentrate their prey.", "Pods of dozens swim together daily."],
     "dietFacts": ["Squid, fish, and octopus", "Night dives target squid that rise toward the surface.", "Each whale may eat hundreds of pounds daily."],
     "sizeFacts": ["About as long as a school bus", "Males are much larger than females.", "Dark gray or black skin blends with deep water."]},
]

def write_file(animals, append=False):
    mode = "a" if append else "w"
    with OUT.open(mode, encoding="utf-8") as f:
        for a in animals:
            f.write(json.dumps(a, ensure_ascii=False) + "\n")

if __name__ == "__main__":
    from animals_batch2 import BATCH2
    from animals_batch3 import BATCH3
    from animals_batch4 import BATCH4

    all_animals = ANIMALS + BATCH2 + BATCH3 + BATCH4
    expected_ids = """cardinal, great-blue-heron, stork, sandhill-crane, hoopoe, magpie, raven, jackdaw, storm-petrel, cormorant, grebe, white-ibis, roseate-spoonbill, groundhog, yellow-bellied-marmot, american-pika, black-tailed-prairie-dog, common-shrew, muskrat, saiga, takin, babirusa, pygmy-marmoset, gray-langur, fossa, small-spotted-genet, margay, spectacled-bear, wolverine, american-mink, harbor-porpoise, fin-whale, sperm-whale, pilot-whale, southern-stingray, great-hammerhead, goblin-shark, basking-shark, sea-lamprey, hagfish, coelacanth, giant-oarfish, barreleye, fangtooth, red-king-crab, giant-isopod, purple-sea-urchin, sand-dollar, aye-aye, indri, coquerels-sifaka, galapagos-tortoise, tuatara, common-basilisk, blue-tongue-skink, black-mamba, gray-tree-frog, blue-poison-dart-frog, lionfish, blue-marlin, atlantic-sailfish, anchovy, sardine, betta, guppy, mountain-goat, alpine-ibex, springbok, greater-kudu, giant-centipede, cone-snail, chinchilla, long-nosed-bandicoot, southern-cuscus, pistol-shrimp, eastern-quoll, sawfish, nurse-shark, mahi-mahi, leafy-sea-dragon, nudibranch, sea-pen, ribbon-worm, cotton-top-tamarin, sloth-bear, sable, least-weasel, devil-ray, japanese-spider-crab, bearded-dragon, emerald-tree-boa, dall-sheep, hamerkop, glow-worm, clown-knifefish, flying-gurnard, viperfish, hoatzin, resplendent-quetzal""".split(", ")

    ids = [a["id"] for a in all_animals]
    assert len(all_animals) == 99, f"got {len(all_animals)} animals"
    assert ids == expected_ids, "id order mismatch"

    write_file(all_animals)
    print(len(all_animals), "lines written to", OUT)
