#!/usr/bin/env python3
"""Generate strong_profiles.json for checklist animals."""

import json
from pathlib import Path

ROOT = Path(__file__).parent

# id|habitat|livesIn|diet|size|funFact|extraFact|pop1|pop2|status|threat|wild|cap
LINES = r"""
addax|Desert|Sahara Desert in Africa — among the driest places on Earth|Desert grasses and acacia leaves; they get water from food|About 1 m (3 ft) at the shoulder with twisted spiral horns|Addax antelope can go long periods without drinking water!|Their sandy coat grows lighter in summer and darker in winter.|Fewer than 100 addax remain in the wild.|Most survivors live in Niger and Chad.|Critically Endangered|Hunting and oil roads across the desert|15–20 years|25 years
african-buffalo|Grassland|Savannas, swamps, and forests across sub-Saharan Africa|Grass and plants — strong herds graze together|Large bulls can weigh as much as a small car|African buffalo herds stick together and defend each other from lions!|Their curved horns form a thick shield on the forehead called a boss.|About 900,000 African buffalo live in Africa.|They are one of the most dangerous animals to approach on foot.|Least Concern|Habitat loss and conflict with people|15–20 years|30 years
african-grey-parrot|Jungle|Lowland rainforests of central and West Africa|Fruits, nuts, seeds, and flowers in the treetops|About as long as your forearm with a short red tail|African grey parrots are famous for copying human speech and sounds!|Wild flocks roost in tall trees and travel far each day to feed.|Populations are falling; exact wild counts are uncertain.|Pet trade capture and forest loss are major threats.|Endangered|Illegal trapping for pets and logging|40–60 years|60+ years in good care
african-penguin|Ocean|Rocky coasts and islands off southern Africa|Small fish and squid caught while swimming|About knee-high — the only penguin that breeds in Africa|African penguins have a pink patch of skin above each eye!|They bray like donkeys, which is why people call them jackass penguins.|Roughly 10,000 breeding pairs remain.|Food shortages and oil spills have caused sharp declines.|Endangered|Overfishing, oil pollution, and climate change|10–15 years|20 years in zoos
agouti|Jungle|Neotropical forests from Mexico to Brazil|Fruits, nuts, seeds, and fallen plants on the forest floor|Rabbit-sized with long legs for running|Agoutis are among the only animals that can crack open Brazil nuts!|They bury seeds and often forget them, helping new trees grow.|Common in healthy rainforests but hard to count precisely.|Forest clearing reduces their living space.|Least Concern|Habitat loss and hunting|10–15 years|20 years
aldabra-tortoise|Ocean|Aldabra Atoll in the Indian Ocean — a remote coral ring|Grasses, leaves, and low plants on the atoll|One of the largest tortoises — shell longer than a child is tall|Aldabra tortoises can live more than 100 years!|They store water and fat inside their bodies for dry seasons.|About 100,000 live on the Aldabra Atoll.|The atoll is protected, so numbers are stable.|Vulnerable|Climate change and rising seas threaten low islands|80–120 years|150+ years
american-flamingo|Ocean|Caribbean islands, Yucatán coasts, and Galápagos wetlands|Filter tiny shrimp and algae from muddy water with their bent bill|Tall as a child — long pink legs and neck|American flamingos get their pink color from food in the water!|Thousands nest together in huge muddy colonies.|Tens of thousands live in the Caribbean region.|Colony counts change with wetland conditions.|Least Concern|Habitat loss and disturbance at nest sites|20–30 years|40+ years in zoos
amur-leopard|Forest|Temperate forests in far eastern Russia and northeast China|Deer, wild boar, and hare in snowy woodlands|Big cat about the size of a large dog with thick spotted fur|Amur leopards can leap more than 19 feet in a single bound!|They are the rarest big cat on Earth.|Fewer than 120 Amur leopards remain in the wild.|A small population also lives in China.|Critically Endangered|Poaching, logging, and road building|10–15 years|20 years in zoos
anatolian-leopard|Grassland|Historically Anatolian hills and forests in Turkey|Deer, wild goats, and boar|Large spotted leopard — now vanishingly rare|The Anatolian leopard may be extinct in the wild in Turkey.|Camera traps occasionally spark hope that a few survive.|Possibly none remain; a few sightings are unconfirmed.|Turkey has protected areas where leopards once roamed.|Critically Endangered (possibly extinct locally)|Hunting and habitat loss|10–12 years|Unknown
andean-flamingo|Grassland|High salt lakes in the Andes Mountains of South America|Filters tiny brine shrimp from very salty water|Pale pink with yellow legs and a black bill|Andean flamingos live higher than any other flamingo — up to 15,000 feet!|Their lakes freeze at night, so they must endure extreme cold.|About 39,000 Andean flamingos remain.|They gather on a few special lakes to breed.|Vulnerable|Mining, drought, and egg collecting|20–30 years|40 years
apennine-chamois|Forest|High rocky slopes of Italy's Apennine Mountains|Grass, herbs, and tender shoots above the tree line|Goat-sized with hooked horns and a dark face mask|Apennine chamois can climb near-vertical rock faces!|Kids can follow mothers on steep cliffs within days of birth.|Roughly 600–700 Apennine chamois survive.|They live only in Italy's central mountains.|Endangered|Small range, inbreeding, and climate change|12–15 years|20 years
aquatic-warbler|Grassland|Fens and wet meadows in eastern Europe and Belarus|Insects and spiders caught in dense wet grass|Small brown songbird — easy to miss in reeds|Aquatic warblers migrate thousands of miles to West Africa each winter!|Males build domed nests hidden in thick sedges.|About 11,000–15,000 singing males estimated.|Wetland drainage has shrunk their breeding grounds.|Vulnerable|Drained fens and late mowing of meadows|3–6 years|8 years
arabian-leopard|Desert|Mountain ranges of the Arabian Peninsula|Mountain goats, deer, and small mammals|Smaller than African leopards with pale spots|Arabian leopards are the smallest leopard subspecies.|Their pale coat blends with rocky desert mountains.|Fewer than 200 may remain across Arabia.|Oman and Yemen hold the last wild groups.|Critically Endangered|Habitat loss, prey loss, and persecution|10–12 years|20 years
armenian-mouflon|Grassland|Armenian highlands and rocky open hills|Grasses and herbs on mountain slopes|Sheep-sized wild sheep with curved horns|Armenian mouflon rams clash horns in autumn breeding fights!|Ancestors of many domestic sheep looked like mouflon.|Several thousand live in Armenia and Iran.|Protected parks help keep herds stable.|Near Threatened|Hunting and competition with livestock|10–12 years|18 years
asiatic-black-bear|Forest|Forests from Iran to Japan and southeast Asia|Fruits, nuts, insects, and carrion — very omnivorous|Medium bear with a white chest patch like a crescent moon|Asiatic black bears are excellent tree climbers!|They are also called moon bears because of the chest mark.|Tens of thousands remain across Asia.|Exact counts are difficult in mountain forests.|Vulnerable|Deforestation and bear bile farms|20–25 years|30 years in sanctuaries
atlantic-puffin|Ocean|Sea cliffs of the North Atlantic in summer|Small fish like sand eels, caught underwater|About the size of a pigeon with a colorful bill in breeding season|Atlantic puffins can carry dozens of fish crosswise in their bill!|They dig burrows in grassy cliff tops like underground tunnels.|Millions breed on North Atlantic coasts.|Some colonies have declined as fish shift with warming seas.|Vulnerable|Overfishing, storms, and climate change|20–25 years|30 years
atlantic-spotted-dolphin|Ocean|Warm Atlantic waters from the U.S. coast to Africa|Fish and squid in open ocean pods|Sleek dolphin up to about 2.3 m long|Atlantic spotted dolphins get more spots as they grow older!|Pods leap and ride bow waves in front of boats.|Hundreds of thousands live in the Atlantic.|They are not as numerous as common dolphins.|Least Concern|Fishing nets and ocean noise|25–30 years|40 years
baikal-seal|Arctic|Lake Baikal in Siberia — the world's deepest freshwater lake|Fish and tiny crustaceans under ice|One of the smallest seals — about 1.3 m long|Baikal seals are the only freshwater seals found far from the sea!|Pups are born in ice dens on the frozen lake.|Roughly 80,000–100,000 Baikal seals.|Lake pollution threatens their food.|Least Concern|Pollution and illegal hunting|20–25 years|30 years
bairds-tapir|Jungle|Cloud forests and rainforests from Mexico to Ecuador|Leaves, twigs, and fruit — helps spread seeds|Largest land mammal in its range — looks like a round pig with a trunk|Baird's tapirs use their flexible snout like a snorkel when swimming!|Calves have watermelon-like stripes that fade as they grow.|Thousands remain but numbers are falling.|Forest roads and hunting hurt tapirs.|Endangered|Habitat loss and hunting|25–30 years|35 years
balkan-lynx|Forest|Remote forests of North Macedonia and Albania|Roe deer and small mammals in snowy woods|Small lynx with tufted ears and spotted coat|Balkan lynx are one of the rarest cats in Europe!|They need large forests with plenty of rabbits and deer.|Fewer than 50 may survive in the wild.|Camera traps occasionally photograph lone lynx.|Critically Endangered|Poaching, logging, and small population|10–12 years|20 years
bar-tailed-lark|Desert|Desert plains of the Middle East and North Africa|Seeds and insects in dry open country|Sparrow-sized sandy-brown lark|Bar-tailed larks run on the ground instead of hopping like many birds!|Their color matches desert sand and hides them from hawks.|Common in deserts but not precisely counted.|Stable in remote arid lands.|Least Concern|Habitat disturbance|3–5 years|8 years
barbary-falcon|Desert|Cliffs and arid hills of North Africa|Birds and insects caught in fast aerial chases|Falcon about the size of a crow|Barbary falcons dive at tremendous speed to catch prey!|They nest on cliff ledges above the desert.|Several thousand pairs in North Africa.|Not as rare as some falcons but poorly studied.|Least Concern|Disturbance at nest cliffs|10–15 years|20 years
barbary-macaque|Forest|Atlas Mountains and cedar forests of Morocco and Algeria|Acorns, leaves, fruit, and insects|Tailless monkey — about 60 cm long sitting|Barbary macaques are the only wild monkeys in Europe (Gibraltar too)!|They groom each other to build troop friendships.|About 8,000–10,000 Barbary macaques remain.|Forests in Morocco hold the largest troops.|Endangered|Logging, tourists feeding them, and pet trade|20–25 years|30 years
basra-reed-warbler|Jungle|Marsh reeds of southern Iraq and Khuzestan|Insects in dense reedbeds|Small brown warbler with a loud song|Basra reed warblers migrate to East African wetlands each winter.|Their nests hang in reeds above water.|A few thousand pairs may remain.|Marsh drainage is the biggest problem.|Endangered|Drained marshes and drought|4–6 years|9 years
bearded-vulture|Grassland|High mountains of Europe, Africa, and Asia|Bones and bone marrow — drops bones onto rocks to break them|Huge vulture with a feathered neck ruff|Bearded vultures dye their feathers rusty orange with mud!|They are the only birds that eat mostly bone.|Several thousand remain in mountains worldwide.|Reintroduction projects help in the Alps.|Near Threatened|Poisoned carcasses and habitat loss|21–30 years|45 years
bezoar-ibex|Grassland|Rocky mountains of Turkey and the Caucasus|Grasses and herbs on cliff ledges|Wild goat with long scimitar-shaped horns|Bezoar ibex stand on tiny ledges above sheer drops!|Males' horns can grow longer than 1 meter.|Several thousand in Turkey and Iran.|Hunting is now regulated in many areas.|Near Threatened|Hunting and habitat loss|15–18 years|22 years
binturong|Jungle|Tall rainforests of Southeast Asia|Fruits, especially figs, and small animals|Bearcat with a prehensile tail that grips branches|Binturongs smell like buttered popcorn!|Their tail works like a fifth hand when climbing.|Unknown exact count — declining in many forests.|Palm oil plantations replace their forest.|Vulnerable|Deforestation and pet trade|18–22 years|25 years
bird-of-paradise|Jungle|New Guinea rainforests — males display on forest courts|Fruits and insects in the canopy|Small to crow-sized birds with extraordinary plumes|Males dance, fan feathers, and hop to impress females!|Raggiana bird-of-paradise males look like floating red fans.|Still common in remote New Guinea forests.|Each species has a tiny range.|Least Concern to Vulnerable|Forest logging|5–8 years|15 years
black-stork|Forest|Forests and rivers across Europe and Asia|Fish, frogs, and insects in shallow water|Tall black-and-white stork with a red bill|Black storks migrate to Africa for winter — silent fliers!|They nest high in old trees far from people.|About 24,000–44,000 pairs in Europe.|Wetland loss affects feeding grounds.|Least Concern|Dam building and disturbance|15–20 years|30 years
black-crowned-crane|Grassland|Savanna wetlands of sub-Saharan Africa|Plants, insects, and small animals in marshes|Tall crane with a golden fan of neck feathers|Black-crowned cranes dance with jumps and bowing displays!|They nest in wetland vegetation standing in water.|About 33,000–66,000 remain.|West African populations are shrinking.|Vulnerable|Drained wetlands and pesticides|20–30 years|40 years
black-necked-crane|Grassland|High plateaus of Tibet and Bhutan in summer|Roots, tubers, and grains in wetlands|Medium crane with a black neck and white eye ring|Black-necked cranes are the only cranes that breed on alpine meadows!|They are sacred birds in Bhutanese culture.|About 10,000–11,000 remain.|Dam projects threaten Tibetan wetlands.|Near Threatened|Habitat loss and disturbance|20–30 years|40 years
bongo|Jungle|Dense forests of central and West Africa|Leaves, shoots, and mineral-rich soil they lick|Large antelope with white stripes and long spiraled horns|Bongos are among the shyest and most colorful forest antelopes!|They mostly feed at night when the forest is quieter.|About 15,000–25,000 bongos may remain.|Eastern bongo subspecies are Critically Endangered.|Near Threatened|Bushmeat hunting and logging|19–21 years|30 years
bonobo|Jungle|Only in lowland rainforests south of the Congo River|Mostly fruits and plants — very peaceful apes|Slightly smaller than chimpanzees with slimmer bodies|Bonobos share food and settle disputes by grooming, not fighting!|Females lead bonobo groups more than in chimp troops.|About 15,000–20,000 bonobos remain.|They live only in the Democratic Republic of Congo.|Endangered|Hunting and habitat loss|40 years|50 years in zoos
bukhara-deer|Grassland|Riparian tugai forests along Central Asian rivers|Leaves, bark, and plants in river woodland|Reddish deer with branched antlers in males|Bukhara deer survive in hot river forests in the desert!|They were nearly extinct but parks brought them back.|About 1,400 Bukhara deer in protected areas.|Reintroduction raised numbers from almost zero.|Endangered|River damming and poaching|12–15 years|20 years
greater-flamingo|Ocean|Shallow lakes and lagoons across Africa, southern Europe, and Asia|Filters algae and tiny shrimp while head upside-down in water|Tall pink bird with stilt legs|Greater flamingos can live in very salty lakes other birds avoid!|A single egg is laid on a mud mound nest.|About 500,000–600,000 greater flamingos.|Huge flocks gather at lakes like Etosha and Camargue.|Least Concern|Wetland loss and disturbance|20–30 years|40 years
cape-fur-seal|Ocean|Coasts and islands of southern Africa|Fish and squid in cold Benguela Current waters|Bull seals much larger than females — loud breeding colonies|Cape fur seal pups learn to swim in crowded nursery pools!|Great white sharks hunt near seal islands.|About 2 million Cape fur seals.|Colonies recovered after hunting ended.|Least Concern|Fishing conflicts and oil spills|20–25 years|30 years
caspian-seal|Arctic|Caspian Sea — the world's largest inland body of water|Fish and crustaceans in brackish water|Smallest seal in their region — pups have white fur|Caspian seal pups are born on ice in late winter!|Pollution from rivers has hurt seal health.|About 100,000–170,000 Caspian seals.|Numbers have dropped sharply since the 1900s.|Endangered|Pollution, hunting, and habitat change|30–50 years|50 years
cat-ba-langur|Jungle|Cat Ba Island limestone forests in Vietnam|Leaves, especially young leaves, in the canopy|Golden-orange langur with a long tail|Cat Ba langurs are found on one island in Vietnam!|Their babies are orange while adults are darker.|Fewer than 70 Cat Ba langurs remain.|They are one of the world's rarest primates.|Critically Endangered|Habitat loss and hunting|20–25 years|30 years
caucasian-leopard|Forest|Caucasus Mountains between Europe and Asia|Wild goats, deer, and boar|Powerful spotted leopard in rugged mountains|Caucasian leopards roam the highest peaks of Russia and Georgia.|Camera traps prove a few still cross mountain passes.|Possibly fewer than 1,000 in the wild.|Russia and Iran hold the main populations.|Endangered|Poaching and road kills|10–12 years|20 years
chamois|Forest|Alpine meadows and rocky peaks of European mountains|Grass and herbs on steep slopes|Goat-antelope with hooked horns and agile hooves|Chamois can jump 2 meters straight up from a standstill!|Kids are born on cliff ledges in spring.|About 400,000 chamois in the Alps and Carpathians.|Hunting is regulated in many countries.|Least Concern|Climate change and tourism disturbance|15–20 years|25 years
chimpanzee|Jungle|Tropical forests and woodlands of central and West Africa|Fruits, leaves, nuts, and sometimes monkeys or termites|Strong apes — arms longer than legs for knuckle-walking|Chimpanzees use sticks to fish termites out of mounds!|They are our closest living relatives besides bonobos.|About 170,000–300,000 chimpanzees remain.|Populations have fallen fast in recent decades.|Endangered|Hunting, forest loss, and disease|33–40 years|50 years in sanctuaries
cuban-crocodile|Jungle|Zapata Swamp and Isle of Youth in Cuba|Fish, turtles, and small mammals in freshwater|Medium crocodile with bumpy scales and long legs|Cuban crocodiles can leap high out of water to catch prey!|They are one of the most aggressive crocodile species.|About 3,000 Cuban crocodiles in the wild.|Hybridization with American crocodiles is a threat.|Critically Endangered|Habitat loss and hybridization|50–75 years|75+ years
dalmatian-pelican|Ocean|Freshwater lakes and deltas of southeastern Europe and Asia|Fish scooped up in a huge bill pouch|One of the heaviest flying birds — wingspan nearly 3 m|Dalmatian pelicans fish together, herding fish into shallows!|They nest in floating reed islands in lakes.|About 4,300–11,000 Dalmatian pelicans.|Wetland drainage has shrunk breeding lakes.|Near Threatened|Drained wetlands and fishing nets|15–25 years|35 years
dama-gazelle|Desert|Sahel grasslands and Sahara edge in Africa|Acacia leaves and desert grasses|Tall gazelle with white neck and S-shaped horns|Dama gazelles can raise their body temperature to save water!|They once ranged across the Sahara in huge herds.|Fewer than 100 dama gazelles remain in the wild.|Captive breeding keeps the species alive.|Critically Endangered|Hunting and desertification|12–15 years|20 years
dead-sea-sparrow|Desert|Jordan Valley and Dead Sea shores|Seeds and insects in scrubby desert plants|Sparrow-sized bird adapted to very salty, hot valleys|Dead Sea sparrows nest in Tamarisk bushes near salty water!|They tolerate heat that would stress many songbirds.|Small populations in Jordan and Israel.|Habitat change along the Rift Valley.|Least Concern|Water diversion and development|4–6 years|10 years
demoiselle-crane|Grassland|Grass steppes of central Asia — migrates over Himalayas|Plants, grains, and insects on open plains|Smaller crane with a black neck and white ear tufts|Demoiselle cranes cross the Himalayas at 26,000 feet on migration!|They perform graceful dancing displays.|About 200,000–230,000 demoiselle cranes.|Most migrate through narrow mountain passes.|Least Concern|Habitat loss and power lines|20–30 years|40 years
desert-elephant|Desert|Namib Desert in Namibia — not a separate species but special herds|Browse on ana trees and travel far for water|African elephants adapted to desert travel|Desert elephants have longer legs and bigger feet for sandy terrain!|They remember water sources used generations ago.|About 150 desert-adapted elephants in Namibia.|They are the same species as savanna elephants.|Vulnerable|Drought and human-elephant conflict|60–70 years|70 years
doctor-bird|Jungle|Jamaica's forests — national bird, also called red-billed streamertail|Nectar from tropical flowers with a long curved bill|Tiny hummingbird with tail feathers longer than its body|Doctor birds' tail streamers flutter like a fancy coat!|They hover at flowers beating wings 50 times a second.|Common on Jamaica but found nowhere else.|Island habitat loss is the main threat.|Least Concern|Forest clearing|3–5 years|10 years
dorcas-gazelle|Desert|Sahara and Arabian deserts in small hardy herds|Acacia leaves, grasses, and desert plants|Small gazelle with curved horns and sandy coat|Dorcas gazelles need little water — they get moisture from plants!|They bounce with stiff-legged leaps called stotting.|Tens of thousands remain but declining.|Sahara populations have crashed.|Vulnerable|Hunting and habitat loss|10–12 years|18 years
drill|Jungle|Rainforests of Nigeria, Cameroon, and Equatorial Guinea|Fruits, seeds, and plants on the forest floor|Large monkey — males have pink and blue striped rumps|Drill troops forage on the ground like forest ground hogs!|Males have colorful rear markings to impress rivals.|Fewer than 4,000 drills remain.|They are among the most endangered African monkeys.|Endangered|Bushmeat hunting and logging|20–28 years|35 years
east-caucasian-tur|Grassland|High Caucasus peaks above the tree line|Alpine grasses and herbs on cliffs|Wild goat with huge scimitar horns in males|East Caucasian turs climb sheer rock at 13,000 feet!|Horns can weigh more than the skull itself.|About 5,000–6,000 in Russia and Georgia.|Protected reserves help stabilize herds.|Near Threatened|Poaching and disturbance|12–15 years|20 years
egyptian-vulture|Grassland|Open country from southern Europe to India and Africa|Carrion, eggs, and waste — often follows livestock|Small vulture with white feathers and yellow face|Egyptian vultures use stones to crack open ostrich eggs!|They sometimes dye feathers with red soil.|About 21,000–67,000 mature Egyptian vultures.|Populations are falling across Europe.|Endangered|Poisoned bait and power lines|21 years|35 years
ethiopian-wolf|Grassland|Afro-alpine meadows above 3,000 m in Ethiopia|Mainly giant mole-rats dug from burrows|Slender fox-sized canid with reddish coat|Ethiopian wolves are Africa's most endangered carnivore!|Packs hunt mole-rats together on open alpine turf.|Only about 500 survive in a few mountain pockets.|They are the only wolf species native to Africa.|Endangered|Disease from domestic dogs and habitat loss|8–10 years|15 years
eurasian-lynx|Forest|Boreal and temperate forests from Europe to Siberia|Roe deer, hares, and grouse in snow|Large lynx with tufted ears — biggest lynx species|Eurasian lynx can bring down deer much larger than themselves!|Their huge paws work like snowshoes in winter.|About 50,000 Eurasian lynx in Europe and Asia.|Reintroductions succeeded in several countries.|Least Concern|Poaching and road kills|10–15 years|25 years
eurasian-otter|Forest|Rivers, lakes, and coasts across Europe and Asia|Fish, frogs, and crustaceans in clean water|Streamlined mammal about 1 m long with webbed feet|Eurasian otters slide on mud and snow for fun!|They use whiskers to sense fish in murky water.|Tens of thousands across a huge range.|Water pollution hurt them but many rivers recovered.|Near Threatened|Pollution and dam building|10–15 years|20 years
european-bison|Forest|Białowieża Forest in Poland and Belarus — last wild herd|Browse leaves, bark, and shoots in ancient woodland|Heaviest land animal in Europe — taller than a person|European bison were saved from extinction by zoo breeding!|A bull can weigh more than 900 kg.|About 7,000 European bison in the wild.|Herd numbers grow slowly due to low birth rate.|Near Threatened|Small population and inbreeding|20–25 years|30 years
european-otter|Forest|Clean rivers and lakes across Europe|Fish and amphibians|Eurasian otter — same species as European otter|European otters mark territories with spraint scent piles!|They close ears and nose underwater while hunting.|Several thousand in the UK and thousands more in Europe.|River cleanup helped otters return.|Near Threatened|Pollution and habitat fragmentation|10–15 years|20 years
european-souslik|Grassland|Steppe grasslands of eastern Europe|Grasses, seeds, and herbs|Ground squirrel that stands upright to watch for hawks|European sousliks hibernate half the year underground!|They whistle alarm calls to warn the colony.|Local populations common but declining overall.|Farmland replaced much steppe.|Least Concern|Habitat loss|4–6 years|10 years
fiji-banded-iguana|Jungle|Fiji and Tonga tropical dry forests|Leaves, flowers, and fruit in the canopy|Bright green iguana with blue or white bands|Fiji banded iguanas change color with mood and temperature!|They are threatened by invasive mongooses.|Fewer than 10,000 may remain.|Island forests are small and fragile.|Endangered|Invasive species and logging|10–15 years|25 years
flying-fox|Jungle|Forests of Australia, Pacific islands, and Southeast Asia|Fruit, nectar, and pollen — vital pollinators|Large fruit bat with fox-like face and 1 m wingspan|Flying foxes pollinate eucalyptus and rainforest trees at night!|Camps of thousands hang upside down in roost trees.|Millions across Australia and islands.|Some island populations are very small.|Least Concern to Vulnerable|Heat stress and habitat loss|15–20 years|25 years
forest-elephant|Jungle|Central and West African rainforests|Fruits, bark, and leaves — spread many tree seeds|Smaller than savanna elephants with straighter tusks|Forest elephants communicate with rumbles too low for humans to hear!|Their dung spreads seeds across the forest floor.|About 100,000 forest elephants may remain.|Ivory poaching reduced numbers sharply.|Critically Endangered|Poaching and logging|60–70 years|70 years
formosan-black-bear|Forest|Mountain forests of Taiwan|Nuts, fruits, insects, and carrion|Medium black bear with a white V on the chest|Formosan black bears build day beds in trees to rest!|They are Taiwan's largest land predator.|About 200–600 Formosan black bears.|Roads and traps threaten isolated bears.|Endangered|Habitat loss and snares|20–25 years|30 years
magnificent-frigatebird|Ocean|Tropical coasts — nests on islands, soars over open sea|Fish stolen from other birds or snatched from the surface|Huge wingspan — males inflate a red throat pouch in display|Magnificent frigatebirds can stay airborne for weeks!|They cannot land on water because their feathers are not waterproof.|Hundreds of thousands in tropical oceans.|Colony disturbance is the main threat.|Least Concern|Climate change and fishing|15–25 years|35 years
ganges-river-dolphin|Ocean|Ganges and Brahmaputra river systems in India and Bangladesh|Fish and shrimp in muddy freshwater|Blind river dolphin — uses echolocation with a long thin snout|Ganges river dolphins swim on their side and bump the river bottom!|They are called susu because of the sound they make.|About 1,200–1,800 Ganges river dolphins.|Dams and pollution fragment their rivers.|Endangered|Dams, nets, and pollution|20–30 years|30 years
gelada-baboon|Grassland|High grassy plateaus of Ethiopia above 2,000 m|Almost entirely grass — most graminivorous primate|Stocky baboon with a heart-shaped red chest patch|Geladas chatter and flip their lips in huge cliffside herds!|They sleep on cliff ledges safe from leopards.|About 200,000 geladas on Ethiopian plateaus.|Their range is limited to Ethiopia.|Least Concern|Farming and drought|15–20 years|30 years
geoffroys-tamarin|Jungle|Central American forests from Panama to Colombia|Fruits, insects, and tree gum they gouge from bark|Tiny monkey weighing less than a half kilogram|Geoffroy's tamarins often carry twin babies on their back!|Family groups share raising the young.|Thousands remain but forests are shrinking.|Panama's forests are under pressure.|Least Concern|Deforestation|10–15 years|20 years
giant-ibis|Jungle|Seasonal wetlands and grasslands of Cambodia and Laos|Frogs, eels, and insects in shallow water|Tall dark ibis — Cambodia's national bird|Giant ibis are the world's largest ibis species!|Only a few hundred nests are found each year.|Fewer than 200 mature giant ibis remain.|They are Cambodia's rarest bird.|Critically Endangered|Habitat loss and hunting|25 years|40 years
giant-muntjac|Forest|Evergreen forests of Laos and Vietnam|Leaves, fruits, and forest plants|Large deer with unbranched antlers in males|Giant muntjac was only discovered by scientists in 1994!|They leave deep hoof prints in muddy forest trails.|Unknown numbers — rarely seen.|Deforestation threatens their forests.|Endangered|Logging and snares|10–12 years|18 years
giant-otter|Jungle|Rivers and lakes of the Amazon and Pantanal|Fish — a family can eat several kilograms daily|Up to 1.8 m long — longest otter species|Giant otters hunt in family teams and whistle to each other!|Each otter has a unique white throat patch.|A few thousand giant otters remain.|Gold mining pollutes their rivers.|Endangered|Pollution, fishing, and habitat loss|8–10 years|15 years
giant-sable-antelope|Grassland|Angola's Malanje plateau woodlands|Leaves and herbs in forest clearings|Magnificent antelope with long curved horns in both sexes|Giant sable antelope were thought extinct then rediscovered!|Their horns can curve almost a full circle.|Fewer than 400 giant sable antelopes.|They survive only in one region of Angola.|Critically Endangered|Civil war legacy and poaching|15–18 years|22 years
goitered-gazelle|Desert|Semi-deserts from the Middle East to China|Grasses, herbs, and desert plants|Medium gazelle — males' throats swell in breeding season|Goitered gazelles can run 60 km/h across open plains!|They migrate long distances between summer and winter range.|About 40,000–50,000 goitered gazelles.|Central Asian populations are healthiest.|Vulnerable|Hunting and habitat loss|8–12 years|18 years
golden-monkey|Jungle|Bamboo forests of China's mountains|Bamboo leaves, buds, and fruits|Small monkey with a golden belly and blue face mask|Golden monkeys live in cold snowy mountains in huge troops!|Their nose turns up in freezing air to reduce frostbite.|About 8,000–10,000 golden monkeys.|China's protected forests help them.|Endangered|Habitat loss|20 years|30 years
golden-snub-nosed-monkey|Forest|High conifer forests of central China|Lichens, bark, and leaves — loves snowy winters|Stocky monkey with a squashed nose and golden coat|Golden snub-nosed monkeys have thick fur for -10°C winters!|Troops of 100+ travel through mountain snow.|About 8,000–15,000 golden snub-nosed monkeys.|China's reserves protect key forests.|Endangered|Logging and tourism pressure|20–25 years|30 years
great-bustard|Grassland|Open steppes of Europe and central Asia|Plants, insects, and seeds on farmland and plains|Heavy bird — males can weigh 16 kg with a white whisker display|Male great bustards inflate throat sacs into a huge white balloon!|They are among the heaviest birds that can fly.|About 44,000–57,000 great bustards.|Iberian populations are recovering with protection.|Vulnerable|Power lines and farming|10–15 years|25 years
great-grey-owl|Forest|Boreal forests of North America, Europe, and Asia|Voles hunted by sound through snow|Large owl with a round facial disk and yellow eyes|Great grey owls can hear voles tunneling under deep snow!|They look huge but weigh less than many other owls.|Tens of thousands across northern forests.|Forests are still widespread.|Least Concern|Logging and road kills|10–15 years|25 years
green-vervet-monkey|Jungle|Savanna woodlands and forests of sub-Saharan Africa|Fruits, flowers, and insects — cheek pouches store food|Medium monkey with black face and greenish fur|Vervet monkeys have different alarm calls for eagles, snakes, and leopards!|Troops have strict pecking orders led by males.|Common across Africa in suitable habitat.|Leopards and eagles hunt them often.|Least Concern|Habitat loss|12–24 years|30 years
grey-rhebok|Grassland|High grassy slopes of southern Africa|Grass and herbs on hillsides|Small antelope with long neck and pointed ears|Grey rhebok stand on rocks to watch for predators!|Only males carry short straight horns.|Several thousand in South African mountains.|Stable in protected reserves.|Near Threatened|Habitat loss|8–10 years|15 years
griffon-vulture|Grassland|Mountains and cliffs across Europe, Africa, and Asia|Carrion from livestock and wild herds|Large vulture with a ruff of white neck feathers|Griffon vultures soar for hours without flapping on updrafts!|Colonies nest on inaccessible cliff ledges.|About 270,000–330,000 griffon vultures.|Reintroductions helped in the Alps.|Least Concern|Poisoned carcasses|25–30 years|40 years
guanaco|Grassland|Patagonian steppes, Andes foothills, and coastal Chile|Grasses and shrubs in windy open country|Wild ancestor of llamas — about 1.2 m at shoulder|Guanacos spit when annoyed and run 56 km/h!|Their soft wool is warmer than sheep's wool.|About 1.5–2.2 million guanacos.|They are the largest wild mammal in Patagonia.|Least Concern|Habitat loss and hunting|15–20 years|25 years
hectors-dolphin|Ocean|Shallow coastal waters around New Zealand|Small fish and squid near shore|One of the smallest dolphins — about 1.4 m long|Hector's dolphins have rounded dorsal fins like Mickey Mouse ears!|Māui dolphins are a subspecies with fewer than 60 left.|About 15,000 Hector's dolphins.|Gillnets catch them accidentally.|Endangered|Fishing nets and coastal development|20 years|25 years
hoolock-gibbon|Jungle|Tropical forests of northeast India, Myanmar, and China|Fruits, leaves, and flowers in the canopy|Small ape that swings arm-over-arm through trees|Hoolock gibbons sing duets at dawn that carry for kilometers!|Eastern and western species have different calls.|About 200,000 hoolock gibbons.|Forest clearing splits their populations.|Endangered|Logging and jhum farming|25–30 years|40 years
hula-painted-frog|Forest|Once Hula Lake marshes in Israel — rediscovered in 2011|Insects and worms in wetland vegetation|Dark frog discovered alive after thought extinct for decades|Hula painted frogs were missing for over 50 years then found again!|They are Israel's only living native amphibian.|Fewer than 200 mature Hula painted frogs.|Restored wetlands may help them spread.|Critically Endangered|Drained marshes|10–15 years|20 years
humboldt-penguin|Ocean|Coasts of Chile and Peru — nests in guano burrows|Anchovies and sardines in cold Humboldt Current|Medium penguin with black horseshoe chest band|Humboldt penguins nest in ancient seabird poop layers called guano!|El Niño warmings crash their fish food.|About 23,000–32,000 Humboldt penguins.|Fish quotas and protected islands help.|Vulnerable|Overfishing and climate swings|15–20 years|30 years
hyacinth-macaw|Jungle|Palm savannas of central South America|Hard palm nuts cracked with massive beak|Largest flying parrot — cobalt blue with yellow eye patches|Hyacinth macaws need manduvi trees with holes for nesting!|Their beak can crack coconuts.|About 4,300 hyacinth macaws in the wild.|The pet trade once removed thousands.|Vulnerable|Habitat loss and trapping|50 years|60+ years in care
iberian-lynx|Forest|Mediterranean scrub and rabbit-rich woodlands in Spain and Portugal|Almost entirely European rabbits|Spotted lynx with a short tail and tufted ears|Iberian lynx bounced back from fewer than 100 to over 1,000!|They need rabbit burrows for hunting success.|About 1,100 Iberian lynx today.|Reintroduction uses captive-bred cats.|Endangered|Rabbit disease and road kills|13 years|20 years
imperial-parrot|Jungle|Mountain rainforests of Dominica|Fruits and nuts in tall forest trees|Large green parrot — national bird of Dominica|Imperial parrots are also called sisserou and appear on Dominica's flag!|Hurricanes can destroy nest trees.|Fewer than 250 mature imperial parrots.|They live only on one Caribbean island.|Endangered|Hurricanes and habitat loss|40 years|60 years
indus-river-dolphin|Ocean|Indus River in Pakistan — blind freshwater dolphin|Fish in muddy river channels|Small dolphin with a long snout and tiny eyes|Indus river dolphins swim on their sides feeling the river bottom!|Dams split populations into isolated sections.|About 1,100–1,500 Indus river dolphins.|Pakistan protects them by law.|Endangered|Dams, pollution, and entanglement|20–30 years|30 years
irrawaddy-dolphin|Ocean|Coastal waters and rivers of Southeast Asia|Fish and cephalopods in brackish water|Rounded forehead dolphin without a long beak|Irrawaddy dolphins cooperate with fishermen in Myanmar!|They spit water to herd fish in some traditions.|About 7,000 Irrawaddy dolphins.|Mekong population has fewer than 100.|Endangered|Fishing nets and dam building|30 years|40 years
jaguarundi|Jungle|Brushy forests from Texas to Argentina|Small mammals, birds, and reptiles|Long-bodied small cat — looks like an otter or weasel|Jaguarundis can jump 2 m straight up to catch birds!|They come in red and gray color phases.|Still fairly common in some Central American forests.|Habitat clearing reduces their range.|Least Concern|Deforestation|10–12 years|18 years
jamaican-iguana|Jungle|Hellshire Hills limestone forest in Jamaica|Leaves, flowers, and fruits|Large gray iguana thought extinct until rediscovered in 1990|Jamaican iguanas are the largest native land animal in Jamaica!|Mongooses and cats eat their eggs.|Fewer than 500 Jamaican iguanas.|A captive head-start program releases young iguanas.|Critically Endangered|Invasive predators|15–20 years|30 years
king-vulture|Jungle|Central and South American tropical forests|Carrion located by sight from high perches|Large vulture with colorful head — white, orange, and purple|King vultures arrive first at carcasses and other vultures wait!|Their colorful head may help species recognize each other.|Tens of thousands across tropical America.|Forest loss is gradual.|Least Concern|Deforestation|30 years|40 years
koi-carp|Farm|Ornamental ponds worldwide — bred from common carp|Aquatic plants, insects, and pellet food|Domestic fish — many color patterns and sizes|Koi can live decades and recognize the person who feeds them!|Some koi have sold for over a million dollars.|Millions kept in ponds globally.|Wild common carp relatives are widespread.|Domestic|Not a wild extinction concern|25–35 years|50+ years
kulan|Grassland|Central Asian steppes — wild ass related to donkeys|Grasses and herbs on open plains|Stocky wild ass with a short dark mane|Kulan can run 70 km/h across treeless steppe!|They once ranged from Ukraine to Mongolia.|About 4,000–5,000 kulan in protected areas.|Reintroduction projects expand their range.|Endangered|Hunting and competition with livestock|20–25 years|30 years
lebanon-viper|Forest|Mountains of Lebanon and Syria|Small rodents and lizards|Thick-bodied viper with a triangular head|Lebanon vipers bask on sunny rocks in mountain meadows!|They give birth to live young rather than laying eggs.|Unknown numbers — restricted range.|Habitat loss in mountains.|Endangered|Habitat loss and persecution|15–20 years|25 years
leopard-cat|Jungle|Forests from Pakistan to Japan and Southeast Asia|Rodents, birds, and insects|House-cat-sized wild cat with spots and stripes|Leopard cats are among the few cats that swim willingly!|They are ancestors of the Bengal cat breed.|Still widespread but declining.|Habitat loss and fur trade historically.|Least Concern|Deforestation|10–12 years|18 years
lion-tailed-macaque|Jungle|Western Ghats rainforests of India|Fruits, seeds, and insects in the canopy|Black monkey with a silver mane and lion-like tail tuft|Lion-tailed macaques rarely leave the treetops!|Their tail tip looks like a lion's tail brush.|About 2,500–3,500 lion-tailed macaques.|They live only in India's Western Ghats.|Endangered|Forest fragmentation|20–30 years|35 years
livingstones-fruit-bat|Jungle|Comoros islands in the Indian Ocean|Fruit, nectar, and pollen|Large fruit bat also called Livingstone's flying fox|Livingstone's fruit bats pollinate island trees at night!|They roost in remnant forest patches.|Fewer than 1,200 Livingstone's fruit bats.|Cyclones and deforestation threaten them.|Endangered|Habitat loss and storms|10 years|20 years
magellanic-penguin|Ocean|Coasts of Argentina and Chile — nests in burrows|Small fish and squid in cold Atlantic waters|Medium penguin with two black chest stripes|Magellanic penguins dig burrows to protect chicks from heat and cold!|Oil spills off Argentina have killed thousands.|About 1.1–1.6 million Magellanic penguins.|Largest colony has hundreds of thousands of pairs.|Near Threatened|Oil pollution and climate change|25–30 years|35 years
malachite-sunbird|Jungle|Sub-Saharan Africa forests and gardens|Nectar from flowers with a curved bill|Small bird — males shine metallic green in sunlight|Malachite sunbirds hover at flowers like tiny hummingbirds!|Females are brown and camouflaged on nests.|Common in many African habitats.|Garden flowers help them in cities.|Least Concern|Habitat loss|5–8 years|12 years
marbled-duck|Ocean|Wetlands of the Mediterranean, Middle East, and Asia|Plants, insects, and small aquatic animals|Medium duck with marbled brown plumage|Marbled ducks nest in dense reedbeds near water!|They are quiet and secretive compared to other ducks.|About 50,000–62,000 marbled ducks.|Wetland loss in the Mediterranean hurts them.|Vulnerable|Drained wetlands|10–15 years|20 years
marco-polo-sheep|Grassland|Pamir Mountains of central Asia at very high altitude|Grasses and herbs on steep slopes|Huge wild sheep — horns can span over 1.8 m in old males|Marco Polo sheep were named for the explorer who described them!|Their massive horns are a trophy hunting risk.|About 20,000–25,000 Marco Polo sheep.|Tajikistan holds the largest populations.|Near Threatened|Poaching|12–13 years|18 years
marine-iguana|Ocean|Galápagos rocky shores — unique sea-going lizard|Underwater algae scraped from rocks|Dark iguanas that sneeze salt from nasal glands|Marine iguanas are the only lizards that feed in the ocean!|They shrink body size during bad El Niño years.|About 250,000 marine iguanas on Galápagos.|El Niño and invasive species threaten them.|Vulnerable|Climate swings and predators|12 years|20 years
marsh-deer|Grassland|Wetlands of Argentina, Bolivia, and Paraguay|Aquatic plants in swamps and marshes|Large deer with long legs for wading|Marsh deer have broad hooves that spread on soft mud!|Males carry impressive antlers each season.|About 80,000–90,000 marsh deer.|Wetland drainage is the main threat.|Vulnerable|Habitat loss|10–12 years|18 years
marsican-brown-bear|Forest|Apennine Mountains of central Italy — isolated population|Berries, nuts, and carrion in mountain forests|Brown bear subpopulation with only a few dozen bears|Marsican brown bears are Italy's last wild bears!|They are genetically distinct from Alpine bears.|About 50–60 Marsican brown bears.|Roads and poisoned bait are deadly.|Critically Endangered|Small population and road kills|20–25 years|30 years
mauritius-kestrel|Jungle|Mauritius forests — saved from extinction|Lizards, insects, and small birds|Small falcon that nests in tree holes|Mauritius kestrels dropped to only 4 birds in 1974!|Captive breeding brought them back to hundreds.|About 800–1,000 Mauritius kestrels.|They live only on Mauritius island.|Vulnerable|Invasive species and cyclones|10–15 years|20 years
mediterranean-chameleon|Jungle|Mediterranean scrub from Spain to the Middle East|Insects caught with a sticky tongue shot outward|Small chameleon that changes color slowly| Mediterranean chameleons sway side to side to mimic leaves!|Their eyes move independently to scan for prey.|Tens of thousands in suitable scrub.|Habitat loss in coastal areas.|Least Concern|Development|5–8 years|12 years
mediterranean-monk-seal|Ocean|Caves and remote coasts of the Mediterranean and Atlantic|Fish and octopus in coastal waters|One of the rarest seals — males can weigh 300 kg|Mediterranean monk seals use sea caves as nurseries!|They were hunted since ancient Greek times.|About 700 Mediterranean monk seals.|Greek and Turkish reserves protect caves.|Endangered|Fishing nets and disturbance|30 years|40 years
micronesian-kingfisher|Jungle|Guam and Palau forests — Guam population extinct in wild|Insects, lizards, and small crabs|Colorful kingfisher with a big head and dagger bill|Guam kingfishers vanished in the wild when brown tree snakes arrived!|Captive breeding may reintroduce them.|Hundreds in zoos; wild only on Palau.|Snake invasion wiped out Guam's wild birds.|Extinct in the Wild on Guam|Invasive brown tree snake|10 years|20 years
minke-whale|Ocean|Cold oceans worldwide — smallest baleen whale|Krill and small schooling fish|Whale about 8–9 m long — sleek and fast|Minke whales are one of the fastest baleen whales!|They often approach boats out of curiosity.|Hundreds of thousands in oceans.|Some populations are heavily hunted.|Least Concern to Threatened|Whaling and ship strikes|30–50 years|60 years
mona-monkey|Jungle|West African forests from Ghana to Cameroon|Fruits, leaves, and insects|Medium guenon with white chest ruff and sharp cheek whiskers|Mona monkeys store food in cheek pouches like hamsters!|They mix with other monkey species in large troops.|Common in West African forests.|Bushmeat hunting is a threat.|Least Concern|Hunting and logging|20 years|30 years
morelets-crocodile|Jungle|Freshwater wetlands of Mexico, Belize, and Guatemala|Fish, birds, and small mammals|Medium crocodile with a broad snout|Morelet's crocodiles were heavily hunted for their skins!|They nest in mound nests on riverbanks.|Several thousand in Central American wetlands.|Protection laws helped recovery.|Least Concern|Habitat loss|50 years|70 years
mouflon|Grassland|Mountains of Corsica, Sardinia, and Europe|Grasses and herbs on rocky slopes|Wild sheep — ancestor of many domestic breeds|Mouflon rams crash horns in spectacular mountain fights!|They are shy and flee at the first sign of danger.|About 60,000 mouflon in Europe.|Hunting is managed in many parks.|Least Concern|Hybridization with domestic sheep|8–12 years|18 years
mountain-gazelle|Desert|Hills and deserts of Israel, Palestine, and Arabia|Grasses and acacia leaves|Small graceful gazelle with curved horns|Mountain gazelles can survive without drinking if plants are moist!|They bound away with stiff-legged leaps.|About 3,000–4,000 mountain gazelles.|Israeli reserves protect key populations.|Vulnerable|Habitat loss and roads|12–15 years|20 years
napoleon-wrasse|Ocean|Indo-Pacific coral reefs — huge reef fish|Clams, sea urchins, and crustaceans|Massive fish that can weigh 190 kg with a bump on the head|Napoleon wrasse change from females to males as they grow!|Their thick lips look like they're wearing lipstick.|Declining across much of their reef range.|Live fish trade removed many big individuals.|Endangered|Overfishing for luxury food|30 years|40 years
nile-lechwe|Grassland|Swamps of South Sudan and Ethiopia|Aquatic grasses in floodplains|Antelope with long horns and oily water-repellent coat|Nile lechwe run through swamp water with splayed hooves!|Males have sweeping horns used in fights.|About 30,000–40,000 Nile lechwe.|Civil conflict and dams threaten wetlands.|Endangered|Wetland loss and hunting|10–12 years|18 years
noddy|Ocean|Tropical islands — nests on beaches and shrubs|Small fish and squid snatched from the surface|Medium tern-like seabird with a wedge-shaped tail|Noddies nod to each other during courtship displays!|They often nest near seabird colonies on islands.|Hundreds of thousands on tropical islands.|Island predators can hurt colonies.|Least Concern|Invasive rats and cats|15–20 years|25 years
north-african-ostrich|Desert|Sahel and Sahara edge in North Africa|Plants, seeds, and occasional insects|World's largest bird — cannot fly but runs 70 km/h|North African ostriches have pink neck skin in breeding season!|One egg can weigh as much as two dozen chicken eggs.|Wild populations are very small.|Reintroduction projects use captive birds.|Endangered|Hunting and habitat loss|30–40 years|50 years
nubian-ibex|Desert|Rocky deserts of Egypt, Sudan, and the Middle East|Desert grasses and leaves on cliff ledges|Wild goat with backward-curving horns|Nubian ibex stand on cliff edges unreachable by most predators!|Kids learn to climb days after birth.|About 4,500 Nubian ibex.|Israel's desert reserves protect some herds.|Vulnerable|Hunting and scarce water|15–17 years|22 years
olive-baboon|Grassland|Savannas and woodlands across Africa|Omnivorous — fruits, roots, insects, and small animals|Large baboon with a dog-like muzzle|Olive baboon troops have complex friendships and rivalries!|They sleep in cliffs or tall trees at night.|Hundreds of thousands across Africa.|Leopards are their main predator.|Least Concern|Habitat loss|20–30 years|40 years
oriental-pied-hornbill|Jungle|Forests of Southeast Asia and the Indian subcontinent|Fruits and small animals|Black-and-white hornbill with a big yellow bill|Female oriental pied hornbills seal themselves in tree holes to nest!|The male feeds her through a narrow slit for weeks.|Common in many Asian forests.|Logging reduces nest trees.|Least Concern|Deforestation|20 years|35 years
orinoco-crocodile|Jungle|Orinoco River basin in Venezuela and Colombia|Fish, birds, and mammals in rivers|One of the largest crocodiles — pale tan with dark bands|Orinoco crocodiles were hunted almost to extinction!|Reintroduction releases captive-bred juveniles.|About 1,500 Orinoco crocodiles.|Venezuela leads recovery efforts.|Critically Endangered|Hunting and dam building|70–80 years|80+ years
palestine-sunbird|Desert|Middle East gardens and scrub — male has metallic purple|Nectar from flowers and small insects|Tiny bird that hovers like a hummingbird|Palestine sunbirds build hanging nests in bushes!|Males shine purple-green in sunlight.|Common in Middle Eastern towns and wild scrub.|Garden plants help them survive.|Least Concern|Habitat change|4–6 years|10 years
palmchat|Jungle|Hispaniola (Haiti and Dominican Republic) only|Fruits, especially palm fruits and berries|National bird of Dominican Republic — brown with streaks|Palmchats nest in huge communal stick nests in palm trees!|They are related to waxwings, not true chats.|Hundreds of thousands on Hispaniola.|Island deforestation is a threat.|Least Concern|Habitat loss|12 years|20 years
panther-chameleon|Jungle|Madagascar forests — males show vivid colors|Insects caught with a lightning-fast tongue|Large chameleon — males can be turquoise, red, or green|Panther chameleons' colors show mood, temperature, and rivalry!|Each eye swivels separately to watch for prey.|Popular in pet trade but wild in Madagascar.|Forest loss threatens Madagascar chameleons.|Least Concern|Deforestation|5–7 years|10 years
persian-leopard|Forest|Forests and mountains of Iran and the Caucasus|Wild goats, deer, and boar|Large spotted leopard — biggest leopard in the region|Persian leopards still roam Iran's mountains where other big cats vanished!|Camera traps photograph them on snowy trails.|Fewer than 1,000 Persian leopards.|Iran holds the largest remaining population.|Endangered|Poaching and prey loss|10–12 years|20 years
philippine-eagle|Jungle|Philippine rainforests on four main islands|Flying lemurs, monkeys, and hornbills|One of the largest and most powerful eagles|Philippine eagles have a shaggy crest they raise when alarmed!|A pair needs 100 square km of forest.|About 400 breeding pairs remain.|They are the national bird of the Philippines.|Critically Endangered|Deforestation|30–60 years|50 years
pied-kingfisher|Ocean|Rivers and lakes across Africa and Asia|Fish caught by hovering then diving straight down|Black-and-white kingfisher — often perches on wires| Pied kingfishers hover high above water before diving!|They are among the few kingfishers that hover.|Widespread and common near water.|Water pollution hurts local numbers.|Least Concern|Pollution|5–10 years|15 years
pileated-gibbon|Jungle|Forests of Thailand, Cambodia, and Laos|Fruits and leaves in the canopy|Small ape with white hands and dark fur|Pileated gibbons sing duets that bond male-female pairs!|Yellow-cheeked and pileated types differ by region.|Thousands remain but forests are fragmented.|Gibbon songs disappear when forests are cut.|Endangered|Logging and hunting|25 years|40 years
pink-pigeon|Jungle|Mauritius forests — rescued from near extinction|Pink pigeon eats fruits and buds in native trees|Plump pinkish pigeon found only on Mauritius|Pink pigeons dropped to only 10 birds in 1990!|Captive breeding saved them from extinction.|About 400–500 pink pigeons on Mauritius.|Invasive rats and cats still threaten nests.|Endangered|Invasive species|10–15 years|20 years
pink-river-dolphin|Ocean|Amazon and Orinoco river systems|Fish in muddy freshwater channels|Botos turn pinker with age — flexible neck vertebrae|Pink river dolphins use echolocation in chocolate-colored rivers!|Local legends say they transform into people at festivals.|Tens of thousands in the Amazon.|Dams and fishing threaten some rivers.|Endangered|Dams and entanglement|30 years|40 years
pink-backed-pelican|Ocean|Freshwater lakes and rivers of sub-Saharan Africa|Fish scooped in a pink-backed bill pouch|Medium pelican — nests in trees unlike many pelicans|Pink-backed pelicans nest in colonies high in waterfront trees!|They cooperate to herd fish in shallow water.|About 50,000–100,000 pink-backed pelicans.|Wetland loss is the main concern.|Least Concern|Habitat loss|15–20 years|30 years
pygmy-hippo|Jungle|West African rainforest swamps and streams|Leaves, ferns, and fallen fruit at night|Mini hippo about 1.5 m long — shy and solitary|Pygmy hippos mark trails with spinning tail dung scatter!|They are far rarer than common hippos.|About 2,000–3,000 pygmy hippos.|Liberia's forests hold the most.|Endangered|Logging and hunting|30–40 years|50 years
pyrenean-chamois|Forest|Pyrenees Mountains between France and Spain|Alpine grasses and herbs|Goat-antelope with black face stripes and hooked horns|Pyrenean chamois leap between razor-thin ledges!|Winter fur is thick and dark; summer coat is reddish.|About 25,000 Pyrenean chamois.|Hunting is regulated in both countries.|Least Concern|Climate change|14–15 years|22 years
red-colobus|Jungle|African coastal and rainforest trees|Leaves — specialized stomach to digest tough foliage|Reddish monkey with a tufted head and no thumbs|Red colobus monkeys digest leaves slowly like forest cows!|They are important prey for chimpanzees.|Several thousand across many subspecies.|Some island forms are Critically Endangered.|Endangered|Hunting and logging|20 years|30 years
red-crowned-crane|Grassland|Wetlands of China, Korea, and Japan|Insects, fish, and plants in marshes|Large white crane with a red crown of bare skin|Red-crowned cranes dance and bow in beautiful pair displays!|They symbolize longevity in East Asian art.|About 2,750 red-crowned cranes.|China and Russia protect key wetlands.|Vulnerable|Wetland loss|30–40 years|60 years
red-tailed-tropicbird|Ocean|Tropical Pacific and Indian Ocean islands|Flying fish and squid caught in plunge dives|White seabird with two long red tail streamers|Red-tailed tropicbirds hover before diving into the sea!|They nest on remote islands safe from predators.|Hundreds of thousands on ocean islands.|Invasive species on islands hurt colonies.|Least Concern|Invasive predators|15–20 years|30 years
reef-shark|Ocean|Coral reefs in tropical oceans worldwide|Fish, rays, and crustaceans on reefs|Medium shark — gray reef shark is fast and social|Reef sharks patrol reef edges in coordinated groups!|They keep fish populations healthy on reefs.|Millions across Indo-Pacific reefs.|Overfishing removed many from busy reefs.|Near Threatened|Overfishing|15–25 years|30 years
rhinoceros-iguana|Jungle|Hispaniola dry forests and rocky areas|Leaves, flowers, and fruits|Large gray iguana with bumpy nose scales like rhino horn|Rhinoceros iguanas bask on rocks to warm up each morning!|They can whip predators with a muscular tail.|Several thousand on Hispaniola.|Habitat loss and hunting continue.|Endangered|Deforestation|20 years|35 years
ricords-iguana|Jungle|Dominican Republic — smaller range than rhinoceros iguana|Plants and fruits in dry forest|Critically endangered iguana with dark bands|Ricord's iguanas live only in a few valleys in the Dominican Republic!|Captive breeding supports wild releases.|Fewer than 2,500 Ricord's iguanas.|Their forest is fragmented by farms.|Critically Endangered|Habitat loss|20 years|30 years
rose-ringed-parakeet|Jungle|Originally South Asia — now in cities worldwide|Fruits, buds, and seeds|Bright green parakeet with black neck ring in males|Rose-ringed parakeets thrive in cities from London to Tokyo!|Wild flocks in Asia nest in tree holes.|Millions in South Asia; feral millions globally.|Invasive in some countries but secure in native range.|Least Concern|Pet trade historically|15–25 years|35 years
saimaa-ringed-seal|Arctic|Lake Saimaa in Finland — only freshwater ringed seal|Fish in freshwater ice holes|Small seal with a ring pattern on pale fur|Saimaa ringed seals need snow drifts on lake ice for dens!|Climate warming reduces safe snow caves.|About 400 Saimaa ringed seals.|They live only in one Finnish lake.|Endangered|Climate change and nets|15–20 years|30 years
saint-lucia-parrot|Jungle|Saint Lucia rainforests — national symbol|Fruits and nuts in forest canopy|Colorful parrot with green, blue, and red feathers|Saint Lucia parrots were saved from near extinction by local pride!|They are called jacquot on the island.|About 500–1,000 Saint Lucia parrots.|Hurricanes and habitat loss are threats.|Vulnerable|Hurricanes|30 years|50 years
saint-vincent-parrot|Jungle|Saint Vincent cloud forests|Fruits and seeds in montane forest|Large green Amazona parrot with brown-purple chest|Saint Vincent parrots are the national bird of Saint Vincent!|Only a few hundred survive in the wild.|About 800 Saint Vincent parrots.|Volcanic eruptions can destroy forest.|Vulnerable|Habitat loss|30 years|50 years
sand-gazelle|Desert|Deserts of the Middle East and central Asia|Desert plants and grasses|Small gazelle adapted to extreme heat|Sand gazelles shrink their heart and liver in drought to save water!|They get moisture from plants they eat.|About 100,000–120,000 sand gazelles.|Some populations are heavily hunted.|Vulnerable|Hunting and habitat loss|10–12 years|18 years
sarus-crane|Grassland|Wetlands of India, Southeast Asia, and Australia|Tall wetland plants, grains, and insects|Tallest flying bird — red head and gray body|Sarus cranes mate for life and dance together!|Indian legend calls them symbols of marital love.|About 15,000–20,000 sarus cranes.|Wetland drainage is the biggest threat.|Vulnerable|Habitat loss|20–30 years|40 years
scarlet-ibis|Jungle|Coastal mangroves and wetlands of South America|Crustaceans and insects — diet makes them red|Brilliant red wading bird with a curved bill|Scarlet ibis chicks start brown and turn red as they eat shrimp!|They roost in mangrove trees in huge red flocks.|Tens of thousands in Trinidad and Venezuela.|Mangrove loss threatens roost sites.|Least Concern|Habitat loss|16 years|25 years
seychelles-warbler|Jungle|Seychelles islands — once down to 26 birds on one island|Insects in coastal woodland|Small gray warbler saved by island conservation|Seychelles warblers help each other feed chicks — cooperative breeding!|Translocations restored them to several islands.|About 2,800 Seychelles warblers.|Island reserves keep them safe.|Near Threatened|Climate and invasive species|8 years|15 years
sitatunga|Jungle|African swamps from Senegal to Zambia|Aquatic plants in papyrus swamps|Antelope with splayed hooves for walking on floating vegetation|Sitatunga hide in swamps with only their nose above water!|Males have twisted horns and a shaggy coat.|About 170,000 sitatunga.|Swamp drainage is the main threat.|Least Concern|Wetland loss|15–19 years|25 years
smooth-coated-otter|Jungle|Rivers and coasts of South and Southeast Asia|Fish, frogs, and crustaceans|Social otter that hunts in family groups|Smooth-coated otters have been seen cooperatively hunting with humans!|They slide on mud banks and groom constantly.|Tens of thousands but declining.|Wetland pollution and fishing nets hurt them.|Vulnerable|Pollution and habitat loss|10–15 years|20 years
socotra-cormorant|Ocean|Islands and coasts of the Persian Gulf|Fish caught by pursuit diving|Large cormorant — colonies can hold thousands|Socotra cormorants nest in enormous coastal colonies!|Oil spills in the Gulf have killed many.|About 110,000–230,000 Socotra cormorants.|The Gulf's oil industry threatens their sea.|Vulnerable|Oil pollution|10–15 years|20 years
soemmerrings-gazelle|Desert|Horn of Africa deserts and semi-deserts|Desert grasses and acacia leaves|Medium gazelle with a white rump and S-shaped horns|Soemmerring's gazelles were once abundant on the Horn of Africa!|They need access to water or very moist plants.|About 3,500–5,000 remain.|War and hunting reduced numbers sharply.|Vulnerable|Hunting and drought|10–12 years|18 years
somali-ostrich|Desert|Horn of Africa arid savannas|Plants and seeds — blue-skinned legs in males|Large flightless bird — Somali ostrich has gray neck|Somali ostrich males develop bright blue skin on legs in breeding!|They are a distinct species from common ostrich.|About 140,000 Somali ostriches.|Hunting and egg collection occur.|Vulnerable|Hunting|30–40 years|50 years
somali-wild-ass|Desert|Deserts of Eritrea, Ethiopia, and Somalia|Grasses and herbs in arid plains|Smaller than kulan with thin legs for desert travel|Somali wild asses can lose 30% of body water and survive!|They are ancestors of domestic donkeys.|Fewer than 200 Somali wild asses.|They may be the rarest equid on Earth.|Critically Endangered|Hunting and competition with livestock|25–30 years|40 years
southern-ground-hornbill|Grassland|Savannas of southern and East Africa|Snakes, insects, and small animals on the ground|Large black bird with red face patch and booming call|Southern ground hornbills call so loudly they can be heard 3 km away!|Families raise one chick every few years.|About 1,500–2,000 in South Africa.|They need huge territories to survive.|Vulnerable|Habitat loss and persecution|50–60 years|70 years
southern-right-whale|Ocean|Sub-Antarctic and temperate southern oceans|Krill and copepods filtered from cold water|Massive whale with callosities on the head|Southern right whales were named because they were the right whale to hunt!|They swim close to shore and are slow swimmers.|About 10,000 southern right whales.|Numbers recover slowly after whaling ban.|Least Concern|Ship strikes and entanglement|50–70 years|80 years
stellers-sea-eagle|Arctic|Coasts of Russia, Japan, and Korea in winter|Fish and waterbirds — especially salmon runs|Huge eagle — wingspan can reach 2.5 m|Steller's sea eagles have white shoulders and giant yellow bills!|They gather by hundreds on Japanese ice floes.|About 4,000–5,000 Steller's sea eagles.|Dam projects threaten salmon rivers.|Vulnerable|Habitat loss and pollution|20–25 years|35 years
steppe-eagle|Grassland|Open steppes from eastern Europe to Mongolia|Carrion and small mammals on open plains|Large brown eagle — migrates to Africa and India|Steppe eagles migrate thousands of kilometers each autumn!|Wind turbines and power lines kill many migrants.|About 50,000–75,000 steppe eagles.|Population is declining.|Endangered|Power lines and habitat loss|15–20 years|30 years
striped-hyena|Desert|Dry country from North Africa to India|Carrion, insects, and fruit — scavenger and hunter|Shaggy hyena with vertical stripes and a mane|Striped hyenas can crunch bones with incredibly strong jaws!|They are mostly silent compared to laughing spotted hyenas.|About 5,000–14,000 striped hyenas.|Persecution as pests hurts their numbers.|Near Threatened|Poisoning and hunting|12 years|20 years
swift|Forest|Towns and cliffs worldwide — masters of the air|Flying insects caught in the air|Small bird that can sleep while flying on migration|Common swifts may not land for 10 months while migrating!|They nest in old buildings and church towers.|Millions across Europe and Asia.|Building repairs block nest holes.|Least Concern|Nest site loss|9 years|20 years
sao-tome-grosbeak|Jungle|São Tomé island forests in the Gulf of Guinea|Seeds and fruits with a massive bill|Large critically endangered finch| São Tomé grosbeak has one of the biggest beaks of any songbird!|It was only discovered by science in 1888.|Fewer than 250 mature São Tomé grosbeaks.|Island forest is being cleared.|Critically Endangered|Deforestation|10 years|15 years
taiwan-blue-magpie|Forest|Mountains of Taiwan — blue and white with long tail|Insects, fruit, and small animals|Stunning blue magpie with a white-tipped tail|Taiwan blue magpies travel in noisy family groups!|They are protected as Taiwan's national bird.|About 3,000–5,000 Taiwan blue magpies.|They need mature forest.|Least Concern|Habitat loss|10 years|20 years
tarsier|Jungle|Southeast Asian islands — Philippines and Indonesia|Insects, lizards, and small birds at night|Tiny primate with enormous eyes — each eye bigger than its brain|Tarsiers can turn their head 180 degrees like an owl!|They are the only entirely carnivorous primates.|Tens of thousands but several species are threatened.|Tourism and habitat loss stress them.|Vulnerable|Deforestation|12 years|20 years
tatra-chamois|Forest|Tatra Mountains on Poland-Slovakia border|Alpine grasses and herbs|Mountain goat-antelope with curved horns|Tatra chamois survived near extinction after World War I!|Strict protection rebuilt herds in the Tatras.|About 1,000–1,500 Tatra chamois.|Small range makes them vulnerable.|Vulnerable|Small population|15 years|22 years
timor-green-pigeon|Jungle|Timor and Wetar island forests|Fruits in the canopy — especially figs|Green pigeon with a purple patch on the back|Timor green pigeons are hard to spot in leafy treetops!|Island forest loss threatens them.|Unknown — likely a few thousand.|Timor's forests are under pressure.|Vulnerable|Deforestation|10 years|15 years
tree-kangaroo|Jungle|New Guinea and Queensland rainforests|Leaves and fruits high in the canopy|Kangaroo that climbs trees with strong forearms|Tree kangaroos can leap 9 meters from branch to branch!|They are the only kangaroos that live mostly in trees.|Unknown — several species are Critically Endangered.|Logging destroys their forest.|Endangered|Habitat loss|15 years|25 years
tree-climbing-lion|Grassland|Ishasha sector of Queen Elizabeth Park, Uganda|Buffalo and antelope in savanna woodlands|Lions famous for resting on fig tree branches|Tree-climbing lions nap in acacia and fig trees to escape flies!|Only some prides in Uganda and Tanzania climb often.|Same population as other African lions.|Habitat loss and conflict threaten lions.|Vulnerable|Habitat loss and hunting|10–14 years|20 years
waliya-ibex|Grassland|Simien Mountains of Ethiopia — cliff specialist|Alpine grasses and herbs on ledges|Endemic ibex with massive ridged horns|Waliya ibex live on cliffs above 2,500 m in Ethiopia!|Their horns can grow over 1 meter long.|About 500–550 Waliya ibex.|Simien Mountains National Park protects them.|Endangered|Small population|12–15 years|20 years
west-african-crocodile|Jungle|West African rivers and wetlands|Fish and mammals in freshwater|Medium crocodile — sacred in some West African cultures|West African crocodiles were once thought to be a mythic species!|They tolerate both fresh and brackish water.|Several thousand across West Africa.|Habitat loss and hunting continue.|Vulnerable|Habitat loss|50 years|70 years
west-african-manatee|Ocean|Coastal rivers and estuaries of West Africa|Aquatic plants in slow-moving water|Gentle manatee with paddle tail and whiskered face|West African manatees migrate upstream when rains flood rivers!|They are hunted for meat in some regions.|About 10,000 West African manatees.|Exact counts are uncertain.|Vulnerable|Hunting and dam building|30 years|50 years
west-indian-flamingo|Ocean|Caribbean islands and Yucatán — pinkest flamingo|Brine shrimp and algae filtered from salty lagoons|Tall pink flamingo — national bird of Bahamas|West Indian flamingos nest in huge pink colonies on mud flats!|Their pink color comes from shrimp in the diet.|About 80,000–90,000 West Indian flamingos.|Bahamas and Cuba protect major colonies.|Least Concern|Habitat loss|15–20 years|30 years
west-indian-manatee|Ocean|Caribbean, Gulf of Mexico, and Atlantic U.S. coasts|Seagrasses and aquatic plants|Bulky gray mammal — related to elephants|West Indian manatees have fingernails on their flippers!|They surface every few minutes to breathe.|About 7,000–10,000 West Indian manatees.|Boat strikes kill many each year.|Vulnerable|Boat hits and habitat loss|40 years|60 years
west-indian-whistling-duck|Jungle|Caribbean wetlands and mangroves|Plants, seeds, and insects|Long-legged duck that whistles rather than quacks|West Indian whistling ducks fly to fruit trees at night to feed!|They nest in tree cavities and on the ground.|Tens of thousands in the Caribbean.|Wetland loss is a concern.|Least Concern|Habitat loss|10 years|20 years
whale-shark|Ocean|Tropical oceans worldwide — largest fish|Plankton and small fish filtered through wide mouth|Shark longer than a school bus but gentle to divers|Whale sharks have unique spot patterns like human fingerprints!|They swim slowly with mouth wide open filtering food.|Tens of thousands worldwide.|Tourism and ship strikes can injure them.|Endangered|Fishing, ship strikes|70–100 years|80+ years
white-stork|Grassland|Open fields and wetlands across Europe and Asia|Frogs, insects, and small animals in fields|Tall white bird with black wing feathers|White storks migrate to Africa — nests on rooftops and poles!|Legend says they bring babies, but they really bring spring.|About 700,000 white storks.|Populations are stable or growing.|Least Concern|Power lines|15–20 years|30 years
white-tailed-eagle|Ocean|Coastal cliffs and lakes across Eurasia|Fish, waterbirds, and carrion|Huge eagle with white tail — wingspan over 2 m|White-tailed eagles lock talons in midair courtship displays!|Reintroduction returned them to Scotland.|About 20,000–50,000 white-tailed eagles.|Water pollution once hurt them badly.|Least Concern|Lead poisoning|15–25 years|35 years
yelkouan-shearwater|Ocean|Mediterranean islands — nests in burrows|Fish and squid caught underwater|Medium seabird that glides low over waves|Yelkouan shearwaters visit colonies only at night to avoid gulls!|Light pollution disorients fledglings.|About 55,000–75,000 Yelkouan shearwaters.|Invasive predators on islands hurt breeding.|Vulnerable|Invasive species and fishing|15–20 years|30 years
yellow-eyed-penguin|Ocean|Coasts of New Zealand — nests in coastal forest|Fish and squid in cold southern waters|Medium penguin with pale yellow eyes and head band|Yellow-eyed penguins are among the rarest penguins!|They nest under trees, unlike most penguin burrowers.|About 2,000–3,000 yellow-eyed penguins.|Predators and fishing nets hurt them.|Endangered|Predators and fisheries|20 years|30 years
""".strip()

NAME_FIX = {
    "aldabra-tortoise": "Aldabra Giant Tortoise",
    "greater-flamingo": "Greater Flamingo",
    "chamois": "Chamois",
    "ethiopian-wolf": "Ethiopian Wolf",
    "flying-fox": "Flying Fox",
    "galapagos-giant-tortoises": "Galápagos Giant Tortoise",
    "jaguarundi": "Jaguarundi",
    "magnificent-frigatebird": "Magnificent Frigatebird",
    "sao-tome-grosbeak": "São Tomé Grosbeak",
    "taiwan-blue-magpie": "Taiwan Blue Magpie",
    "tree-climbing-lion": "Tree-Climbing Lion",
    "hectors-dolphin": "Hector's Dolphin",
    "bairds-tapir": "Baird's Tapir",
    "geoffroys-tamarin": "Geoffroy's Tamarin",
    "soemmerrings-gazelle": "Soemmerring's Gazelle",
    "stellers-sea-eagle": "Steller's Sea Eagle",
    "ricords-iguana": "Ricord's Iguana",
    "livingstones-fruit-bat": "Livingstone's Fruit Bat",
}


def expand(row):
    aid, habitat, lives, diet, size, fun, extra, pop1, pop2, status, threat, wild, cap = row
    name = NAME_FIX.get(aid, aid.replace("-", " ").title())
    deaths = f"Often die from: {threat}."
    return {
        "id": aid,
        "name": name,
        "habitat": habitat,
        "livesIn": lives,
        "diet": diet,
        "size": size,
        "funFact": fun,
        "extraFact": extra,
        "funFacts": [fun],
        "didYouKnowFacts": list(dict.fromkeys([extra, pop2, f"Conservation status: {status}."]))[:3],
        "livesInFacts": [lives],
        "dietFacts": [diet],
        "sizeFacts": [size],
        "lifespanFacts": [
            f"In the wild: Usually live about {wild}.",
            f"In captivity: With expert care, they may live about {cap}.",
            deaths,
        ],
        "lifespan": f"In the wild: Usually live about {wild}.",
        "populationFacts": [pop1, pop2],
        "population": pop1,
        "conservationFacts": [
            f"Status: {status}.",
            f"Main threats include {threat.lower()}.",
        ],
        "conservation": f"Status: {status}.",
    }


def main():
    profiles = {}
    for line in LINES.splitlines():
        line = line.strip()
        if not line:
            continue
        row = line.split("|")
        if len(row) != 13:
            raise ValueError(f"Bad row ({len(row)} fields): {line[:60]}")
        prof = expand(row)
        profiles[prof["id"]] = prof
    out = ROOT / "strong_profiles.json"
    out.write_text(json.dumps(profiles, ensure_ascii=False, indent=2), encoding="utf-8")
    print(f"Wrote {len(profiles)} profiles to {out.name}")


if __name__ == "__main__":
    main()
